//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Contacts/CNContactStore.h>

@interface CNContactStore (DaemoniOSLibrary)
- (_Bool)clearWithChangeAnchor:(id)arg1 error:(id *)arg2;	// IMP=0x00000001001d8e64
@end

