//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SDXPCDaemon.h"

#import "SDAirDropAlertManager-Protocol.h"
#import "SDAirDropTransferManagerProtocol-Protocol.h"

@class NSArray, NSMutableDictionary, NSObject, NSString;
@protocol SDAirDropAlertManagerDelegate;

__attribute__((visibility("hidden")))
@interface SDAirDropTransferManager : SDXPCDaemon <SDAirDropTransferManagerProtocol, SDAirDropAlertManager>
{
    NSObject<SDAirDropAlertManagerDelegate> *delegate;	// 8 = 0x8
    NSObject<SDAirDropAlertManagerDelegate> *_classroomDelegate;	// 16 = 0x10
    NSMutableDictionary *_transferIdentifierToTransfer;	// 24 = 0x18
    NSMutableDictionary *_transferIdentifierToHandler;	// 32 = 0x20
    NSArray *_kvoObservingKeys;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x000000010007add8
@property(retain) NSArray *kvoObservingKeys; // @synthesize kvoObservingKeys=_kvoObservingKeys;
@property(retain) NSMutableDictionary *transferIdentifierToHandler; // @synthesize transferIdentifierToHandler=_transferIdentifierToHandler;
@property(retain) NSMutableDictionary *transferIdentifierToTransfer; // @synthesize transferIdentifierToTransfer=_transferIdentifierToTransfer;
@property(nonatomic) __weak NSObject<SDAirDropAlertManagerDelegate> *classroomDelegate; // @synthesize classroomDelegate=_classroomDelegate;
@property(nonatomic) __weak NSObject<SDAirDropAlertManagerDelegate> *delegate; // @synthesize delegate;
- (id)itemTypesForTransfer:(id)arg1;	// IMP=0x000000010007a734
- (void)loadAllPersistedTransfers;	// IMP=0x000000010007a3d8
- (void)cleanUpURL:(id)arg1;	// IMP=0x000000010007a260
- (id)transferURLForTransfer:(id)arg1;	// IMP=0x000000010007a178
- (id)persistedTransfersBaseURL;	// IMP=0x000000010007a124
- (void)setTransferState:(unsigned long long)arg1 forTransfer:(id)arg2 shouldNotify:(_Bool)arg3 shouldCleanup:(_Bool)arg4;	// IMP=0x0000000100079fc0
- (void)setTransferState:(unsigned long long)arg1 forTransfer:(id)arg2 shouldNotify:(_Bool)arg3;	// IMP=0x0000000100079fb0
- (void)failTransfer:(id)arg1 withState:(unsigned long long)arg2 failureReason:(unsigned long long)arg3;	// IMP=0x0000000100079dac
- (void)handlerFailedForTransfer:(id)arg1;	// IMP=0x0000000100079b9c
- (void)setHandler:(id)arg1 forTransfer:(id)arg2;	// IMP=0x0000000100079874
- (id)determineHandlerForTransfer:(id)arg1;	// IMP=0x000000010007943c
- (void)connectionInvalidated:(id)arg1;	// IMP=0x0000000100079358
- (void)connectionEstablished:(id)arg1;	// IMP=0x00000001000790c0
- (_Bool)shouldAcceptNewConnection:(id)arg1;	// IMP=0x00000001000790b8
- (id)remoteObjectInterface;	// IMP=0x000000010007909c
- (id)exportedInterface;	// IMP=0x0000000100079080
- (id)machServiceName;	// IMP=0x0000000100079074
- (void)transfer:(id)arg1 actionTriggeredForAction:(id)arg2;	// IMP=0x0000000100078f50
- (void)transferUserResponseUpdated:(id)arg1;	// IMP=0x0000000100078a30
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x00000001000788d0
- (void)finishedEventForRecordID:(id)arg1 withResults:(id)arg2;	// IMP=0x00000001000787c4
- (void)errorEventForRecordID:(id)arg1 withResults:(id)arg2;	// IMP=0x0000000100078690
- (void)cancelEventForRecordID:(id)arg1 withResults:(id)arg2;	// IMP=0x0000000100078584
- (void)progressEventForRecordID:(id)arg1 withResults:(id)arg2;	// IMP=0x0000000100078460
- (void)askEventForRecordID:(id)arg1 withResults:(id)arg2;	// IMP=0x0000000100077fd8
- (void)cleanUpTransfer:(id)arg1;	// IMP=0x0000000100077eb4
- (void)removeTransfer:(id)arg1 shouldCleanup:(_Bool)arg2;	// IMP=0x0000000100077c80
- (void)notifyObserversOfRemovedTransfer:(id)arg1;	// IMP=0x0000000100077bcc
- (void)notifyObserversOfUpdatedTransfer:(id)arg1;	// IMP=0x0000000100077b24
- (void)_enumerateRemoteObjectProxiesUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x0000000100077b18
- (void)_remoteObjectProxyForConnection:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;	// IMP=0x0000000100077ac8
- (void)invalidate;	// IMP=0x0000000100077a94
- (void)activate;	// IMP=0x0000000100077a60
- (id)init;	// IMP=0x000000010007790c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

