//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SDAirDropClientDelegate-Protocol.h"
#import "SDAirDropIconCacherDelegate-Protocol.h"
#import "WPAWDLDelegate-Protocol.h"

@class NSArray, NSMutableDictionary, NSMutableSet, NSNumber, NSString, NSTimer, SDStatusMonitor, SDXPCHelperConnection, WPAWDL;
@protocol OS_xpc_object, SDBonjourBrowserDelegate;

__attribute__((visibility("hidden")))
@interface SDBonjourBrowser : NSObject <SDAirDropClientDelegate, SDAirDropIconCacherDelegate, WPAWDLDelegate>
{
    _Bool _isAirDrop;	// 8 = 0x8
    _Bool _isLegacyMode;	// 9 = 0x9
    _Bool _isNetBIOS;	// 10 = 0xa
    _Bool _isWorkgroups;	// 11 = 0xb
    int _maxServices;	// 12 = 0xc
    NSString *_domain;	// 16 = 0x10
    WPAWDL *_proximity;	// 24 = 0x18
    NSString *_bundleID;	// 32 = 0x20
    NSNumber *_isFinder;	// 40 = 0x28
    long long _mode;	// 48 = 0x30
    unsigned int _awdlIndex;	// 56 = 0x38
    NSString *_browserID;	// 64 = 0x40
    NSString *_sessionID;	// 72 = 0x48
    NSTimer *_restartTimer;	// 80 = 0x50
    int _transfersInitiated;	// 88 = 0x58
    int _transfersCompleted;	// 92 = 0x5c
    SDStatusMonitor *_monitor;	// 96 = 0x60
    struct _DNSServiceRef_t *_connection;	// 104 = 0x68
    double _firstTime;	// 112 = 0x70
    double _startTime;	// 120 = 0x78
    NSMutableSet *_discoveredPeers;	// 128 = 0x80
    NSMutableDictionary *_servers;	// 136 = 0x88
    NSObject<OS_xpc_object> *_xpcConnection;	// 144 = 0x90
    NSMutableDictionary *_iconCache;	// 152 = 0x98
    NSMutableDictionary *_dnsQueries;	// 160 = 0xa0
    NSMutableDictionary *_serverCache;	// 168 = 0xa8
    NSMutableDictionary *_iconCachers;	// 176 = 0xb0
    NSMutableDictionary *_airDropRequests;	// 184 = 0xb8
    struct __CFDictionary *_identityQueries;	// 192 = 0xc0
    SDXPCHelperConnection *_helperConnection;	// 200 = 0xc8
    NSArray *_types;	// 208 = 0xd0
    id <SDBonjourBrowserDelegate> _delegate;	// 216 = 0xd8
}

+ (void)updateRPIdentityForAccountID:(id)arg1 withAirDropClientInfo:(id)arg2;	// IMP=0x00000001001097b0
- (void).cxx_destruct;	// IMP=0x000000010010c748
@property int transfersCompleted; // @synthesize transfersCompleted=_transfersCompleted;
@property int transfersInitiated; // @synthesize transfersInitiated=_transfersInitiated;
@property(retain) NSObject<OS_xpc_object> *xpcConnection; // @synthesize xpcConnection=_xpcConnection;
@property __weak id <SDBonjourBrowserDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, copy) NSString *domain; // @synthesize domain=_domain;
@property(readonly, copy) NSArray *types; // @synthesize types=_types;
@property(copy) NSString *sessionID; // @synthesize sessionID=_sessionID;
@property(nonatomic) __weak SDXPCHelperConnection *helperConnection; // @synthesize helperConnection=_helperConnection;
@property(copy, nonatomic) NSString *bundleID; // @synthesize bundleID=_bundleID;
@property(readonly, copy) NSString *description;
- (void)restartAfterDelay:(double)arg1;	// IMP=0x000000010010c49c
- (void)queryRecordTimerCallBack:(id)arg1;	// IMP=0x000000010010c44c
- (void)handleQueryCallBack:(unsigned int)arg1 error:(int)arg2 fullname:(const char *)arg3 rrtype:(unsigned short)arg4 rdlen:(unsigned short)arg5 rdata:(const void *)arg6;	// IMP=0x000000010010c38c
- (void)processNULLRecordUpdate:(const char *)arg1 rdlen:(unsigned short)arg2 rdata:(const void *)arg3;	// IMP=0x000000010010c260
- (void)processTXTRecordUpdate:(const char *)arg1 rdlen:(unsigned short)arg2 rdata:(const void *)arg3;	// IMP=0x000000010010bce8
- (id)valueForKey:(id)arg1 inTXTRecord:(const void *)arg2 withLength:(unsigned short)arg3;	// IMP=0x000000010010bc48
- (id)serviceFromServiceName:(id)arg1;	// IMP=0x000000010010bb80
- (id)odiskMountPoints:(id)arg1;	// IMP=0x000000010010b9f4
- (void)handleBrowseCallBack:(unsigned int)arg1 interface:(unsigned int)arg2 error:(int)arg3 name:(const char *)arg4 type:(const char *)arg5 domain:(const char *)arg6;	// IMP=0x000000010010b840
- (_Bool)validAirDropInterface:(unsigned int)arg1;	// IMP=0x000000010010b7b8
- (void)notifyClientIfDone:(unsigned int)arg1;	// IMP=0x000000010010b768
- (void)notifyClient;	// IMP=0x000000010010b72c
- (void)personIconChanged:(id)arg1 iconData:(id)arg2;	// IMP=0x000000010010b48c
- (void)setIconData:(id)arg1 iconHash:(id)arg2 forPerson:(struct __SFNode *)arg3;	// IMP=0x000000010010b2ac
- (void)legacyModeChanged:(id)arg1;	// IMP=0x000000010010b214
- (void)linkStateChanged:(id)arg1;	// IMP=0x000000010010b17c
- (void)wirelessPowerChanged:(id)arg1;	// IMP=0x000000010010b16c
- (void)somethingChanged:(id)arg1;	// IMP=0x000000010010b15c
- (void)screenStatusChanged:(id)arg1;	// IMP=0x000000010010b150
- (void)consoleUserChanged:(id)arg1;	// IMP=0x000000010010b144
- (void)lockStatusChanged:(id)arg1;	// IMP=0x000000010010b138
- (void)airDropPublished:(id)arg1;	// IMP=0x000000010010b12c
- (void)contactsChanged:(id)arg1;	// IMP=0x000000010010af6c
- (void)cancelIdentityQueries;	// IMP=0x000000010010af5c
- (void)startIdentityQueryForNode:(struct __SFNode *)arg1;	// IMP=0x000000010010acc0
- (void)handleIdentity:(id)arg1 withQueryID:(id)arg2 emailOrPhone:(id)arg3 error:(id)arg4;	// IMP=0x000000010010aa94
- (void)personInfoChanged:(id)arg1 flags:(id)arg2 atag:(id)arg3 cname:(id)arg4 phash:(id)arg5 ehash:(id)arg6 nhash:(id)arg7;	// IMP=0x000000010010a53c
- (void)cancelAirDropRequests;	// IMP=0x000000010010a3fc
- (void)startAirDropRequestForNode:(struct __SFNode *)arg1;	// IMP=0x000000010010a2f8
- (void)airDropClient:(id)arg1 event:(long long)arg2 withResults:(id)arg3;	// IMP=0x0000000100109e8c
- (void)logAirDropDiscoveryInfoForNode:(struct __SFNode *)arg1;	// IMP=0x0000000100109354
- (void)cleanupAirDropRequest:(id)arg1;	// IMP=0x00000001001092d8
- (void)clearCacheAndNotify;	// IMP=0x0000000100109248
- (void)iconCacher:(id)arg1 didStoreDataWithError:(id)arg2;	// IMP=0x0000000100109118
- (void)iconCacher:(id)arg1 didFetchDataWithError:(id)arg2;	// IMP=0x0000000100108e7c
- (id)iconCacherKey:(id)arg1 pictureHash:(id)arg2;	// IMP=0x0000000100108dcc
- (void)startPictureQuery:(id)arg1;	// IMP=0x0000000100108cdc
- (void)commentChanged:(id)arg1 comment:(id)arg2;	// IMP=0x0000000100108c4c
- (void)deviceInfoChanged:(id)arg1 model:(id)arg2 ecolor:(id)arg3 osxvers:(id)arg4;	// IMP=0x0000000100108b34
- (id)redGreenBlueFromEcolor:(id)arg1;	// IMP=0x000000010010892c
- (void)systemInfoChanged:(id)arg1 diskInfo:(struct __CFDictionary *)arg2;	// IMP=0x0000000100108818
- (struct __SFNode *)copyNodeForService:(id)arg1;	// IMP=0x000000010010877c
- (struct __SFNode *)copyNodeForName:(id)arg1;	// IMP=0x00000001001086d4
- (void)ejectDisksIfNeeded:(id)arg1 diskNames:(id)arg2;	// IMP=0x00000001001086d0
- (void)removeService:(id)arg1 type:(id)arg2 domain:(id)arg3;	// IMP=0x00000001001083ec
- (void)cleanupRecordQueryForNetService:(id)arg1 recordType:(unsigned short)arg2;	// IMP=0x0000000100108320
- (void)cleanupRecordQuery:(id)arg1 type:(id)arg2 domain:(id)arg3 recordType:(unsigned short)arg4;	// IMP=0x0000000100108278
- (void)cleanupRecordQueryForKey:(id)arg1;	// IMP=0x0000000100108180
- (void)startRecordQuery:(id)arg1 type:(id)arg2 domain:(id)arg3 recordType:(unsigned short)arg4 interface:(unsigned int)arg5;	// IMP=0x0000000100107ec8
- (void)addQueryToDictionary:(struct _DNSServiceRef_t **)arg1 name:(id)arg2 type:(id)arg3 domain:(id)arg4 recordType:(unsigned short)arg5;	// IMP=0x0000000100107d48
- (id)queryKey:(id)arg1 type:(id)arg2 domain:(id)arg3 recordType:(unsigned short)arg4;	// IMP=0x0000000100107c80
- (void)addService:(id)arg1 type:(id)arg2 domain:(id)arg3 interface:(unsigned int)arg4;	// IMP=0x00000001001076b0
@property(readonly, copy) NSArray *nodes;
- (void)updateServerCacheIfNeeded;	// IMP=0x0000000100107440
- (void)updateSecondaryNameForNodes:(id)arg1;	// IMP=0x0000000100107328
- (void)removeInvalidNodes:(id)arg1;	// IMP=0x0000000100107128
- (void)invalidate;	// IMP=0x00000001001070d8
- (void)stop;	// IMP=0x0000000100106d24
- (void)logAirDropSessionInfo;	// IMP=0x0000000100106bdc
- (void)start;	// IMP=0x0000000100106afc
- (void)updateBrowserState;	// IMP=0x0000000100106540
- (_Bool)shouldStart;	// IMP=0x00000001001064d8
- (void)advertiseHashes;	// IMP=0x0000000100106330
- (void)stopConnectionlessAdvertising;	// IMP=0x00000001001062ec
- (void)startConnectionlessAdvertisingWithData:(id)arg1;	// IMP=0x00000001001061c4
- (void)awdl:(id)arg1 failedToStartAdvertisingWithError:(id)arg2;	// IMP=0x0000000100106164
- (void)awdlDidUpdateState:(id)arg1;	// IMP=0x0000000100106004
- (void)awdl:(id)arg1 foundDevice:(id)arg2 rssi:(id)arg3;	// IMP=0x0000000100105f80
- (_Bool)checkDiscoveryEntitlement;	// IMP=0x0000000100105f58
- (_Bool)preferVibrantIcons;	// IMP=0x0000000100105f50
- (_Bool)thisIsTheFinder;	// IMP=0x0000000100105eac
- (unsigned int)getInterface:(unsigned int)arg1;	// IMP=0x0000000100105de8
- (void)removeObservers;	// IMP=0x0000000100105d98
- (void)addObservers;	// IMP=0x0000000100105b50
- (void)clearCache;	// IMP=0x0000000100105b40
- (void)dealloc;	// IMP=0x0000000100105ae8
- (void)restartBrowser:(id)arg1;	// IMP=0x0000000100105aa4
@property long long mode;
- (id)initWithDomain:(id)arg1 types:(id)arg2;	// IMP=0x0000000100105720

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

