//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SDNetworkBrowserDelegate-Protocol.h"
#import "SDNetworkOperationDelegate-Protocol.h"

@class NSMutableDictionary, NSMutableSet, NSString, SDActivityAdvertiser, SDActivityEncryptionManager, SDActivityPayloadManager, SDActivityScanner, SDAirDropReceiveManager, SDAutoUnlockSessionManager, SDNearbyIDSAgent, SDPairedDeviceAgent, SDUnlockKeyManager, SDUnlockLockManager, SDXPCHelperConnection, SDXPCServer;
@protocol OS_xpc_object;

__attribute__((visibility("hidden")))
@interface SharingDaemon : NSObject <SDNetworkBrowserDelegate, SDNetworkOperationDelegate>
{
    NSMutableSet *_activeObjects;	// 8 = 0x8
    SDActivityAdvertiser *_activityAdvertiser;	// 16 = 0x10
    SDActivityScanner *_activityScanner;	// 24 = 0x18
    SDAirDropReceiveManager *_airdropManager;	// 32 = 0x20
    SDAutoUnlockSessionManager *_autoUnlockSessionManager;	// 40 = 0x28
    SDActivityEncryptionManager *_encryptionManager;	// 48 = 0x30
    SDNearbyIDSAgent *_nearbyIDSAgent;	// 56 = 0x38
    NSMutableDictionary *_exportedOperations;	// 64 = 0x40
    SDPairedDeviceAgent *_pairedDeviceAgent;	// 72 = 0x48
    NSObject<OS_xpc_object> *_listener;	// 80 = 0x50
    SDActivityPayloadManager *_payloadManager;	// 88 = 0x58
    SDUnlockKeyManager *_unlockKeyManager;	// 96 = 0x60
    SDUnlockLockManager *_unlockLockManager;	// 104 = 0x68
    unsigned long long _stateHandle;	// 112 = 0x70
    SDXPCServer *_xpcServer;	// 120 = 0x78
    SDXPCHelperConnection *_helperConnection;	// 128 = 0x80
}

+ (id)sharedDaemon;	// IMP=0x00000001001023ac
- (void).cxx_destruct;	// IMP=0x0000000100104e38
- (_Bool)canAccessAirDropSettings:(id)arg1;	// IMP=0x0000000100104e28
- (void)stop;	// IMP=0x0000000100104d40
- (void)start;	// IMP=0x0000000100104718
- (struct os_state_data_s *)stateCapture;	// IMP=0x000000010010460c
@property(readonly, copy) NSString *description;
- (void)handleNewConnection:(id)arg1;	// IMP=0x0000000100104084
- (void)handleOperationMessage:(id)arg1 forConnection:(id)arg2;	// IMP=0x0000000100103b10
- (void)handleBrowserMessage:(id)arg1 forConnection:(id)arg2;	// IMP=0x00000001001035dc
- (void)networkOperation:(id)arg1 event:(long long)arg2 withResults:(id)arg3;	// IMP=0x000000010010306c
- (void)networkBrowser:(id)arg1 nodesChangedForParent:(struct __SFNode *)arg2 protocol:(id)arg3 error:(int)arg4;	// IMP=0x0000000100102bc0
- (id)xpcArrayForSFNodeArray:(id)arg1;	// IMP=0x0000000100102a78
- (id)numberFromXPCObject:(id)arg1;	// IMP=0x00000001001029c0
- (id)arrayFromXPCObject:(id)arg1;	// IMP=0x0000000100102920
- (id)stringFromXPCObject:(id)arg1;	// IMP=0x0000000100102880
- (id)xpcObjectForSFOperationResults:(id)arg1;	// IMP=0x00000001001024e4
- (void)dealloc;	// IMP=0x0000000100102498
- (id)init;	// IMP=0x0000000100102418

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

