//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "TVAirPlayLegacySession-Protocol.h"

@class NSString, TVAirPlayPresentationView;
@protocol OS_dispatch_source, TVAirPlayLegacySessionDelegate;

@interface TVAirPlayPresentationSession : NSObject <TVAirPlayLegacySession>
{
    _Bool _deactivated;	// 8 = 0x8
    unsigned int _sessionID;	// 12 = 0xc
    NSObject<TVAirPlayLegacySessionDelegate> *_delegate;	// 16 = 0x10
    TVAirPlayPresentationView *_presentationView;	// 24 = 0x18
    NSObject<OS_dispatch_source> *_userActivityTimer;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x000000010001146c
@property(retain, nonatomic) NSObject<OS_dispatch_source> *userActivityTimer; // @synthesize userActivityTimer=_userActivityTimer;
@property(retain, nonatomic) TVAirPlayPresentationView *presentationView; // @synthesize presentationView=_presentationView;
@property(readonly, nonatomic) unsigned int sessionID; // @synthesize sessionID=_sessionID;
@property(nonatomic) __weak NSObject<TVAirPlayLegacySessionDelegate> *delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool deactivated; // @synthesize deactivated=_deactivated;
- (void)_cancelUserActivityTimer;	// IMP=0x00000001000113cc
- (void)_startUserActivityTimer;	// IMP=0x00000001000112f0
- (_Bool)performAction:(id)arg1 withOptions:(id)arg2 outInfo:(id *)arg3 error:(id *)arg4;	// IMP=0x0000000100011218
- (_Bool)setProperty:(id)arg1 qualifier:(id)arg2 value:(id)arg3 error:(id *)arg4;	// IMP=0x0000000100011210
- (id)getProperty:(id)arg1 qualifier:(id)arg2 error:(id *)arg3;	// IMP=0x0000000100011208
- (_Bool)stopWithOptions:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100011140
- (void)startWithOptions:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100010e68
- (void)userStop;	// IMP=0x0000000100010ce0
@property(readonly, nonatomic) long long sessionType;
@property(readonly, copy) NSString *description;
- (void)dealloc;	// IMP=0x0000000100010bec

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

