//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "APRKStreamRendererDelegate-Protocol.h"
#import "APRKStreamRenderingManagerDelegate-Protocol.h"
#import "TVAirPlayAPRKSessionDelegate-Protocol.h"
#import "TVAirPlayLegacyReceiverDelegateEventSink-Protocol.h"

@class APRKStreamRenderer, APRKStreamRenderingManager, NSString, TVAirPlayLegacyReceiverDelegate, TVAirPlaySessionManager;
@protocol OS_dispatch_queue;

@interface TVAirPlayAPRKManager : NSObject <TVAirPlayAPRKSessionDelegate, APRKStreamRenderingManagerDelegate, APRKStreamRendererDelegate, TVAirPlayLegacyReceiverDelegateEventSink>
{
    _Bool _started;	// 8 = 0x8
    _Bool _hasActiveRenderer;	// 9 = 0x9
    NSObject<OS_dispatch_queue> *_delegateSerialQueue;	// 16 = 0x10
    APRKStreamRenderingManager *_streamRenderingManager;	// 24 = 0x18
    TVAirPlaySessionManager *_sessionManager;	// 32 = 0x20
    TVAirPlayLegacyReceiverDelegate *_legacyReceiverDelegate;	// 40 = 0x28
    APRKStreamRenderer *_activeRenderer;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x000000010000ef40
@property(retain, nonatomic) APRKStreamRenderer *activeRenderer; // @synthesize activeRenderer=_activeRenderer;
@property(retain, nonatomic) TVAirPlayLegacyReceiverDelegate *legacyReceiverDelegate; // @synthesize legacyReceiverDelegate=_legacyReceiverDelegate;
@property(retain, nonatomic) TVAirPlaySessionManager *sessionManager; // @synthesize sessionManager=_sessionManager;
@property(retain, nonatomic) APRKStreamRenderingManager *streamRenderingManager; // @synthesize streamRenderingManager=_streamRenderingManager;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *delegateSerialQueue; // @synthesize delegateSerialQueue=_delegateSerialQueue;
@property(nonatomic) _Bool hasActiveRenderer; // @synthesize hasActiveRenderer=_hasActiveRenderer;
@property(nonatomic) _Bool started; // @synthesize started=_started;
- (void)_onMainQueue_deregisterSession:(id)arg1;	// IMP=0x000000010000ee48
- (void)_onMainQueue_registerSession:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;	// IMP=0x000000010000edac
- (void)_onMainQueue_deregisterGlobalPinSession;	// IMP=0x000000010000ec90
- (void)_onMainQueue_registerGlobalPinSession:(id)arg1 clientName:(id)arg2;	// IMP=0x000000010000e94c
- (void)_deregisterActiveVideoSessionIfRequired;	// IMP=0x000000010000e824
- (void)_registerActiveVideoSessionIfRequiredForRenderer:(id)arg1;	// IMP=0x000000010000e310
- (void)_stopAndClearActiveRenderer;	// IMP=0x000000010000e22c
- (void)_enqueueAsyncDelegateSerialQueueBlock:(CDUnknownBlockType)arg1;	// IMP=0x000000010000e0f4
- (void)_performSessionManagerWorkOnMainQueueWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x000000010000df64
- (void)sessionDidReceiveUserStop:(id)arg1;	// IMP=0x000000010000ddb8
- (void)didChangeStreamRendererModeTo:(unsigned long long)arg1 forRenderer:(id)arg2;	// IMP=0x000000010000dc44
- (void)shouldHideGlobalPasscode;	// IMP=0x000000010000db48
- (void)shouldShowGlobalPasscodeWithString:(id)arg1 withClientName:(id)arg2;	// IMP=0x000000010000d7e4
- (void)didStopStreamingWithRenderer:(id)arg1;	// IMP=0x000000010000d610
- (void)didStartStreamingWithRenderer:(id)arg1;	// IMP=0x000000010000d438
- (void)airPlayReceiverDelegate:(id)arg1 postEvent:(id)arg2 withInfo:(id)arg3;	// IMP=0x000000010000d2b4
- (void)stopReceiverServer;	// IMP=0x000000010000d168
- (void)startReceiverServer;	// IMP=0x000000010000cfcc
- (id)initWithSessionManager:(id)arg1 streamRenderingManager:(id)arg2 legacyReceiverDelegate:(id)arg3;	// IMP=0x000000010000ce8c
- (id)init;	// IMP=0x000000010000cddc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

