//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSString, TVSUIDigitEntryViewController, UIVisualEffectView;

@interface TVAirPlayPINViewController : UIViewController
{
    _Bool _dismissed;	// 8 = 0x8
    NSString *_clientName;	// 16 = 0x10
    NSString *_pinCode;	// 24 = 0x18
    CDUnknownBlockType _dismissHandler;	// 32 = 0x20
    UIVisualEffectView *_backgroundView;	// 40 = 0x28
    TVSUIDigitEntryViewController *_digitViewController;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x00000001000137c8
@property(retain, nonatomic) TVSUIDigitEntryViewController *digitViewController; // @synthesize digitViewController=_digitViewController;
@property(retain, nonatomic) UIVisualEffectView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(copy, nonatomic) CDUnknownBlockType dismissHandler; // @synthesize dismissHandler=_dismissHandler;
@property(copy, nonatomic) NSString *pinCode; // @synthesize pinCode=_pinCode;
@property(copy, nonatomic) NSString *clientName; // @synthesize clientName=_clientName;
- (void)_menuPressed;	// IMP=0x000000010001370c
- (void)setTitle:(id)arg1;	// IMP=0x0000000100013514
- (void)viewDidLoad;	// IMP=0x0000000100012f84

@end

