//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;
@protocol OS_xpc_object;

@interface NESMSessionClient : NSObject
{
    NSString *_description;	// 8 = 0x8
    NSObject<OS_xpc_object> *_connection;	// 16 = 0x10
    unsigned long long _permissions;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x000000010007dd48
@property(readonly) unsigned long long permissions; // @synthesize permissions=_permissions;
@property(readonly) NSObject<OS_xpc_object> *connection; // @synthesize connection=_connection;
- (void)cancel;	// IMP=0x000000010007dd04
- (void)sendStatusChangedNotification;	// IMP=0x000000010007dc5c
- (id)description;	// IMP=0x000000010007dc54
- (int)type;	// IMP=0x000000010007dc4c
- (id)initWithPID:(int)arg1;	// IMP=0x000000010007db50
- (id)initWithConnection:(id)arg1;	// IMP=0x000000010007d9a0

@end

