//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface NRDUpdateBrainLoader : NSObject
{
}

+ (_Bool)isBrainLoaded;	// IMP=0x0000000100009ce0
+ (id)brainAtPath:(id)arg1 delegate:(id)arg2 error:(id *)arg3;	// IMP=0x00000001000098f8

@end

