//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SAObjects/SAUIImageResource.h>

@interface SAUIImageResource (Siriland)
- (id)_convertedImageOfSize:(struct CGSize)arg1;	// IMP=0x0000000100083828
@end

