//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep  6 2019 11:16:02).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SAObjects/SAUIAppPunchOut.h>

@interface SAUIAppPunchOut (SRAdditions)
- (long long)sr_aceCommandType;	// IMP=0x0000000100083104
- (id)_convertedPunchout;	// IMP=0x0000000100083e6c
@end

