//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class UILabel;

@interface SRSpeechAlternativeTapToEditCellView : UIView
{
    UILabel *_tapToEditLabel;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0000000100072e08
- (void)layoutSubviews;	// IMP=0x0000000100072d00
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x0000000100072cf0
- (void)setTextHidden:(_Bool)arg1;	// IMP=0x0000000100072b64
- (id)init;	// IMP=0x0000000100072904

@end

