//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSNumber, SRStarkGatekeeperContactView;

@interface SRStarkMessagesContactContainerView : UIView
{
    SRStarkGatekeeperContactView *_contactView;	// 8 = 0x8
    NSNumber *_yOffset;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x000000010002d528
@property(nonatomic) NSNumber *yOffset; // @synthesize yOffset=_yOffset;
@property(readonly, nonatomic, getter=_contactView) SRStarkGatekeeperContactView *contactView; // @synthesize contactView=_contactView;
- (id)description;	// IMP=0x000000010002d42c
- (void)layoutSubviews;	// IMP=0x000000010002d0ac
- (void)centerText;	// IMP=0x000000010002d074
- (void)setTextOffset:(double)arg1;	// IMP=0x000000010002d010
- (void)showContactView:(id)arg1;	// IMP=0x000000010002cdd4
- (void)_configureWithAceObject:(id)arg1;	// IMP=0x000000010002cccc
- (void)updateWithAceObject:(id)arg1;	// IMP=0x000000010002ccc0
- (_Bool)isEquivalentTo:(id)arg1;	// IMP=0x000000010002cc24
- (id)initWithAceObject:(id)arg1;	// IMP=0x000000010002cba0
- (id)initWithRequestOptions:(id)arg1;	// IMP=0x000000010002c92c

@end

