//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "PBSViewServicePresenter-Protocol.h"
#import "TVDANavigationControllerDelegate-Protocol.h"

@class NSString, PBSDisplayAssistantPresentationRequest;

@interface TVDAViewController : UIViewController <PBSViewServicePresenter, TVDANavigationControllerDelegate>
{
    PBSDisplayAssistantPresentationRequest *_presentationRequest;	// 8 = 0x8
}

+ (id)_remoteViewControllerInterface;	// IMP=0x0000000100013784
+ (id)_exportedInterface;	// IMP=0x000000010001366c
+ (void)initialize;	// IMP=0x00000001000132f8
- (void).cxx_destruct;	// IMP=0x00000001000138c8
@property(retain, nonatomic) PBSDisplayAssistantPresentationRequest *presentationRequest; // @synthesize presentationRequest=_presentationRequest;
- (void)navigationControllerDidComplete:(id)arg1;	// IMP=0x00000001000137a0
- (void)viewServiceEndPresentationWithOptions:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000135dc
- (void)viewServiceBeginPresentationWithOptions:(id)arg1;	// IMP=0x0000000100013484
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x0000000100013358

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

