/*
* This header is generated by classdump-dyld 1.0
* on Sunday, June 7, 2020 at 11:25:42 AM Mountain Standard Time
* Operating System: Version 13.4.5 (Build 17L562)
* Image Source: /usr/lib/swift/libswiftCore.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface Swift.__VaListBuilder : _UKNOWN_SUPERCLASS_ {

	 requiredAlignmentInBytes;
	 count;
	 allocated;
	 storage;

}
@end

