//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "BackLightCC.h"

#import "tGraphDataSource-Protocol.h"

@interface BackLightCCSingle : BackLightCC <tGraphDataSource>
{
    unsigned int gPowerServiceBL;	// 296 = 0x128
    int _brightnessMilliNitsCurrent;	// 300 = 0x12c
    int _brightnessMilliNitsMaximum;	// 304 = 0x130
}

- (struct __CFString *)copyFieldCurrentValueForIndex:(int)arg1;	// IMP=0x000000010002e4b8
- (struct __CFString *)copyHeaderForIndex:(int)arg1;	// IMP=0x000000010002e408
- (int)numberOfFields;	// IMP=0x000000010002e3d0
- (void)refreshFunctionalTelemetry;	// IMP=0x000000010002e130
- (_Bool)findBacklightServices;	// IMP=0x000000010002e0b0
- (id)initWithParams:(struct __CFDictionary *)arg1;	// IMP=0x000000010002e024

@end

