//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "ComponentControl.h"

#import "tGraphDataSource-Protocol.h"

@interface RefreshRateCC : ComponentControl <tGraphDataSource>
{
    unsigned char refreshRateLevelElem;	// 120 = 0x78
    unsigned char refreshRateLevelPointer;	// 121 = 0x79
    unsigned char refreshRateLevelUp[4];	// 122 = 0x7a
    unsigned char refreshRateLevels[4];	// 126 = 0x7e
    unsigned char refreshRateLevelDown[4];	// 130 = 0x82
    unsigned char currentRefreshRateLevel;	// 134 = 0x86
    unsigned char previousRefreshRateLevel;	// 135 = 0x87
    unsigned char currentRefreshRateFPS;	// 136 = 0x88
}

- (struct __CFString *)copyFieldCurrentValueForIndex:(int)arg1;	// IMP=0x000000010000dd8c
- (struct __CFString *)copyHeaderForIndex:(int)arg1;	// IMP=0x000000010000dcf0
- (int)numberOfFields;	// IMP=0x000000010000dcbc
- (void)refreshTGraphTelemetry;	// IMP=0x000000010000dcb8
- (void)initRefreshRateTable:(struct __CFArray *)arg1;	// IMP=0x000000010000da74
- (void)defaultAction;	// IMP=0x000000010000d9c8
- (id)initWithParams:(struct __CFDictionary *)arg1;	// IMP=0x000000010000d8b8

@end

