//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface TableDrivenDecisionTree : NSObject
{
    NSArray *_componentControllers;	// 8 = 0x8
    NSArray *_hotspotControllers;	// 16 = 0x10
    unsigned char maxLoadIndexForComponent[13];	// 24 = 0x18
    unsigned char releaseMaxLoadIndexForComponent[13];	// 37 = 0x25
    unsigned int releaseRateForComponent[13];	// 52 = 0x34
}

- (void)initDecisionTable:(struct __CFDictionary *)arg1;	// IMP=0x0000000100013dec
- (id)findCC:(int)arg1;	// IMP=0x0000000100013cc8
- (void)evaluateDecisionTree;	// IMP=0x0000000100013b98
- (void)readReleaseRateForAllComponents;	// IMP=0x0000000100013ad4
- (int)getReleaseRateForComponent:(int)arg1;	// IMP=0x0000000100013a90
- (void)actionComponentControl;	// IMP=0x00000001000137dc
- (int)getMTypeFromComponent:(int)arg1;	// IMP=0x00000001000137bc
- (id)initWithComponentControllers:(id)arg1 hotspotControllers:(id)arg2 decisionTreeTable:(id)arg3;	// IMP=0x0000000100013738

@end

