//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CommonProduct.h"

@interface tm615510ed960594846913e03b9a1422aa : CommonProduct
{
}

- (void)updateAllThermalLoad:(_Bool)arg1;	// IMP=0x0000000100032764

@end

