//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;
@protocol OS_dispatch_queue, OS_xpc_object;

@interface NEHelperServer : NSObject
{
    int _firstUnlockToken;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_queue;	// 16 = 0x10
    NSObject<OS_xpc_object> *_listener;	// 24 = 0x18
    NSMutableArray *_clients;	// 32 = 0x20
}

+ (Class)classFromID:(int)arg1;	// IMP=0x000000010000b32c
+ (_Bool)verifyConnection:(id)arg1 hasEntitlement:(const char *)arg2;	// IMP=0x000000010000a03c
+ (void)sendReplyForMessage:(id)arg1 result:(long long)arg2 data:(id)arg3;	// IMP=0x0000000100009f88
+ (id)sharedServer;	// IMP=0x0000000100009350
- (void).cxx_destruct;	// IMP=0x000000010000bcec
@property int firstUnlockToken; // @synthesize firstUnlockToken=_firstUnlockToken;
@property(readonly) NSMutableArray *clients; // @synthesize clients=_clients;
@property(readonly) NSObject<OS_xpc_object> *listener; // @synthesize listener=_listener;
@property(readonly) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void)handleInitCommand;	// IMP=0x000000010000bba4
- (void)handleAppsChanged:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x000000010000b3d8
- (id)copyClientsWithName:(id)arg1 delegateClassID:(int)arg2;	// IMP=0x000000010000b0fc
- (void)handleEvent:(id)arg1 ofType:(const char *)arg2;	// IMP=0x000000010000a5b0
- (void)handleControlSettingsFileChanged;	// IMP=0x000000010000a278
- (void)handleManagedPreferencesChangedForInitCheck:(_Bool)arg1;	// IMP=0x000000010000a158
- (void)acceptNewConnection:(id)arg1;	// IMP=0x0000000100009698
- (void)stop;	// IMP=0x0000000100009660
- (void)start;	// IMP=0x00000001000093cc
- (id)initPrivate;	// IMP=0x00000001000091ac
- (id)init;	// IMP=0x00000001000091a0

@end

