//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "GKDaemonProxyDataUpdateDelegate-Protocol.h"
#import "UIApplicationDelegate-Protocol.h"

@class NSString, UIWindow;

@interface AppDelegateService : NSObject <GKDaemonProxyDataUpdateDelegate, UIApplicationDelegate>
{
}

- (void)setLocalPlayer:(id)arg1;	// IMP=0x0000000100002960
- (void)refreshContentsForDataType:(unsigned int)arg1 userInfo:(id)arg2;	// IMP=0x0000000100002928
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;	// IMP=0x0000000100002920
- (id)init;	// IMP=0x00000001000028ac

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) UIWindow *window;

@end

