//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MCNewCertificatePayloadHandler.h"

@interface MCNewSCEPPayloadHandler : MCNewCertificatePayloadHandler
{
    struct __SecIdentity *_identity;	// 40 = 0x28
}

+ (void)allowInsecureHTTPLoadsOfURL:(id)arg1 forConfiguration:(id)arg2;	// IMP=0x000000010005d268
+ (id)atsOverrideDataWithInsecureHTTPForHost:(id)arg1 fromATSOverrideData:(id)arg2;	// IMP=0x000000010005d00c
+ (id)mutableATSExceptionInExceptionDomains:(id)arg1 matchingHost:(id)arg2;	// IMP=0x000000010005ce50
- (struct __SecIdentity *)copyIdentityImmediatelyWithInteractionClient:(id)arg1 outError:(id *)arg2;	// IMP=0x000000010005e148
- (_Bool)installWithInstaller:(id)arg1 options:(id)arg2 interactionClient:(id)arg3 outError:(id *)arg4;	// IMP=0x000000010005ddc4
- (id)_performPKIOperation:(id)arg1 withPayload:(id)arg2 usingPost:(_Bool)arg3 error:(id *)arg4;	// IMP=0x000000010005dbe8
- (_Bool)_createKeyPairLength:(unsigned long long)arg1 outPublicKey:(struct __SecKey **)arg2 outPrivateKey:(struct __SecKey **)arg3;	// IMP=0x000000010005dae4
- (id)_invalidRAResponse;	// IMP=0x000000010005da4c
- (id)_synchronousTransactionWithURL:(id)arg1 method:(id)arg2 content:(id)arg3 contentType:(id)arg4 outResponseCode:(long long *)arg5 outContentType:(id *)arg6 outError:(id *)arg7;	// IMP=0x000000010005d374
- (id)_SCEPOperationURLWithBaseURLString:(id)arg1 operation:(id)arg2 message:(id)arg3;	// IMP=0x000000010005cc8c
- (id)userInputFields;	// IMP=0x000000010005cacc
- (void)dealloc;	// IMP=0x000000010005ca78

@end

