//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MCNewPayloadHandler.h"

@interface MCNewGlobalHTTPProxyPayloadHandler : MCNewPayloadHandler
{
}

- (_Bool)_sendSystemConfigurationProxyChangeNotification;	// IMP=0x000000010006e770
- (void)remove;	// IMP=0x000000010006e624
- (void)unsetAside;	// IMP=0x000000010006e5f0
- (void)setAside;	// IMP=0x000000010006e5bc
- (void)_recoverProxyCredential;	// IMP=0x000000010006e3d4
- (void)_removeProxyCredential;	// IMP=0x000000010006dfcc
- (_Bool)installWithInstaller:(id)arg1 options:(id)arg2 interactionClient:(id)arg3 outError:(id *)arg4;	// IMP=0x000000010006dc28
- (void)_applyProxyCredential:(id)arg1;	// IMP=0x000000010006d9b4
- (_Bool)_remove;	// IMP=0x000000010006d900
- (_Bool)_install;	// IMP=0x000000010006d2c8
- (_Bool)preflightUserInputResponses:(id)arg1 outError:(id *)arg2;	// IMP=0x000000010006d05c
- (id)userInputFields;	// IMP=0x000000010006cecc

@end

