//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionView.h>

@class MISSING_TYPE;

@interface _TtC8AppStore26ProductMediaCollectionView : UICollectionView
{
    MISSING_TYPE *activeDataSource;	// 8 = 0x8
    MISSING_TYPE *flowLayout;	// 16 = 0x10
    MISSING_TYPE *artworkSelectionHandler;	// 24 = 0x18
    MISSING_TYPE *scrollViewDelegateCoordinator;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x00000001001abd04
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x00000001001ab02c
@property(nonatomic, readonly) _Bool canBecomeFocused;
- (void)didMoveToWindow;	// IMP=0x00000001001aae18
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001001aad48
- (id)initWithFrame:(struct CGRect)arg1 collectionViewLayout:(id)arg2;	// IMP=0x00000001001aad1c
- (id)init;	// IMP=0x00000001001aacfc
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001001aac48

@end

