//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionReusableView.h>

@class MISSING_TYPE, NSArray, NSString, UIView, _TtC8AppStore16DynamicTypeLabel;

@interface _TtC8AppStore15TitleHeaderView : UICollectionReusableView
{
    MISSING_TYPE *titleLabel;	// 8 = 0x8
    MISSING_TYPE *detailLabel;	// 16 = 0x10
    MISSING_TYPE *style;	// 24 = 0x18
    MISSING_TYPE *accessoryView;	// 208 = 0xd0
    MISSING_TYPE *accessory;	// 216 = 0xd8
    MISSING_TYPE *accessoryAction;	// 248 = 0xf8
    MISSING_TYPE *separatorLineView;	// 264 = 0x108
    MISSING_TYPE *separatorInset;	// 272 = 0x110
    MISSING_TYPE *avoidanceRegion;	// 304 = 0x130
}

- (void).cxx_destruct;	// IMP=0x000000010013b3a4
@property(nonatomic, readonly) NSArray *preferredFocusEnvironments;
@property(nonatomic, readonly) _Bool canBecomeFocused;
@property(nonatomic, readonly) UIView *accessibilityAccessoryView;
@property(nonatomic, readonly) _TtC8AppStore16DynamicTypeLabel *accessibilityTitleLabel;
@property(nonatomic, copy) NSString *accessibilityLabel;
- (void)prepareForReuse;	// IMP=0x000000010013ad10
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x000000010013ac28
- (void)layoutSubviews;	// IMP=0x000000010013abfc
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x000000010013a1fc
- (void)didTapWithAccessoryView:(id)arg1;	// IMP=0x0000000100139f40
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100139ea4
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100139e84

@end

