//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE;

@interface _TtC8AppStoreP33_597C521DDB3F529AE9C0FC042D86CE8911ContentView : UIView
{
    MISSING_TYPE *insetLayoutMarginsFromSafeArea;	// 8 = 0x8
}

- (unsigned long long)_edgesPropagatingSafeAreaInsetsToDescendants;	// IMP=0x000000010006d120
@property(nonatomic) unsigned long long edgesInsettingLayoutMarginsFromSafeArea;
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010006c7d0
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010006c734

@end

