//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@interface UIView (AppStore)
@property(nonatomic, readonly) double lastBaselineMaxY;
@property(nonatomic, readonly) double lastBaselineFromBottom;
@property(nonatomic, readonly) double firstBaselineFromTop;
@end

