//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSURLStorageTask.h"

@class NSString;

@interface NSURLStorageTaskSchemaCheck : NSURLStorageTask
{
    NSString *_dbPath;	// 16 = 0x10
    long long _dbSize;	// 24 = 0x18
    CDStruct_4c969caf _token;	// 32 = 0x20
    long long _sandboxExtensionHandle;	// 64 = 0x40
}

- (void).cxx_destruct;	// IMP=0x0000000100008110
- (void)run;	// IMP=0x0000000100008014
- (void)dealloc;	// IMP=0x0000000100007f90
- (id)initWithPath:(id)arg1 size:(long long)arg2 auditToken:(CDStruct_4c969caf)arg3 sandboxExtension:(id)arg4;	// IMP=0x0000000100007dfc
- (id)initWithTaskManager:(id)arg1 path:(id)arg2 size:(long long)arg3;	// IMP=0x0000000100007d40

@end

