//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MCMContainer, NSURL;

@interface MIContainer : NSObject
{
    MCMContainer *_container;	// 8 = 0x8
    NSURL *_containerURL;	// 16 = 0x10
    unsigned long long _status;	// 24 = 0x18
}

+ (id)allContainersForIdentifier:(id)arg1 options:(unsigned long long)arg2 error:(id *)arg3;	// IMP=0x000000010001f598
+ (id)_groupContainerIdentifiersForBundleId:(id)arg1;	// IMP=0x000000010001f3fc
+ (id)_bundleContainerForIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x000000010001f27c
+ (id)containersWithClass:(long long)arg1 error:(id *)arg2;	// IMP=0x000000010001e00c
+ (id)containerWithIdentifier:(id)arg1 ofContentClass:(long long)arg2 createIfNeeded:(_Bool)arg3 created:(_Bool *)arg4 error:(id *)arg5;	// IMP=0x000000010001dce0
+ (id)tempContainerWithIdentifier:(id)arg1 ofContentClass:(long long)arg2 error:(id *)arg3;	// IMP=0x000000010001d9a4
- (void).cxx_destruct;	// IMP=0x0000000100020498
@property(readonly, nonatomic) unsigned long long status; // @synthesize status=_status;
@property(readonly, nonatomic) NSURL *containerURL; // @synthesize containerURL=_containerURL;
@property(readonly, nonatomic) MCMContainer *container; // @synthesize container=_container;
- (id)description;	// IMP=0x000000010002043c
- (_Bool)captureStoreDataFromDirectory:(id)arg1 doCopy:(_Bool)arg2 failureIsFatal:(_Bool)arg3 withError:(id *)arg4;	// IMP=0x0000000100020318
@property(readonly, nonatomic) unsigned long long diskUsage;
- (_Bool)purgeContentWithError:(id *)arg1;	// IMP=0x000000010001ef18
- (_Bool)regenerateDirectoryUUIDWithError:(id *)arg1;	// IMP=0x000000010001ed5c
- (_Bool)makeContainerLiveReplacingContainer:(id)arg1 reason:(unsigned long long)arg2 waitForDeletion:(_Bool)arg3 withError:(id *)arg4;	// IMP=0x000000010001e2c4
- (_Bool)makeContainerLiveWithError:(id *)arg1;	// IMP=0x000000010001e2a8
@property(readonly, nonatomic) long long contentClass;
- (id)initWithContainer:(id)arg1;	// IMP=0x000000010001d7e0

@end

