//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NDApplicationObserver-Protocol.h"

@class NDApplication, NSMutableArray, NSString, NSURLSessionTask, __NSCFURLSessionTaskInfo;
@protocol OS_dispatch_queue, OS_dispatch_source;

@interface NDTaskMonitor : NSObject <NDApplicationObserver>
{
    NSURLSessionTask *_task;	// 8 = 0x8
    __NSCFURLSessionTaskInfo *_taskInfo;	// 16 = 0x10
    NSString *_clientBundleIdentifier;	// 24 = 0x18
    NSString *_clientSecondaryIdentifier;	// 32 = 0x20
    NSObject<OS_dispatch_queue> *_queue;	// 40 = 0x28
    NSObject<OS_dispatch_source> *_throughputTimer;	// 48 = 0x30
    NSMutableArray *_progressTimestamps;	// 56 = 0x38
    NSMutableArray *_progressValues;	// 64 = 0x40
    unsigned long long _throughputInterval;	// 72 = 0x48
    NDApplication *_monitoredApplication;	// 80 = 0x50
    double _throughputMonitoringStartTime;	// 88 = 0x58
    _Bool _startedDuetReporter;	// 96 = 0x60
    _Bool _connectionIsCellular;	// 97 = 0x61
    _Bool _hasTransferredData;	// 98 = 0x62
    _Bool _discretionary;	// 99 = 0x63
    _Bool _explicitlyDiscretionary;	// 100 = 0x64
    _Bool _performsNonDiscretionaryThrougputMonitoring;	// 101 = 0x65
    _Bool _mayBeDemotedToDiscretionary;	// 102 = 0x66
    int _powerMonitorToken;	// 104 = 0x68
    long long _basePriority;	// 112 = 0x70
}

- (void).cxx_destruct;	// IMP=0x000000010003e284
@property long long basePriority; // @synthesize basePriority=_basePriority;
- (void)applicationEndedTransitionalDiscretionaryBackgroundPeriod:(id)arg1;	// IMP=0x000000010003e21c
- (void)applicationNoLongerInForeground:(id)arg1;	// IMP=0x000000010003e1c4
- (void)applicationEnteredForeground:(id)arg1;	// IMP=0x000000010003e16c
- (void)backgroundUpdatesDisabledForApplication:(id)arg1;	// IMP=0x000000010003e0e8
- (void)applicationWasQuitFromAppSwitcher:(id)arg1;	// IMP=0x000000010003e064
- (void)cancel;	// IMP=0x000000010003e010
- (void)taskWillSuspend;	// IMP=0x000000010003e004
- (void)startThroughputMonitoringIfAppropriate;	// IMP=0x000000010003df9c
- (void)taskWillResume;	// IMP=0x000000010003def8
- (void)stopThroughputMonitoring;	// IMP=0x000000010003dea8
- (void)startThroughputMonitoring;	// IMP=0x000000010003ddd8
- (void)taskTransferredData:(unsigned long long)arg1 countOfBytesReceived:(unsigned long long)arg2;	// IMP=0x000000010003db38
- (void)setThroughputTimerForCurrentInterval;	// IMP=0x000000010003da98
- (void)calculateThroughput;	// IMP=0x000000010003d76c
- (long long)currentIntervalEndDelta;	// IMP=0x000000010003d72c
- (double)currentThroughputThreshold;	// IMP=0x000000010003d70c
- (id)initWithTask:(id)arg1 taskInfo:(id)arg2 clientBundleIdentifier:(id)arg3 secondaryIdentifier:(id)arg4 monitoredApplication:(id)arg5 priority:(long long)arg6 options:(unsigned long long)arg7 queue:(id)arg8;	// IMP=0x000000010003d514

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

