//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSMutableDictionary;
@protocol OS_dispatch_queue, OS_xpc_object;

@interface NDUserEventAgentConnection : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    NSObject<OS_xpc_object> *_connection;	// 16 = 0x10
    NSObject<OS_xpc_object> *_listener;	// 24 = 0x18
    NSDictionary *_registeredClients;	// 32 = 0x20
    NSMutableDictionary *_pendingWakes;	// 40 = 0x28
}

+ (id)sharedUserEventAgentConnection;	// IMP=0x0000000100030320
- (void).cxx_destruct;	// IMP=0x000000010002fa30
- (void)removePendingWakeForClient:(id)arg1 sessionIdentifier:(id)arg2;	// IMP=0x000000010002f96c
- (void)wakeClientUponNotification:(id)arg1 sessionIdentifier:(id)arg2;	// IMP=0x000000010002f8a8
- (void)launchProcessWithIdentifier:(id)arg1 sessionIdentifier:(id)arg2;	// IMP=0x000000010002f7e4
- (_Bool)canLaunchProcessWithIdentifier:(id)arg1;	// IMP=0x000000010002f7a4
- (void)handleNewConnection:(id)arg1;	// IMP=0x000000010002f67c
- (void)start;	// IMP=0x000000010002f558
- (id)init;	// IMP=0x000000010002f488

@end

