//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@class NSData;

@interface PDURLSessionProxyAuthChallenge : PBCodable <NSCopying>
{
    NSData *_archiveList;	// 8 = 0x8
    unsigned int _version;	// 16 = 0x10
    CDStruct_f20694ce _has;	// 20 = 0x14
}

- (void).cxx_destruct;	// IMP=0x000000010004a29c
@property(retain, nonatomic) NSData *archiveList; // @synthesize archiveList=_archiveList;
@property(nonatomic) unsigned int version; // @synthesize version=_version;
- (void)mergeFrom:(id)arg1;	// IMP=0x000000010004a1f0
- (unsigned long long)hash;	// IMP=0x000000010004a18c
- (_Bool)isEqual:(id)arg1;	// IMP=0x000000010004a0b4
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x000000010004a00c
- (void)copyTo:(id)arg1;	// IMP=0x0000000100049f94
- (void)writeTo:(id)arg1;	// IMP=0x0000000100049f24
- (_Bool)readFrom:(id)arg1;	// IMP=0x0000000100049f1c
- (id)dictionaryRepresentation;	// IMP=0x0000000100049e50
- (id)description;	// IMP=0x0000000100049d9c
@property(readonly, nonatomic) _Bool hasArchiveList;
@property(nonatomic) _Bool hasVersion;

@end

