//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@class NSData, PDURLSessionProxyTaskMessage;

@interface PDURLSessionProxyGetAuthHeadersReply : PBCodable <NSCopying>
{
    NSData *_headerData;	// 8 = 0x8
    PDURLSessionProxyTaskMessage *_task;	// 16 = 0x10
    _Bool _continueLoad;	// 24 = 0x18
    struct {
        unsigned int continueLoad:1;
    } _has;	// 28 = 0x1c
}

- (void).cxx_destruct;	// IMP=0x000000010002cb00
@property(nonatomic) _Bool continueLoad; // @synthesize continueLoad=_continueLoad;
@property(retain, nonatomic) NSData *headerData; // @synthesize headerData=_headerData;
@property(retain, nonatomic) PDURLSessionProxyTaskMessage *task; // @synthesize task=_task;
- (void)mergeFrom:(id)arg1;	// IMP=0x000000010002c9f8
- (unsigned long long)hash;	// IMP=0x000000010002c968
- (_Bool)isEqual:(id)arg1;	// IMP=0x000000010002c858
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x000000010002c77c
- (void)copyTo:(id)arg1;	// IMP=0x000000010002c6e4
- (void)writeTo:(id)arg1;	// IMP=0x000000010002c658
- (_Bool)readFrom:(id)arg1;	// IMP=0x000000010002c37c
- (id)dictionaryRepresentation;	// IMP=0x000000010002c268
- (id)description;	// IMP=0x000000010002c1b4
@property(nonatomic) _Bool hasContinueLoad;
@property(readonly, nonatomic) _Bool hasHeaderData;
@property(readonly, nonatomic) _Bool hasTask;

@end

