//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@class PDURLSessionProxyTaskMessage;

@interface PDURLSessionProxySetTaskPriority : PBCodable <NSCopying>
{
    unsigned int _priority;	// 8 = 0x8
    PDURLSessionProxyTaskMessage *_task;	// 16 = 0x10
    struct {
        unsigned int priority:1;
    } _has;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x000000010000ac80
@property(nonatomic) unsigned int priority; // @synthesize priority=_priority;
@property(retain, nonatomic) PDURLSessionProxyTaskMessage *task; // @synthesize task=_task;
- (void)mergeFrom:(id)arg1;	// IMP=0x000000010000abbc
- (unsigned long long)hash;	// IMP=0x000000010000ab54
- (_Bool)isEqual:(id)arg1;	// IMP=0x000000010000aa78
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x000000010000a9d0
- (void)copyTo:(id)arg1;	// IMP=0x000000010000a958
- (void)writeTo:(id)arg1;	// IMP=0x000000010000a8e8
- (_Bool)readFrom:(id)arg1;	// IMP=0x000000010000a648
- (id)dictionaryRepresentation;	// IMP=0x000000010000a558
- (id)description;	// IMP=0x000000010000a4a4
@property(nonatomic) _Bool hasPriority;
@property(readonly, nonatomic) _Bool hasTask;

@end

