//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@class PDURLSessionProxyTaskMessage;

@interface PDURLSessionProxySuspendTask : PBCodable <NSCopying>
{
    PDURLSessionProxyTaskMessage *_task;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0000000100038670
@property(retain, nonatomic) PDURLSessionProxyTaskMessage *task; // @synthesize task=_task;
- (void)mergeFrom:(id)arg1;	// IMP=0x00000001000385e8
- (unsigned long long)hash;	// IMP=0x00000001000385d0
- (_Bool)isEqual:(id)arg1;	// IMP=0x0000000100038530
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001000384b4
- (void)copyTo:(id)arg1;	// IMP=0x000000010003848c
- (void)writeTo:(id)arg1;	// IMP=0x000000010003846c
- (_Bool)readFrom:(id)arg1;	// IMP=0x0000000100038284
- (id)dictionaryRepresentation;	// IMP=0x00000001000381f8
- (id)description;	// IMP=0x0000000100038144
@property(readonly, nonatomic) _Bool hasTask;

@end

