//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@class PDURLSessionProxyTaskMessage;

@interface PDURLSessionProxyOpenBodyStream : PBCodable <NSCopying>
{
    PDURLSessionProxyTaskMessage *_task;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010003ba28
@property(retain, nonatomic) PDURLSessionProxyTaskMessage *task; // @synthesize task=_task;
- (void)mergeFrom:(id)arg1;	// IMP=0x000000010003b9a0
- (unsigned long long)hash;	// IMP=0x000000010003b988
- (_Bool)isEqual:(id)arg1;	// IMP=0x000000010003b8e8
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x000000010003b86c
- (void)copyTo:(id)arg1;	// IMP=0x000000010003b844
- (void)writeTo:(id)arg1;	// IMP=0x000000010003b824
- (_Bool)readFrom:(id)arg1;	// IMP=0x000000010003b63c
- (id)dictionaryRepresentation;	// IMP=0x000000010003b5b0
- (id)description;	// IMP=0x000000010003b4fc
@property(readonly, nonatomic) _Bool hasTask;

@end

