/*
* This header is generated by classdump-dyld 1.0
* on Sunday, June 7, 2020 at 11:42:03 AM Mountain Standard Time
* Operating System: Version 13.4.5 (Build 17L562)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/RTPredictedLocationOfInterestProvider.h>

@class RTVehicleLocationProvider, RTDistanceCalculator, NSString;

@interface RTPredictedLocationOfInterestProviderVehicleLocation : NSObject <RTPredictedLocationOfInterestProvider> {

	RTVehicleLocationProvider* _vehicleLocationProvider;
	RTDistanceCalculator* _distanceCalculator;

}

@property (nonatomic,readonly) RTVehicleLocationProvider * vehicleLocationProvider;              //@synthesize vehicleLocationProvider=_vehicleLocationProvider - In the implementation block
@property (nonatomic,readonly) RTDistanceCalculator * distanceCalculator;                        //@synthesize distanceCalculator=_distanceCalculator - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)init;
-(RTVehicleLocationProvider *)vehicleLocationProvider;
-(RTDistanceCalculator *)distanceCalculator;
-(id)initWithVehicleLocationProvider:(id)arg1 distanceCalculator:(id)arg2 ;
-(void)fetchNextPredictedLocationsOfInterestWithCriteria:(id)arg1 handler:(/*^block*/id)arg2 ;
-(void)fetchPredictedExitDatesWithCriteria:(id)arg1 handler:(/*^block*/id)arg2 ;
-(void)fetchPredictedLocationsOfInterestWithCriteria:(id)arg1 handler:(/*^block*/id)arg2 ;
-(id)locationOfInterestFromVehicleEvent:(id)arg1 ;
-(BOOL)parkingEventIsUsualAndNearHome:(id)arg1 ;
-(id)predictedLocationOfInterestFromVehicleEvent:(id)arg1 ;
@end

