//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPBeaconManagerUserAgentDaemonInternalXPCProtocol-Protocol.h"
#import "SPLocalBeaconManagerXPCProtocol-Protocol.h"
#import "SPLocalPairingManagerXPCProtocol-Protocol.h"

@class MISSING_TYPE;

@interface _TtC12searchpartyd34LightweightBeaconManagerTrampoline : NSObject <SPLocalBeaconManagerXPCProtocol, SPLocalPairingManagerXPCProtocol, SPBeaconManagerUserAgentDaemonInternalXPCProtocol>
{
    MISSING_TYPE *implementation;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00000001000e9de0
- (id)init;	// IMP=0x00000001000e9df0
- (void)pushSubmissionConfigurationHostName:(id)arg1 path:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00000001000e9cd0
- (void)containerWithName:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000e9c30
- (void)purgeLocalBeaconRecordWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001000e9bd8
- (void)pushLocalBeaconRecord:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000e9b34
- (void)alwaysBeaconStateWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001000e9a44
- (void)setAlwaysBeaconState:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000e99b8
- (void)getLocalPairingDataWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001000e97e8
- (void)getMacBeaconConfigWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001000e9788
- (void)beaconingKeysWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001000e96fc
- (void)beaconingStateWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001000e966c

@end

