//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep  6 2019 11:16:02).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CloudKit/CKRecord.h>

@interface CKRecord (HeadBoard)
- (id)hb_UInt32ForKey:(id)arg1;	// IMP=0x000000010006e800
- (void)hb_setUInt32:(id)arg1 forKey:(id)arg2;	// IMP=0x000000010006e7b0
- (id)hb_UInt64ForKey:(id)arg1;	// IMP=0x000000010006e738
- (void)hb_setUInt64:(id)arg1 forKey:(id)arg2;	// IMP=0x000000010006e6ac
@end

