//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class HBAppGridViewController, HBRootItem, UIFocusAnimationCoordinator;

@protocol HBAppGridViewControllerDelegate <NSObject>

@optional
- (void)gridViewControllerEditingStateChanged:(HBAppGridViewController *)arg1;
- (void)gridViewControllerItemsBecameReady:(HBAppGridViewController *)arg1;
- (void)gridViewControllerDidScrollCloseEnoughToTop:(HBAppGridViewController *)arg1;
- (void)gridViewControllerDidEndDecelerating:(HBAppGridViewController *)arg1;
- (void)gridViewController:(HBAppGridViewController *)arg1 itemMovedOutOfDock:(HBRootItem *)arg2 replacedWithItem:(HBRootItem *)arg3;
- (void)gridViewController:(HBAppGridViewController *)arg1 itemMovedIntoDock:(HBRootItem *)arg2;
- (void)appGridViewController:(HBAppGridViewController *)arg1 didUpdateFocusInContext:(CDStruct_334d6f95)arg2 withAnimationCoordinator:(UIFocusAnimationCoordinator *)arg3;
@end

