//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface HBCloudSyncDeviceToCloudSyncUtility : NSObject
{
}

+ (id)_appIdsFromRootFolder:(id)arg1;	// IMP=0x000000010006e528
+ (_Bool)parentFolderForApp:(id)arg1 containsOnlyNonRestorableApps:(id)arg2;	// IMP=0x000000010006e294
+ (_Bool)hasAllParametersForInstallation:(id)arg1;	// IMP=0x000000010006e098
+ (_Bool)isFolderSyncable:(id)arg1;	// IMP=0x000000010006de34
+ (_Bool)isAppSyncable:(id)arg1;	// IMP=0x000000010006da54
+ (id)validateFolderStructureAndDiscardUnwantedItems:(id)arg1;	// IMP=0x000000010006d4b8
+ (id)appsWithChangedAlternateAppIconsFromAllApps:(id)arg1 appIdsToSyncedIconNames:(id)arg2;	// IMP=0x000000010006d0e8
+ (id)updateItemOrderIdsForMovedItemsInFolder:(id)arg1 baseOrderId:(double)arg2;	// IMP=0x000000010006cbb0
+ (id)updateItemOrderIdsForMovedItemsInFolder:(id)arg1;	// IMP=0x000000010006cb9c
+ (id)indicesForUnarrangedItemsInFolder:(id)arg1 subfolder:(CDUnknownBlockType)arg2;	// IMP=0x000000010006c724
+ (id)allItemsWithUpdatedOrderIdsFromFolder:(id)arg1 baseOrderId:(unsigned long long)arg2;	// IMP=0x000000010006c488
+ (_Bool)needToResetOrderingForItemsInFolder:(id)arg1;	// IMP=0x000000010006c0c0
+ (_Bool)doItemOrderIdsCollideInFolder:(id)arg1;	// IMP=0x000000010006bef4
+ (id)deletedItemsListFromFolder:(id)arg1 itemsToParentMapping:(id)arg2;	// IMP=0x000000010006bce4
+ (id)addedOrModifiedItemsFromRootFolderItems:(id)arg1 currentParentFolderLevel:(long long)arg2 itemsToParentMapping:(id)arg3;	// IMP=0x000000010006b600
+ (id)foldersWithChangedDisplayNamesFromFolder:(id)arg1 folderIdentifiersMappedToDisplayNames:(id)arg2;	// IMP=0x000000010006b3a0
+ (id)folderIdentifiersMappedToDisplayNamesFromSyncedRecords:(id)arg1 existingMapping:(id)arg2;	// IMP=0x000000010006b0a0
+ (id)folderIdentifiersMappedToDisplayNames:(id)arg1;	// IMP=0x000000010006aea4
+ (id)itemsToParentMappingFromItems:(id)arg1 currentFolderLevelIndex:(long long)arg2;	// IMP=0x000000010006aadc
+ (id)itemsToParentMappingFromAddedRecords:(id)arg1 deletedRecordIDs:(id)arg2 existingItemsToParentMapping:(id)arg3 rootFolder:(id)arg4;	// IMP=0x000000010006a634
+ (void)initialize;	// IMP=0x000000010006a5d0

@end

