//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface HBCollectionChangeSetComparator : NSObject
{
}

+ (id)_movedIdentifiersWithSourceIdentifiers:(id)arg1 destinationIdentifiers:(id)arg2;	// IMP=0x000000010007b484
+ (id)_indexByIdentifierDictionaryWithIdentifiers:(id)arg1;	// IMP=0x000000010007b310
+ (id)_identifiersWithObjects:(id)arg1 identifierBlock:(CDUnknownBlockType)arg2;	// IMP=0x000000010007b0bc
+ (id)_changeSetWithSourceObjects:(id)arg1 destinationObjects:(id)arg2 identifierBlock:(CDUnknownBlockType)arg3 isEqualBlock:(CDUnknownBlockType)arg4 updateChangeSetBlock:(CDUnknownBlockType)arg5;	// IMP=0x000000010007a5a0
+ (id)changeSetFromObjects:(id)arg1 toObjects:(id)arg2 identifierBlock:(CDUnknownBlockType)arg3 updateChangeSetBlock:(CDUnknownBlockType)arg4;	// IMP=0x000000010007a4f8
+ (id)changeSetFromObjects:(id)arg1 toObjects:(id)arg2 identifierBlock:(CDUnknownBlockType)arg3 isEqualBlock:(CDUnknownBlockType)arg4;	// IMP=0x000000010007a450
+ (id)changeSetFromObjects:(id)arg1 toObjects:(id)arg2;	// IMP=0x000000010007a3c8

@end

