//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIPresentationController.h>

@class UIView, UIVisualEffectView;

@interface HBFolderPresentationController : UIPresentationController
{
    UIVisualEffectView *_visualEffectView;	// 8 = 0x8
    UIView *_dimmingView;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x000000010004b44c
@property(retain, nonatomic) UIView *dimmingView; // @synthesize dimmingView=_dimmingView;
@property(retain, nonatomic) UIVisualEffectView *visualEffectView; // @synthesize visualEffectView=_visualEffectView;
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x000000010004b30c
- (void)dismissalTransitionDidEnd:(_Bool)arg1;	// IMP=0x000000010004b29c
- (void)dismissalTransitionWillBegin;	// IMP=0x000000010004b10c
- (void)presentationTransitionDidEnd:(_Bool)arg1;	// IMP=0x000000010004b030
- (void)presentationTransitionWillBegin;	// IMP=0x000000010004acb0

@end

