//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableSet;

@interface HBIconCacheSynchronizedSet : NSObject
{
    struct os_unfair_lock_s _lock;	// 8 = 0x8
    NSMutableSet *_objects;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x000000010004aca4
@property(readonly, nonatomic) NSMutableSet *objects; // @synthesize objects=_objects;
@property(readonly, nonatomic) struct os_unfair_lock_s lock; // @synthesize lock=_lock;
- (void)removeObject:(id)arg1;	// IMP=0x000000010004ac38
- (_Bool)addObject:(id)arg1;	// IMP=0x000000010004abb0
- (id)init;	// IMP=0x000000010004ab48

@end

