//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "HBLaunchAction.h"

#import "HBLaunchAction-Protocol.h"

@class NSString;

@interface HBLaunchApplicationAction : HBLaunchAction <HBLaunchAction>
{
}

- (void)executeWithOptions:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100091760
- (id)replacementAction;	// IMP=0x0000000100091758
- (_Bool)validate:(inout id *)arg1;	// IMP=0x00000001000914cc
- (_Bool)supportsLaunchEventTime;	// IMP=0x00000001000914c4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

