//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class HBTopShelfFetchTimer, NSString;

@protocol HBTopShelfFetchTimerDelegate <NSObject>
- (_Bool)topShelfFetchTimer:(HBTopShelfFetchTimer *)arg1 startTopShelfFetchWithIdentifier:(NSString *)arg2;
@end

