//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "HBTopShelfModel.h"

@class NSArray;

@interface HBTopShelfSectionedModel : HBTopShelfModel
{
    NSArray *_sections;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0000000100091248
@property(copy, nonatomic) NSArray *sections; // @synthesize sections=_sections;
- (unsigned long long)_itemsCount;	// IMP=0x00000001000910d0
- (void)_applyItemUpdates:(id)arg1;	// IMP=0x0000000100090f74
- (id)_logSafeDescriptionBuilder;	// IMP=0x0000000100090e94
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;	// IMP=0x0000000100090dd8
- (id)initWithTopShelfSectionedContent:(id)arg1 applicationIdentifier:(id)arg2;	// IMP=0x0000000100090b90

@end

