//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep  6 2019 11:16:02).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TVServices/TVTopShelfCarouselItem.h>

@class HBTopShelfRottenTomatoesRating, NSArray, _TVContentRating;

@interface TVTopShelfCarouselItem (HBTopShelf)
@property(readonly, nonatomic) _TVContentRating *hb_contentRating;
@property(readonly, nonatomic) HBTopShelfRottenTomatoesRating *hb_rottenTomatoesRating;
@property(readonly, copy, nonatomic) NSArray *hb_namedAttributes;
@end

