//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TVServices/TVTopShelfSectionedItem.h>

@interface TVTopShelfSectionedItem (HBTopShelf)
+ (long long)_hb_genericPlaceholderForSectionedImageShape:(unsigned long long)arg1;	// IMP=0x000000010006497c
- (_Bool)_hb_hasPodcastsRelatedMediaTypeWithApplicationIdentifier:(id)arg1;	// IMP=0x00000001000647e4
- (_Bool)_hb_hasMusicRelatedMediaTypeWithApplicationIdentifier:(id)arg1;	// IMP=0x00000001000645cc
- (_Bool)_hb_hasPhotoRelatedMediaTypeWithApplicationIdentifier:(id)arg1;	// IMP=0x00000001000645b0
- (_Bool)_hb_hasTVRelatedMediaTypeWithApplicationIdentifier:(id)arg1;	// IMP=0x00000001000643e8
- (_Bool)_hb_hasMovieRelatedMediaTypeWithApplicationIdentifier:(id)arg1;	// IMP=0x0000000100064348
- (long long)hb_placeholderAssetTypeWithApplicationIdentifier:(id)arg1;	// IMP=0x000000010006420c
@property(readonly, nonatomic) struct CGSize hb_imageSize;
@property(readonly, nonatomic) unsigned long long hb_imageShape;
@end

