//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MTLFunctionConstantValues, NSArray, NSString;
@protocol MTLDevice, MTLFunction;

@protocol MTLLibrary <NSObject>
@property(nonatomic, readonly) NSArray *functionNames;
- (void)newFunctionWithName:(NSString *)arg1 constantValues:(MTLFunctionConstantValues *)arg2 completionHandler:(void (^)(id <MTLFunction>, NSError *))arg3;
- (id <MTLFunction>)newFunctionWithName:(NSString *)arg1 constantValues:(MTLFunctionConstantValues *)arg2 error:(id *)arg3;
- (id <MTLFunction>)newFunctionWithName:(NSString *)arg1;
@property(nonatomic, readonly) id <MTLDevice> device;
@property(nonatomic, copy) NSString *label;
@end

