//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface TVMusicLibraryUtilities : NSObject
{
}

+ (id)playlistWithPersistentID:(long long)arg1;	// IMP=0x00000001000401c0
+ (_Bool)playlistFolderExistsWithPersistentID:(long long)arg1;	// IMP=0x00000001000400e8
+ (_Bool)playlistExistsWithPersistentID:(long long)arg1;	// IMP=0x000000010004008c
+ (id)urlForDisplayingPlaylist:(id)arg1;	// IMP=0x000000010003fd38
+ (id)stringWithAppendedExplicitIndicator:(id)arg1;	// IMP=0x000000010003fc6c
+ (void)findSingleMusicVideoInAlbum:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x000000010003f938
+ (id)_modelSongForAdamID:(long long)arg1;	// IMP=0x000000010003f8c4
+ (id)_libraryAddRemoveQueue;	// IMP=0x000000010003f854
+ (void)_addItemToPlaylist:(id)arg1 objectToAdd:(id)arg2 itemsToAdd:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x000000010003f59c
+ (void)_storeRequestForID:(id)arg1 profile:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x000000010003f2d0
+ (void)_storeProductRequestForID:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x000000010003f274
+ (void)showContextMenuForLibraryObject:(id)arg1 inContainer:(id)arg2;	// IMP=0x000000010003f188
+ (void)showContextMenuForLibraryObject:(id)arg1;	// IMP=0x000000010003f178
+ (void)storeURLRequestForID:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x000000010003f11c
+ (id)playlistChangeRequestQueue;	// IMP=0x000000010003f07c
+ (void)getSongsInAlbum:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x000000010003e678
+ (void)getItemsInPlaylist:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x000000010003dab4
+ (void)addPlaylist:(id)arg1 toPlaylist:(id)arg2 itemsToAdd:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x000000010003d860
+ (void)addAlbum:(id)arg1 toPlaylist:(id)arg2 songsToAdd:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x000000010003d5a0
+ (void)addSong:(id)arg1 toPlaylist:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x000000010003d4a0
+ (void)removeSong:(id)arg1 fromPlaylist:(id)arg2 atPosition:(long long)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x000000010003cc00
+ (void)findPlaylistWithCloudGlobalID:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x000000010003c9d0
+ (void)findMPSongWithIdentifiers:(id)arg1 itemProperties:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x000000010003c860
+ (void)findMPSongInLibraryWithSubscriptionAdamID:(long long)arg1 itemProperties:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x000000010003c7b4
+ (void)findItemInLibraryWithPersistentID:(long long)arg1 itemKind:(id)arg2 itemProperties:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x000000010003c6e4
+ (void)findMPObjectWithIdentifiers:(id)arg1 itemKind:(id)arg2 itemProperties:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x000000010003c47c
+ (void)removeItemsFromLibraryWithSagaIDs:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x000000010003bd30
+ (void)addGlobalPlaylistToLibraryWithID:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x000000010003ba7c
+ (_Bool)isItemPendingAddToLibraryForAdamID:(long long)arg1;	// IMP=0x000000010003b9f4
+ (void)removeMPObjectFromLibrary:(id)arg1;	// IMP=0x000000010003b744
+ (void)addItemToLibraryWithAdamID:(long long)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x000000010003aee0

@end

