//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TVMusicLibraryAlbumsViewController.h"

@interface TVMusicLibraryComposerDetailViewController : TVMusicLibraryAlbumsViewController
{
}

- (_Bool)showGradientMask;	// IMP=0x0000000100097f28
- (double)cellsTopMargin;	// IMP=0x0000000100097f1c
- (struct CGSize)artworkSize;	// IMP=0x0000000100097f0c
- (struct CGSize)cellSize;	// IMP=0x0000000100097ef8
- (double)headerVerticalOffset;	// IMP=0x0000000100097ef0

@end

