//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TVMusicMPObjectMediaItem.h"

@class MPModelTVEpisode;

@interface TVMusicMPTVEpisodeMediaItem : TVMusicMPObjectMediaItem
{
}

- (id)description;	// IMP=0x0000000100095b28
- (id)mediaItemMetadataForProperty:(id)arg1;	// IMP=0x00000001000955c4
- (_Bool)useBookmarks;	// IMP=0x00000001000955bc
@property(readonly, nonatomic) MPModelTVEpisode *tvEpisode;
- (id)initWithTVEpisode:(id)arg1;	// IMP=0x00000001000955a0
- (id)initWithTVEpisode:(id)arg1 mediaItemMetadata:(id)arg2;	// IMP=0x0000000100095530

@end

