//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class MPModelPlayEvent, MPModelSong, NSAttributedString, NSData, NSString, UIActivityIndicatorView, UIFont, UILabel, UIScrollView, UIView;

@interface TVMusicLyricsViewController : UIViewController
{
    UILabel *_lyricsLabel;	// 8 = 0x8
    UIScrollView *_lyricsScrollView;	// 16 = 0x10
    UIActivityIndicatorView *_spinnerView;	// 24 = 0x18
    UILabel *_songTitleLabel;	// 32 = 0x20
    double _startViewTime;	// 40 = 0x28
    UIFont *_boldLyricsFont;	// 48 = 0x30
    _Bool _viewAppeared;	// 56 = 0x38
    UIView *_gradientView;	// 64 = 0x40
    UIView *_gradientMaskView;	// 72 = 0x48
    _Bool _viewVisible;	// 80 = 0x50
    NSString *_PAFFeatureName;	// 88 = 0x58
    NSData *_PAFRecommendationData;	// 96 = 0x60
    MPModelPlayEvent *_PAFContainerData;	// 104 = 0x68
    MPModelSong *_song;	// 112 = 0x70
    NSAttributedString *_lyricsText;	// 120 = 0x78
    NSString *_lyricsID;	// 128 = 0x80
    NSString *_language;	// 136 = 0x88
}

+ (id)songwritersStringWithPrefix:(id)arg1 songwriters:(id)arg2;	// IMP=0x000000010000e930
- (void).cxx_destruct;	// IMP=0x0000000100010570
@property(nonatomic, getter=isViewVisible) _Bool viewVisible; // @synthesize viewVisible=_viewVisible;
@property(copy, nonatomic) NSString *language; // @synthesize language=_language;
@property(copy, nonatomic) NSString *lyricsID; // @synthesize lyricsID=_lyricsID;
@property(copy, nonatomic) NSAttributedString *lyricsText; // @synthesize lyricsText=_lyricsText;
@property(retain, nonatomic) MPModelSong *song; // @synthesize song=_song;
@property(retain, nonatomic) MPModelPlayEvent *PAFContainerData; // @synthesize PAFContainerData=_PAFContainerData;
@property(retain, nonatomic) NSData *PAFRecommendationData; // @synthesize PAFRecommendationData=_PAFRecommendationData;
@property(copy, nonatomic) NSString *PAFFeatureName; // @synthesize PAFFeatureName=_PAFFeatureName;
- (void)_handleTogglePlayPause;	// IMP=0x000000010001042c
- (void)_reportPAFEventForLyricsView;	// IMP=0x00000001000100e8
- (void)_showErrorAlertWithTitle:(id)arg1 message:(id)arg2;	// IMP=0x000000010000ff5c
- (void)viewWillLayoutSubviews;	// IMP=0x000000010000fa24
- (id)preferredFocusEnvironments;	// IMP=0x000000010000f9b4
@property(readonly, nonatomic) NSString *songArtist;
@property(readonly, nonatomic) NSString *songTitle;
- (_Bool)_showLyrics:(id)arg1 withLyricsID:(id)arg2 error:(id)arg3;	// IMP=0x000000010000f5fc
- (void)_loadAndDisplayStoreLyrics;	// IMP=0x000000010000f04c
- (id)_attributedStringFromLyricsInfo:(id)arg1;	// IMP=0x000000010000eb6c
- (void)_hideActivityIndicator;	// IMP=0x000000010000e8e4
- (void)_showActivityIndicator;	// IMP=0x000000010000e7f4
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x000000010000e7a0
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x000000010000e750
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x000000010000e6c8
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x000000010000e3cc
- (void)viewDidLoad;	// IMP=0x000000010000dcb0
- (void)applicationDidBecomeActive:(id)arg1;	// IMP=0x000000010000dc74
- (void)applicationWillResignActive:(id)arg1;	// IMP=0x000000010000dc30
- (id)initWithSong:(id)arg1;	// IMP=0x000000010000db18

@end

