//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton;

@interface TVTextEntryFooterView : UIView
{
    UIButton *_submitButton;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00000001000a7088
@property(retain, nonatomic) UIButton *submitButton; // @synthesize submitButton=_submitButton;
- (struct CGRect)_buttonFrameWithBounds:(struct CGRect)arg1;	// IMP=0x00000001000a7018
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x00000001000a6fe0
- (void)layoutSubviews;	// IMP=0x00000001000a6f94

@end

