//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@interface ALCMCalorieDataDeprecated : PBCodable <NSCopying>
{
    double _mets;	// 8 = 0x8
    double _timestamp;	// 16 = 0x10
    int _activityType;	// 24 = 0x18
    float _energyMagnitude;	// 28 = 0x1c
    float _meanAngleX;	// 32 = 0x20
    int _metSource;	// 36 = 0x24
    float _metsHR;	// 40 = 0x28
    float _metsWR;	// 44 = 0x2c
    int _recordId;	// 48 = 0x30
    _Bool _isStanding;	// 52 = 0x34
    _Bool _regularEntry;	// 53 = 0x35
    struct {
        unsigned int timestamp:1;
        unsigned int metsHR:1;
        unsigned int metsWR:1;
        unsigned int recordId:1;
    } _has;	// 56 = 0x38
}

@property(nonatomic) float metsWR; // @synthesize metsWR=_metsWR;
@property(nonatomic) float metsHR; // @synthesize metsHR=_metsHR;
@property(nonatomic) _Bool regularEntry; // @synthesize regularEntry=_regularEntry;
@property(nonatomic) double timestamp; // @synthesize timestamp=_timestamp;
@property(nonatomic) float energyMagnitude; // @synthesize energyMagnitude=_energyMagnitude;
@property(nonatomic) float meanAngleX; // @synthesize meanAngleX=_meanAngleX;
@property(nonatomic) int metSource; // @synthesize metSource=_metSource;
@property(nonatomic) double mets; // @synthesize mets=_mets;
@property(nonatomic) _Bool isStanding; // @synthesize isStanding=_isStanding;
@property(nonatomic) int activityType; // @synthesize activityType=_activityType;
@property(nonatomic) int recordId; // @synthesize recordId=_recordId;
- (void)mergeFrom:(id)arg1;	// IMP=0x00000001003a3728
- (unsigned long long)hash;	// IMP=0x00000001003a33ec
- (_Bool)isEqual:(id)arg1;	// IMP=0x00000001003a323c
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001003a30f4
- (void)copyTo:(id)arg1;	// IMP=0x00000001003a2fe0
- (void)writeTo:(id)arg1;	// IMP=0x00000001003a2e7c
- (_Bool)readFrom:(id)arg1;	// IMP=0x00000001003a2e74
- (id)dictionaryRepresentation;	// IMP=0x00000001003a2194
- (id)description;	// IMP=0x00000001003a2114
@property(nonatomic) _Bool hasMetsWR;
@property(nonatomic) _Bool hasMetsHR;
@property(nonatomic) _Bool hasTimestamp;
- (int)StringAsMetSource:(id)arg1;	// IMP=0x00000001003a1f74
- (id)metSourceAsString:(int)arg1;	// IMP=0x00000001003a1eec
- (int)StringAsActivityType:(id)arg1;	// IMP=0x00000001003a1ae4
- (id)activityTypeAsString:(int)arg1;	// IMP=0x00000001003a180c
@property(nonatomic) _Bool hasRecordId;

@end

