//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CLIntersiloClientProtocol-Protocol.h"

@class NSData, NSDate;

@protocol CLAvengerScannerClientProtocol <CLIntersiloClientProtocol>

@optional
- (void)onAggressiveScanEnded;
- (void)onAggressiveScanStarted;
- (void)onAvengerAdvertisement:(NSDate *)arg1 address:(NSData *)arg2 advertisementData:(NSData *)arg3 status:(unsigned char)arg4 rssi:(long long)arg5 reserved:(NSData *)arg6;
@end

