//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CLBarometerCalibrationSource.h"

@protocol CLWifiServiceProtocol;

@interface CLBarometerCalibrationSourceWifi : CLBarometerCalibrationSource
{
    id <CLWifiServiceProtocol> _wifiServiceProxy;	// 32 = 0x20
    struct unique_ptr<CLWifiService_Type::Client, std::__1::default_delete<CLWifiService_Type::Client>> _wifiServiceClient;	// 40 = 0x28
    struct CLBarometerCalibrationWiFiActiveScanBuffer activeScanBuffer;	// 48 = 0x30
    double lastSubmissionToSourceAggregator;	// 88 = 0x58
}

- (id).cxx_construct;	// IMP=0x00000001007134ac
- (void).cxx_destruct;	// IMP=0x0000000100713458
- (void)writeWifiAPToJson:(id)arg1 withData:(const vector_94cb9693 *)arg2;	// IMP=0x0000000100712f54
- (void)dealloc;	// IMP=0x0000000100712ee0
- (shared_ptr_760f25b1)convertAPToWifiData:(struct AccessPoint)arg1;	// IMP=0x0000000100712e30
- (void)processScanCache:(const vector_94cb9693 *)arg1;	// IMP=0x0000000100712b7c
- (void)processActiveScan:(const vector_94cb9693 *)arg1;	// IMP=0x0000000100712304
- (void)onWifiServiceNotification:(int)arg1 data:(struct NotificationData)arg2;	// IMP=0x0000000100712158
- (void)disableSource;	// IMP=0x0000000100712100
- (void)enableSource;	// IMP=0x0000000100712074
- (id)initWithUniverse:(id)arg1 delegate:(id)arg2;	// IMP=0x0000000100711edc

@end

