//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol CLBarometerCalibrationSourceClient, CLIntersiloUniverse;

@interface CLBarometerCalibrationSource : NSObject
{
    id <CLIntersiloUniverse> _universe;	// 8 = 0x8
    id <CLBarometerCalibrationSourceClient> _delegate;	// 16 = 0x10
    _Bool _sourceEnabled;	// 24 = 0x18
}

- (void)disableSource;	// IMP=0x000000010019fd38
- (void)enableSource;	// IMP=0x000000010019fd34
- (void)dealloc;	// IMP=0x000000010019fcfc
- (id)initWithUniverse:(id)arg1 delegate:(id)arg2;	// IMP=0x000000010019fc20

@end

