//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <LocationSupport/CLIntersiloService.h>

#import "CLClientAuthorizationCacheProtocol-Protocol.h"

@class NSDictionary, NSMutableArray, NSString;

@interface CLClientAuthorizationCache : CLIntersiloService <CLClientAuthorizationCacheProtocol>
{
    NSDictionary *_clients;	// 8 = 0x8
    NSMutableArray *_cachePopulationReplyBlocks;	// 16 = 0x10
}

+ (id)getSilo;	// IMP=0x0000000100789744
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x0000000100789720
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x00000001008ac3d4
@property(retain, nonatomic) NSMutableArray *cachePopulationReplyBlocks; // @synthesize cachePopulationReplyBlocks=_cachePopulationReplyBlocks;
@property(retain, nonatomic) NSDictionary *clients; // @synthesize clients=_clients;
- (void)notifyWhenCacheIsPopulatedWithReply:(CDUnknownBlockType)arg1;	// IMP=0x0000000100789db0
- (void)setClientsAuthorizationMap:(id)arg1;	// IMP=0x0000000100789b6c
- (void)getAuthorizationContextOfClient:(id)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x0000000100789a40
- (id)syncgetAuthorizationContextOfClient:(id)arg1;	// IMP=0x0000000100789a0c
- (int)syncgetAuthorizationOfClient:(id)arg1 forServiceMask:(unsigned long long)arg2;	// IMP=0x0000000100789874
- (void)endService;	// IMP=0x0000000100789834
- (void)beginService;	// IMP=0x0000000100789800
- (id)init;	// IMP=0x00000001007897bc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

