//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CLNotifierServiceAdapter.h"

#import "CLFenceManagerProtocol-Protocol.h"

@class NSString;

@interface CLFenceManagerAdapter : CLNotifierServiceAdapter <CLFenceManagerProtocol>
{
}

+ (id)getSilo;	// IMP=0x00000001002cdf54
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x00000001002cdf30
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x00000001008819d8
+ (_Bool)isSupported;	// IMP=0x00000001002d04c0
- (void)getFencesForBundleID:(id)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x00000001002d0390
- (void)simulateFenceWithBundleID:(id)arg1 andFenceID:(id)arg2 eventType:(unsigned char)arg3 atLocation:(id)arg4;	// IMP=0x00000001002cfe60
- (_Bool)syncgetFences:(vector_7520210c *)arg1 forKey:(id)arg2;	// IMP=0x00000001002cfdc0
- (_Bool)syncgetHasMonitoredFences:(id)arg1;	// IMP=0x00000001002cfd2c
- (void)requestRegionState:(CDUnknownBlockType)arg1;	// IMP=0x00000001002cf628
- (void)removeFence:(CDUnknownBlockType)arg1;	// IMP=0x00000001002cf400
- (void)addFence:(CDUnknownBlockType)arg1;	// IMP=0x00000001002ce1f0
- (_Bool)syncgetDoSync:(CDUnknownBlockType)arg1;	// IMP=0x00000001002ce1b4
- (void)doAsync:(CDUnknownBlockType)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x00000001002ce170
- (void)doAsync:(CDUnknownBlockType)arg1;	// IMP=0x00000001002ce13c
- (struct CLFenceManager *)adaptee;	// IMP=0x00000001002ce100
- (void)endService;	// IMP=0x00000001002ce0dc
- (void)beginService;	// IMP=0x00000001002ce010
- (id)init;	// IMP=0x00000001002cdfcc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

