//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <LocationSupport/CLIntersiloService.h>

#import "CLLocationStreamingConnectionManagerClientProtocol-Protocol.h"
#import "CLRemoteMotionAlarmServiceProtocol-Protocol.h"

@class CLTimer, NSMutableSet, NSString;
@protocol CLLocationStreamingConnectionManagerServiceProtocol;

@interface CLRemoteMotionAlarm : CLIntersiloService <CLRemoteMotionAlarmServiceProtocol, CLLocationStreamingConnectionManagerClientProtocol>
{
    int _lastKnownMotionState;	// 8 = 0x8
    id <CLLocationStreamingConnectionManagerServiceProtocol> _streamingConnection;	// 16 = 0x10
    NSMutableSet *_motionAlarmClients;	// 24 = 0x18
    CLTimer *_resendTimer;	// 32 = 0x20
    CLTimer *_revertToUnknownTimer;	// 40 = 0x28
}

+ (_Bool)isSupported;	// IMP=0x00000001004c3410
+ (id)getSilo;	// IMP=0x00000001004c3398
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x00000001004c3374
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x000000010089267c
@property(retain, nonatomic) CLTimer *revertToUnknownTimer; // @synthesize revertToUnknownTimer=_revertToUnknownTimer;
@property(retain, nonatomic) CLTimer *resendTimer; // @synthesize resendTimer=_resendTimer;
@property(nonatomic) int lastKnownMotionState; // @synthesize lastKnownMotionState=_lastKnownMotionState;
@property(retain, nonatomic) NSMutableSet *motionAlarmClients; // @synthesize motionAlarmClients=_motionAlarmClients;
@property(retain, nonatomic) id <CLLocationStreamingConnectionManagerServiceProtocol> streamingConnection; // @synthesize streamingConnection=_streamingConnection;
- (void)pairedDeviceIsNearby:(_Bool)arg1;	// IMP=0x00000001004c4324
- (void)successfullySentMessage:(id)arg1;	// IMP=0x00000001004c4320
- (void)failedToSendMessage:(id)arg1 withError:(id)arg2 isFatal:(_Bool)arg3;	// IMP=0x00000001004c431c
- (void)receivedMessageOfType:(id)arg1 withPayload:(id)arg2;	// IMP=0x00000001004c4140
- (void)unregisterClientForRemoteMotionAlarm:(byref id)arg1;	// IMP=0x00000001004c40f8
- (void)registerClientForRemoteMotionAlarm:(byref id)arg1;	// IMP=0x00000001004c4048
- (void)sendMotionAlarmRequest;	// IMP=0x00000001004c3e04
- (void)delayRevertToUnknownTimer;	// IMP=0x00000001004c3dd4
- (void)evaluateMotionAlarmState;	// IMP=0x00000001004c3b04
- (void)endService;	// IMP=0x00000001004c3888
- (void)beginService;	// IMP=0x00000001004c34bc
- (id)init;	// IMP=0x00000001004c3478

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

