//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CLNotifierServiceAdapter.h"

#import "CLSensorRecorderNotifierProtocol-Protocol.h"

@class NSString;

@interface CLSensorRecorderNotifierAdapter : CLNotifierServiceAdapter <CLSensorRecorderNotifierProtocol>
{
}

+ (id)getSilo;	// IMP=0x00000001006cd07c
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x00000001006cd058
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x00000001008a4d1c
+ (_Bool)isSupportedForType:(int)arg1;	// IMP=0x00000001006cd318
- (_Bool)syncgetDoSync:(CDUnknownBlockType)arg1;	// IMP=0x00000001006cd2dc
- (void)doAsync:(CDUnknownBlockType)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x00000001006cd298
- (void)doAsync:(CDUnknownBlockType)arg1;	// IMP=0x00000001006cd264
- (struct CLSensorRecorderNotifier *)adaptee;	// IMP=0x00000001006cd228
- (void)endService;	// IMP=0x00000001006cd204
- (void)beginService;	// IMP=0x00000001006cd138
- (id)init;	// IMP=0x00000001006cd0f4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

