//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CLNotifierServiceAdapter.h"

#import "CLTilesManagerProtocol-Protocol.h"

@class NSString;

@interface CLTilesManagerAdapter : CLNotifierServiceAdapter <CLTilesManagerProtocol>
{
}

+ (_Bool)isSupported;	// IMP=0x000000010056c34c
+ (id)getSilo;	// IMP=0x000000010056c0b0
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x000000010056c08c
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x0000000100897acc
- (_Bool)syncgetListTilesDirectory:(id)arg1 type:(int)arg2 time:(double)arg3;	// IMP=0x0000000100570078
- (_Bool)syncgetTransitMacAddressesAmong:(struct vector<unsigned long long, std::__1::allocator<unsigned long long>> *)arg1 nearLatitude:(double)arg2 longitude:(double)arg3 resultMacAddresses:(struct vector<CLTilesManager_Type::TransitMac, std::__1::allocator<CLTilesManager_Type::TransitMac>> *)arg4;	// IMP=0x000000010056fd90
- (_Bool)syncgetRegionPreloadManifest:(vector_ffaa9e0a *)arg1;	// IMP=0x000000010056faf8
- (_Bool)syncgetAppAvailabilityForLocation:(const CDStruct_c412fcbb *)arg1 radius:(float)arg2 searchContext:(struct CLTilesSearchContext *)arg3 availabilityList:(struct list<CLTilesManager_Type::AppAvailability, std::__1::allocator<CLTilesManager_Type::AppAvailability>> *)arg4 includeRegionalApps:(_Bool)arg5;	// IMP=0x000000010056eba8
- (_Bool)syncgetDeleteTileFile:(int)arg1 atPath:(id)arg2;	// IMP=0x000000010056e794
- (id)syncgetTileFilePath:(int)arg1 latitude:(double)arg2 longitude:(double)arg3 isFileAccessible:(_Bool *)arg4 isTileNotExistingOnServer:(_Bool *)arg5;	// IMP=0x000000010056e6ac
- (_Bool)syncgetTileStats:(struct LocationNetworkQueries *)arg1;	// IMP=0x000000010056e53c
- (void)enableAppTilesDownload:(_Bool)arg1;	// IMP=0x000000010056e3b4
- (void)requestTileDownloadByType:(int)arg1 path:(id)arg2 details:(struct CLTileFileDownloadDetails)arg3;	// IMP=0x000000010056e2e0
- (void)requestTileDownloadByType:(int)arg1 lat:(double)arg2 lon:(double)arg3 seckey:(unsigned long long)arg4 details:(struct CLTileFileDownloadDetails)arg5;	// IMP=0x000000010056c420
- (_Bool)syncgetDoSync:(CDUnknownBlockType)arg1;	// IMP=0x000000010056c310
- (void)doAsync:(CDUnknownBlockType)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x000000010056c2cc
- (void)doAsync:(CDUnknownBlockType)arg1;	// IMP=0x000000010056c298
- (struct CLTilesManager *)adaptee;	// IMP=0x000000010056c25c
- (void)endService;	// IMP=0x000000010056c238
- (void)beginService;	// IMP=0x000000010056c16c
- (id)init;	// IMP=0x000000010056c128

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

