//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <LocationSupport/CLIntersiloService.h>

#import "CLWorkoutRecorderProtocol-Protocol.h"
#import "CLWorkoutRecorderPublisherDelegate-Protocol.h"
#import "CLWorkoutRecordingDelegate-Protocol.h"

@class CLDispatchSilo, CLServiceVendor, CLWorkoutRecorderPublisher, CLWorkoutRecording, NSObject, NSString, NSURL;
@protocol OS_dispatch_source;

@interface CLWorkoutRecorder : CLIntersiloService <CLWorkoutRecorderProtocol, CLWorkoutRecorderPublisherDelegate, CLWorkoutRecordingDelegate>
{
    NSURL *_workingDirectory;	// 8 = 0x8
    _Bool _deviceUnlocked;	// 16 = 0x10
    CLWorkoutRecorderPublisher *_publisher;	// 24 = 0x18
    struct unique_ptr<CLDataProtectionManager_Type::Client, std::__1::default_delete<CLDataProtectionManager_Type::Client>> _dataProtectionClient;	// 32 = 0x20
    unsigned char _workoutSession[16];	// 40 = 0x28
    NSObject<OS_dispatch_source> *_deferredStopTimer;	// 56 = 0x38
    struct unique_ptr<CLMotionStateMediator_Type::Client, std::__1::default_delete<CLMotionStateMediator_Type::Client>> _motionStateMediatorClient;	// 64 = 0x40
    struct unique_ptr<CLPowerAssertion, std::__1::default_delete<CLPowerAssertion>> _powerAssertion;	// 72 = 0x48
    struct CLDaemonLocation _recentLocation;	// 80 = 0x50
    struct CLServiceLocationProvider *_serviceLocationProvider;	// 224 = 0xe0
    struct unique_ptr<CLServiceLocationProvider_Type::Client, std::__1::default_delete<CLServiceLocationProvider_Type::Client>> _serviceLocationClient;	// 232 = 0xe8
    CLWorkoutRecording *_recording;	// 240 = 0xf0
}

+ (_Bool)isSupported;	// IMP=0x000000010084bf28
+ (id)getSilo;	// IMP=0x000000010084bdcc
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x000000010084bda8
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x000000010084bd24
- (id).cxx_construct;	// IMP=0x000000010084e788
- (void).cxx_destruct;	// IMP=0x000000010084e6e4
@property(readonly, retain, nonatomic) CLWorkoutRecorderPublisher *publisher; // @synthesize publisher=_publisher;
- (void)handleResponse:(id)arg1;	// IMP=0x000000010084e530
- (_Bool)workingDirectoryHasSufficientFreeSpace;	// IMP=0x000000010084e27c
- (_Bool)createWorkingDirectory;	// IMP=0x000000010084ddc0
- (_Bool)acquireToken;	// IMP=0x000000010084d9ac
- (void)onDeferredStopTimerShouldPublish:(_Bool)arg1;	// IMP=0x000000010084d960
- (void)cancelDeferredStopTimer;	// IMP=0x000000010084d924
- (void)scheduleStop;	// IMP=0x000000010084d5bc
- (void)onMotionStateMediatorNotification:(const int *)arg1 data:(const union NotificationData *)arg2;	// IMP=0x000000010084d2a4
- (void)onLocationNotification:(const int *)arg1 data:(const struct NotificationData *)arg2;	// IMP=0x000000010084d260
- (void)onDataProtectionNotification:(const int *)arg1 data:(const struct NotificationData *)arg2;	// IMP=0x000000010084d1c0
- (void)publishRecording;	// IMP=0x000000010084cd64
- (void)stopRecordingShouldPublish:(_Bool)arg1;	// IMP=0x000000010084cba0
- (void)startRecording;	// IMP=0x000000010084c3b4
- (void)endService;	// IMP=0x000000010084c26c
- (void)beginService;	// IMP=0x000000010084bf30
- (void)dealloc;	// IMP=0x000000010084be98
- (id)init;	// IMP=0x000000010084be44

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, retain, nonatomic) CLDispatchSilo *silo; // @dynamic silo;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;
@property(readonly, nonatomic) CLServiceVendor *vendor;

@end

