//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface TVIMetadataParser : NSObject
{
}

+ (id)assetWithJSONObject:(id)arg1;	// IMP=0x000000010001dcd8
+ (id)metadataWithJSONObject:(id)arg1;	// IMP=0x000000010001dc38
+ (id)metadataWithData:(id)arg1;	// IMP=0x000000010001dab8

@end

