//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class INInteraction, NSPredicate, NSSet, NSString, NSUUID;

@protocol CKInteractionProcessing <NSObject>
- (NSSet *)supportedTypes;
- (NSPredicate *)bundleIdPredicate;
- (_Bool)supportsSiriDonations;

@optional
- (_Bool)processInteraction:(INInteraction *)arg1 dkEventUUID:(NSUUID *)arg2;
- (_Bool)processInteraction:(INInteraction *)arg1 bundleId:(NSString *)arg2;
@end

