//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TVSettingsCRDPreviewContainerView : UIView
{
    UIView *_contentView;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00000001000ca400
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
- (void)layoutSubviews;	// IMP=0x00000001000ca24c

@end

