//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CastleRequest.h"

@class NSArray;

@interface QuotaAppDetailsRequest : CastleRequest
{
    NSArray *_bundleIds;	// 16 = 0x10
    NSArray *_bundleIDs;	// 24 = 0x18
}

+ (Class)responseClass;	// IMP=0x000000010007d428
- (void).cxx_destruct;	// IMP=0x000000010007d6c0
@property(retain, nonatomic) NSArray *bundleIDs; // @synthesize bundleIDs=_bundleIDs;
- (id)urlRequest;	// IMP=0x000000010007d4f8
- (id)initWithAccount:(id)arg1 bundleIDs:(id)arg2 quotaInfo:(id)arg3;	// IMP=0x000000010007d434

@end

