//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppleAccount/AAResponse.h>

@class NSArray, NSMutableArray;

@interface QuotaAppDetailsResponse : AAResponse
{
    NSMutableArray *_apps;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x00000001000cbba4
@property(readonly, nonatomic) NSArray *apps; // @synthesize apps=_apps;
- (id)description;	// IMP=0x00000001000cbb04
- (void)addApps:(id)arg1;	// IMP=0x00000001000cba90
- (id)initWithHTTPResponse:(id)arg1 data:(id)arg2;	// IMP=0x00000001000cb680

@end

