//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep  6 2019 11:16:02).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TVServices/TVSBluetoothDevice.h>

@interface TVSBluetoothDevice (TVSettings)
- (id)_accessory;	// IMP=0x000000010009b9f4
- (_Bool)tvset_supportsIAP;	// IMP=0x000000010009b988
- (id)tvset_lookupURL;	// IMP=0x000000010009b434
@end

