//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TVSettingKit/TSKViewController.h>

@class TSKPreviewViewController, TSKSettingItem;

@interface TVSettingsMoviesViewController : TSKViewController
{
    TSKPreviewViewController *_moviesPreviewViewController;	// 8 = 0x8
    TSKPreviewViewController *_tvPreviewViewController;	// 16 = 0x10
    TSKSettingItem *_tvFavoritesItem;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x0000000100092df0
- (void)_videoResolutionSelected:(id)arg1;	// IMP=0x0000000100092d54
- (id)previewForItemAtIndexPath:(id)arg1;	// IMP=0x0000000100092c04
- (id)loadSettingGroups;	// IMP=0x000000010009148c

@end

