//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TVSettingKit/TSKViewController.h>

#import "TVSettingsPhotoCollectionViewControllerSelectionDelegate-Protocol.h"

@class NSString, TVPhotoCollectionGroup, TVSettingsPhotoCollectionPreviewViewController, UIVisualEffectView;
@protocol TVSettingsPhotoCollectionGroupViewControllerDelegate;

@interface TVSettingsPhotoCollectionGroupViewController : TSKViewController <TVSettingsPhotoCollectionViewControllerSelectionDelegate>
{
    UIVisualEffectView *_backdropView;	// 8 = 0x8
    id <TVSettingsPhotoCollectionGroupViewControllerDelegate> _delegate;	// 16 = 0x10
    TVPhotoCollectionGroup *_photoCollectionGroup;	// 24 = 0x18
    TVSettingsPhotoCollectionPreviewViewController *_photoPreviewController;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x00000001000b8880
@property(retain, nonatomic) TVSettingsPhotoCollectionPreviewViewController *photoPreviewController; // @synthesize photoPreviewController=_photoPreviewController;
@property(retain, nonatomic) TVPhotoCollectionGroup *photoCollectionGroup; // @synthesize photoCollectionGroup=_photoCollectionGroup;
@property(nonatomic) __weak id <TVSettingsPhotoCollectionGroupViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_updatePhotoCollectionWithIndexPath:(id)arg1;	// IMP=0x00000001000b86ec
- (id)_localizedTitleForPhotoCollection:(id)arg1;	// IMP=0x00000001000b85a4
- (void)controller:(id)arg1 didSelectAsset:(id)arg2;	// IMP=0x00000001000b84b0
- (_Bool)hasFullscreenPreview;	// IMP=0x00000001000b84a8
- (id)previewForItemAtIndexPath:(id)arg1;	// IMP=0x00000001000b8474
- (id)title;	// IMP=0x00000001000b846c
- (id)loadSettingGroups;	// IMP=0x00000001000b8120
- (void)viewDidLoad;	// IMP=0x00000001000b79a8
- (id)initWithPhotoCollectionGroup:(id)arg1;	// IMP=0x00000001000b78c8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

