//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TVSettingKit/TSKViewController.h>

#import "UISearchControllerDelegate-Protocol.h"

@class NSString, TSKPreviewViewController, TSKSettingItem, TVSettingsBluetoothFacade;

@interface TVSettingsGeneralViewController : TSKViewController <UISearchControllerDelegate>
{
    _Bool _isTimeZoneUpdateAvailable;	// 8 = 0x8
    TSKSettingItem *_siriLanguageItem;	// 16 = 0x10
    TSKSettingItem *_languageItem;	// 24 = 0x18
    TSKPreviewViewController *_languagePreviewViewController;	// 32 = 0x20
    TVSettingsBluetoothFacade *_bluetoothFacade;	// 40 = 0x28
    unsigned long long _deleteSiriHistoryState;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x000000010006b48c
@property(nonatomic) unsigned long long deleteSiriHistoryState; // @synthesize deleteSiriHistoryState=_deleteSiriHistoryState;
@property(retain, nonatomic) TVSettingsBluetoothFacade *bluetoothFacade; // @synthesize bluetoothFacade=_bluetoothFacade;
@property(nonatomic) _Bool isTimeZoneUpdateAvailable; // @synthesize isTimeZoneUpdateAvailable=_isTimeZoneUpdateAvailable;
@property(readonly, nonatomic) TSKPreviewViewController *languagePreviewViewController; // @synthesize languagePreviewViewController=_languagePreviewViewController;
@property(readonly, nonatomic) TSKSettingItem *languageItem; // @synthesize languageItem=_languageItem;
@property(readonly, nonatomic) TSKSettingItem *siriLanguageItem; // @synthesize siriLanguageItem=_siriLanguageItem;
- (void)_showDeleteSiriHistoryFailedDialog;	// IMP=0x000000010006b22c
- (id)_deleteSiriHistoryStateString;	// IMP=0x000000010006b1a0
- (void)_updateSiriDeleteHistoryItem:(id)arg1 optInStatus:(unsigned long long)arg2;	// IMP=0x000000010006b03c
- (id)_siriDeleteHistoryViewController;	// IMP=0x000000010006aa7c
- (id)_dictationDescription;	// IMP=0x000000010006a8b0
- (id)_siriUnavailableMessage;	// IMP=0x000000010006a680
- (id)_accessibilitySettingsBundlePath;	// IMP=0x000000010006a65c
- (void)_updateTimeZoneItem:(id)arg1 value:(id)arg2;	// IMP=0x000000010006a4e0
- (void)_updateAutomaticTimeZoneItem:(id)arg1 value:(id)arg2;	// IMP=0x000000010006a37c
- (id)_restrictionsViewController;	// IMP=0x000000010006a264
- (id)_sleepTimeouts;	// IMP=0x000000010006a0d8
- (id)_localeFormatter;	// IMP=0x000000010006a000
- (id)_languageFormatter;	// IMP=0x0000000100069e60
- (id)_siriLanguageFormatter;	// IMP=0x0000000100069db0
- (id)_sleepTimeoutFormatter;	// IMP=0x0000000100069ab4
- (void)activateKonamiCode:(id)arg1;	// IMP=0x0000000100069a4c
- (void)toggleAutomaticTimeZoneEnabled:(id)arg1;	// IMP=0x0000000100069648
- (void)toggleDictationEnabled:(id)arg1;	// IMP=0x0000000100069350
- (void)toggleSiriEnabled:(id)arg1;	// IMP=0x0000000100069090
- (void)bluetoothSettingsChanged:(id)arg1;	// IMP=0x0000000100069084
- (void)storeFrontChanged:(id)arg1;	// IMP=0x0000000100069078
- (void)timeChanged:(id)arg1;	// IMP=0x000000010006906c
- (void)internetAvailabilityChanged:(id)arg1;	// IMP=0x0000000100069060
- (void)editingController:(id)arg1 didProvideValue:(id)arg2 forSettingItem:(id)arg3;	// IMP=0x0000000100068970
- (id)previewForItemAtIndexPath:(id)arg1;	// IMP=0x00000001000687c4
- (id)loadSettingGroups;	// IMP=0x00000001000660c0
- (void)dealloc;	// IMP=0x0000000100066048
- (id)initWithStyle:(long long)arg1;	// IMP=0x0000000100065cd4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

