//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIGestureRecognizer.h>

@class NSTimer, TVSBluetoothDevice;

@interface TVSettingsBluetoothRecognizer : UIGestureRecognizer
{
    struct __IOHIDEventSystemClient *_hidSystemClient;	// 8 = 0x8
    unsigned long long _matchingSenderID;	// 16 = 0x10
    NSTimer *_continousTimer;	// 24 = 0x18
    unsigned int _touchCount;	// 32 = 0x20
    _Bool _continuous;	// 36 = 0x24
    TVSBluetoothDevice *_matchingPhysicalDevice;	// 40 = 0x28
}

+ (_Bool)_shouldDefaultToTouches;	// IMP=0x000000010007ef1c
- (void).cxx_destruct;	// IMP=0x000000010007fb90
@property(copy, nonatomic) TVSBluetoothDevice *matchingPhysicalDevice; // @synthesize matchingPhysicalDevice=_matchingPhysicalDevice;
@property(nonatomic, getter=isContinuous) _Bool continuous; // @synthesize continuous=_continuous;
- (void)_continuousEvent;	// IMP=0x000000010007fb50
- (void)pressesCancelled:(id)arg1 withEvent:(id)arg2;	// IMP=0x000000010007faa8
- (void)pressesEnded:(id)arg1 withEvent:(id)arg2;	// IMP=0x000000010007fa00
- (void)pressesBegan:(id)arg1 withEvent:(id)arg2;	// IMP=0x000000010007f930
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;	// IMP=0x000000010007f81c
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;	// IMP=0x000000010007f708
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;	// IMP=0x000000010007f5fc
- (_Bool)_matchesDeviceOfEvent:(id)arg1;	// IMP=0x000000010007f0a4
- (id)initWithTarget:(id)arg1 action:(SEL)arg2;	// IMP=0x000000010007ef24

@end

