//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TVSettingKit/TSKViewController.h>

#import "TVSettingsPhotoChooserViewControllerSelectionDataSource-Protocol.h"
#import "TVSettingsPhotoChooserViewControllerSelectionDelegate-Protocol.h"

@class NSArray, NSString, TSKSettingItem, TVSettingsCRDPreviewViewController, TVSettingsPhotoChooserViewController;

@interface TVSettingsCRDViewController : TSKViewController <TVSettingsPhotoChooserViewControllerSelectionDataSource, TVSettingsPhotoChooserViewControllerSelectionDelegate>
{
    TVSettingsCRDPreviewViewController *_crdPreviewViewController;	// 8 = 0x8
    NSArray *_photoCollectionGroups;	// 16 = 0x10
    TSKSettingItem *_backgroundPhotoSettingItem;	// 24 = 0x18
    TVSettingsPhotoChooserViewController *__CRDBackgroundPhotoViewController;	// 32 = 0x20
}

+ (void)_removeFromHomeAndEnableEveryTimeCode;	// IMP=0x00000001000c1610
+ (CDUnknownBlockType)_makeRequireCodeEveryTimeHomeChildViewControllerBlock;	// IMP=0x00000001000c1298
+ (id)crdModeFormatter;	// IMP=0x00000001000bf9ec
- (void).cxx_destruct;	// IMP=0x00000001000c1774
@property(retain, nonatomic) TVSettingsPhotoChooserViewController *_CRDBackgroundPhotoViewController; // @synthesize _CRDBackgroundPhotoViewController=__CRDBackgroundPhotoViewController;
@property(retain, nonatomic) TSKSettingItem *backgroundPhotoSettingItem; // @synthesize backgroundPhotoSettingItem=_backgroundPhotoSettingItem;
@property(retain) NSArray *photoCollectionGroups; // @synthesize photoCollectionGroups=_photoCollectionGroups;
@property(retain, nonatomic) TVSettingsCRDPreviewViewController *crdPreviewViewController; // @synthesize crdPreviewViewController=_crdPreviewViewController;
- (id)_allowedPhotoCollectionGroups;	// IMP=0x00000001000c11e0
- (void)_fetchPhotoCollectionGroups;	// IMP=0x00000001000c0e2c
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x00000001000c0d44
- (void)controller:(id)arg1 didSelectAsset:(id)arg2 inCollection:(id)arg3 collectionGroup:(id)arg4;	// IMP=0x00000001000c0b94
- (void)controller:(id)arg1 didSelectCollectionGroup:(id)arg2;	// IMP=0x00000001000c0a80
- (id)photoCollectionGroupsForController:(id)arg1;	// IMP=0x00000001000c0a70
- (void)_showPreview:(id)arg1;	// IMP=0x00000001000c0a28
- (id)previewForItemAtIndexPath:(id)arg1;	// IMP=0x00000001000c0988
- (id)loadSettingGroups;	// IMP=0x00000001000bfcac
- (void)dealloc;	// IMP=0x00000001000bfbd4
- (id)initWithStyle:(long long)arg1;	// IMP=0x00000001000bfab0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

