//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TVSettingKit/TSKViewController.h>

@interface TVSettingsCertificateTrustViewController : TSKViewController
{
}

- (void)_toggleTrust:(id)arg1;	// IMP=0x00000001000b8d64
- (id)loadSettingGroups;	// IMP=0x00000001000b89b4

@end

