//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface TVSettings3rdPartyRemotesFacade : NSObject
{
    _Bool _recomputingConfigurations;	// 8 = 0x8
    NSArray *_configurations;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0000000100082a14
@property(nonatomic) _Bool recomputingConfigurations; // @synthesize recomputingConfigurations=_recomputingConfigurations;
@property(copy, nonatomic) NSArray *configurations; // @synthesize configurations=_configurations;
- (void)_updateConfigurations:(id)arg1;	// IMP=0x00000001000828dc
- (void)dealloc;	// IMP=0x0000000100082864
- (id)init;	// IMP=0x00000001000827b0

@end

