//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TVSettingKit/TSKViewController.h>

@class TSKAppIconPreviewViewController, TSKSettingItem, TVSettingsAppsFacade;

@interface TVSettingsAppsViewController : TSKViewController
{
    _Bool _nowPlayingEnabled;	// 8 = 0x8
    TVSettingsAppsFacade *_appsFacade;	// 16 = 0x10
    TSKSettingItem *_lastFocusedItem;	// 24 = 0x18
    TSKAppIconPreviewViewController *_appIconPreviewViewController;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x00000001000865b0
@property(retain, nonatomic) TSKAppIconPreviewViewController *appIconPreviewViewController; // @synthesize appIconPreviewViewController=_appIconPreviewViewController;
@property(nonatomic) _Bool nowPlayingEnabled; // @synthesize nowPlayingEnabled=_nowPlayingEnabled;
@property(retain, nonatomic) TSKSettingItem *lastFocusedItem; // @synthesize lastFocusedItem=_lastFocusedItem;
@property(retain, nonatomic) TVSettingsAppsFacade *appsFacade; // @synthesize appsFacade=_appsFacade;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x00000001000860fc
- (void)tableView:(id)arg1 didReceivePhysicalPlayForItemAtIndexPath:(id)arg2;	// IMP=0x0000000100086040
- (id)previewForItemAtIndexPath:(id)arg1;	// IMP=0x0000000100085e00
- (id)loadSettingGroups;	// IMP=0x0000000100085074
- (void)dealloc;	// IMP=0x0000000100085008
- (id)initWithStyle:(long long)arg1;	// IMP=0x0000000100084e7c

@end

