//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class BSCompoundAssertion;

@interface BKDisplayController : NSObject
{
    BSCompoundAssertion *_observerAssertion;	// 8 = 0x8
}

+ (id)sharedInstance;	// IMP=0x00000001000067b4
- (void).cxx_destruct;	// IMP=0x00000001000067a8
- (void)display:(id)arg1 didBlank:(_Bool)arg2;	// IMP=0x000000010000665c
- (unsigned int)taskPortForContextID:(unsigned int)arg1 displayUUID:(id)arg2;	// IMP=0x0000000100006654
- (unsigned int)hostContextIDForEmbeddedContextID:(unsigned int)arg1 displayUUID:(id)arg2;	// IMP=0x000000010000664c
- (struct CGPoint)convertCAScreenLocation:(struct CGPoint)arg1 toContextID:(unsigned int)arg2 displayUUID:(id)arg3;	// IMP=0x0000000100006640
- (struct CGPoint)convertReferenceLocation:(struct CGPoint)arg1 toCAScreenLocationForDisplayUUID:(id)arg2;	// IMP=0x0000000100006638
- (unsigned int)contextIDAtCAScreenLocation:(struct CGPoint)arg1 displayUUID:(id)arg2 excludingContextIDs:(id)arg3;	// IMP=0x00000001000065e0
- (unsigned int)contextIDAtCAScreenLocation:(struct CGPoint)arg1 displayUUID:(id)arg2;	// IMP=0x00000001000065d4
- (id)addDisplayBlankingObserver:(id)arg1;	// IMP=0x000000010000650c

@end

