//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class BSProcessDeathWatcher, NSMutableDictionary;

@interface BKEntitlementCachePerProcessEntry : NSObject
{
    NSMutableDictionary *_entitlementCache;	// 8 = 0x8
    BSProcessDeathWatcher *_deathWatcher;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0000000100028110
@property(retain, nonatomic) BSProcessDeathWatcher *deathWatcher; // @synthesize deathWatcher=_deathWatcher;
@property(retain, nonatomic) NSMutableDictionary *entitlementCache; // @synthesize entitlementCache=_entitlementCache;

@end

