//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "BKHIDEventProcessor-Protocol.h"

@class NSMutableDictionary, NSString;

@interface BKExternalHIDEventProcessor : NSObject <BKHIDEventProcessor>
{
    NSMutableDictionary *_eventRecords;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010000e8bc
- (void)_logScrollEvent:(struct __IOHIDEvent *)arg1 sender:(id)arg2;	// IMP=0x000000010000e8b8
- (void)_dispatchEvent:(struct __IOHIDEvent *)arg1 sender:(id)arg2 dispatcher:(id)arg3 destinations:(id)arg4;	// IMP=0x000000010000e6f8
- (long long)_processPointerEvent:(struct __IOHIDEvent *)arg1 sender:(id)arg2 dispatcher:(id)arg3;	// IMP=0x000000010000e0c0
- (long long)processEvent:(struct __IOHIDEvent *)arg1 sender:(id)arg2 dispatcher:(id)arg3;	// IMP=0x000000010000de3c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

