//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "BKHIDEventDispatcher-Protocol.h"

@class BKButtonHIDEventProcessor, BKExternalHIDEventProcessor, BKGenericGestureHIDEventProcessor, BKHIDEventDeliveryManager, BKHIDEventRecognizerEngine, BKHIDEventSenderCache, BKHIDEventStudyLogger, BKHumanPresenceHIDEventProcessor, BKKeyboardHIDEventProcessor, BKSLocalDefaults, BKSmartCoverHIDEventProcessor, NSString, SLGNotificationActivatedLogger;
@protocol OS_dispatch_mach, OS_dispatch_queue;

@interface BKHIDSystemInterface : NSObject <BKHIDEventDispatcher>
{
    struct __IOHIDEventSystem *_HIDEventSystem;	// 8 = 0x8
    struct __IOHIDEventSystemClient *_HIDEventSystemClient;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_gsEventQueue;	// 24 = 0x18
    BKHIDEventStudyLogger *_keyboardLogger;	// 32 = 0x20
    SLGNotificationActivatedLogger *_studyLogger;	// 40 = 0x28
    _Bool _open;	// 48 = 0x30
    _Bool _fullyInitialized;	// 49 = 0x31
    BKHIDEventDeliveryManager *_deliveryManager;	// 56 = 0x38
    BKHumanPresenceHIDEventProcessor *_humanPresenceEventProcessor;	// 64 = 0x40
    BKKeyboardHIDEventProcessor *_keyboardEventProcessor;	// 72 = 0x48
    BKGenericGestureHIDEventProcessor *_genericGestureEventProcessor;	// 80 = 0x50
    BKButtonHIDEventProcessor *_buttonEventProcessor;	// 88 = 0x58
    BKSmartCoverHIDEventProcessor *_smartCoverEventProcessor;	// 96 = 0x60
    BKExternalHIDEventProcessor *_externalEventProcessor;	// 104 = 0x68
    BKHIDEventSenderCache *_senderCache;	// 112 = 0x70
    BKHIDEventRecognizerEngine *_recognizerEngine;	// 120 = 0x78
    NSObject<OS_dispatch_mach> *_HIDSystemChannel;	// 128 = 0x80
    BKSLocalDefaults *_localDefaults;	// 136 = 0x88
}

+ (id)sharedInstance;	// IMP=0x00000001000713cc
- (void).cxx_destruct;	// IMP=0x000000010006ece4
@property(readonly, nonatomic) BKSLocalDefaults *localDefaults; // @synthesize localDefaults=_localDefaults;
@property(readonly, nonatomic) SLGNotificationActivatedLogger *studyLogger; // @synthesize studyLogger=_studyLogger;
@property(retain, getter=HIDSystemChannel) NSObject<OS_dispatch_mach> *HIDSystemChannel; // @synthesize HIDSystemChannel=_HIDSystemChannel;
@property(getter=isFullyInitialized) _Bool fullyInitialized; // @synthesize fullyInitialized=_fullyInitialized;
@property(getter=isOpen) _Bool open; // @synthesize open=_open;
@property(retain) BKHIDEventRecognizerEngine *recognizerEngine; // @synthesize recognizerEngine=_recognizerEngine;
@property(retain) BKHIDEventSenderCache *senderCache; // @synthesize senderCache=_senderCache;
@property(retain, nonatomic) BKExternalHIDEventProcessor *externalEventProcessor; // @synthesize externalEventProcessor=_externalEventProcessor;
@property(retain, nonatomic) BKSmartCoverHIDEventProcessor *smartCoverEventProcessor; // @synthesize smartCoverEventProcessor=_smartCoverEventProcessor;
@property(retain, nonatomic) BKButtonHIDEventProcessor *buttonEventProcessor; // @synthesize buttonEventProcessor=_buttonEventProcessor;
@property(retain, nonatomic) BKGenericGestureHIDEventProcessor *genericGestureEventProcessor; // @synthesize genericGestureEventProcessor=_genericGestureEventProcessor;
@property(retain, nonatomic) BKKeyboardHIDEventProcessor *keyboardEventProcessor; // @synthesize keyboardEventProcessor=_keyboardEventProcessor;
@property(retain, nonatomic) BKHumanPresenceHIDEventProcessor *humanPresenceEventProcessor; // @synthesize humanPresenceEventProcessor=_humanPresenceEventProcessor;
@property(retain) BKHIDEventDeliveryManager *deliveryManager; // @synthesize deliveryManager=_deliveryManager;
- (void)registerWatchdog;	// IMP=0x000000010006ebd0
- (void)postEvent:(struct __IOHIDEvent *)arg1 fromSender:(id)arg2;	// IMP=0x000000010006eab8
- (void)postEvent:(struct __IOHIDEvent *)arg1 toDestination:(id)arg2;	// IMP=0x000000010006eaac
- (id)destinationsForEvent:(struct __IOHIDEvent *)arg1 fromSender:(id)arg2;	// IMP=0x000000010006ea38
- (void)unregisterIOHIDServicesCallback:(CDUnknownFunctionPointerType)arg1 matchingDictionary:(id)arg2 target:(void *)arg3 refCon:(void *)arg4;	// IMP=0x000000010006e938
- (void)registerIOHIDServicesCallback:(CDUnknownFunctionPointerType)arg1 matchingDictionary:(id)arg2 target:(void *)arg3 refCon:(void *)arg4;	// IMP=0x000000010006e838
- (id)IOHIDServicesMatching:(id)arg1;	// IMP=0x000000010006e75c
- (long long)_processKeyboardEvent:(struct __IOHIDEvent *)arg1 sender:(id)arg2;	// IMP=0x000000010006e4a8
- (id)_processorForKeyboardEvent:(struct __IOHIDEvent *)arg1;	// IMP=0x000000010006e3fc
- (void)_beginHandlingEvents;	// IMP=0x000000010006e3e4
- (struct __IOHIDEvent *)systemEventOfType:(unsigned int)arg1 matchingEvent:(struct __IOHIDEvent *)arg2 options:(unsigned int)arg3;	// IMP=0x000000010006e2d8
- (void)injectGSEvent:(struct __GSEvent *)arg1;	// IMP=0x000000010006e1cc
- (void)injectHIDEvent:(struct __IOHIDEvent *)arg1;	// IMP=0x000000010006e1c0
- (void)setSystemProperty:(id)arg1 forKey:(id)arg2;	// IMP=0x000000010006e09c
- (id)systemPropertyForKey:(id)arg1;	// IMP=0x000000010006df84
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x000000010006df18
- (id)_mainDisplay;	// IMP=0x000000010006de5c
- (void)startServer;	// IMP=0x000000010006dd34
- (void)performSynchronized:(CDUnknownBlockType)arg1;	// IMP=0x000000010006dcf4
- (void)startEventProcessors;	// IMP=0x000000010006d3e0
- (void)startHIDSystem;	// IMP=0x000000010006d164
- (void)dealloc;	// IMP=0x000000010006d10c
- (id)init;	// IMP=0x000000010006cee4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

