//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "BKEventStatistic.h"

@interface BKIntegerEventStatistic : BKEventStatistic
{
    long long _value;	// 8 = 0x8
}

@property(nonatomic) long long value; // @synthesize value=_value;
- (void)increment;	// IMP=0x0000000100052a8c
- (void)reset;	// IMP=0x0000000100052a40
- (void)appendDescriptionToFormatter:(id)arg1;	// IMP=0x0000000100052988

@end

