//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "_BKCloneMirroringClientDelegate-Protocol.h"

@class NSSet, _BKCloneMirroringClient, _BKDisplayBlankingContext;
@protocol OS_dispatch_queue;

@interface BKTVOutController : NSObject <_BKCloneMirroringClientDelegate>
{
    NSObject<OS_dispatch_queue> *_workQueue;	// 8 = 0x8
    NSSet *_queue_replayCloneContextIDs;	// 16 = 0x10
    int _queue_currentVirtualDisplayClientPID;	// 24 = 0x18
    _BKCloneMirroringClient *_queue_currentCloneMirroringClient;	// 32 = 0x20
    _BKDisplayBlankingContext *_blankingContext;	// 40 = 0x28
    _Bool _queue_cloneRotationDisabled;	// 48 = 0x30
    _Bool _queue_forceTVOutMode;	// 49 = 0x31
    _Bool _queue_tvOutDisplayHasAvailableModes;	// 50 = 0x32
    _Bool _queue_systemAppHasCheckedIn;	// 51 = 0x33
    int _tvOutMode;	// 52 = 0x34
}

+ (id)sharedInstance;	// IMP=0x000000010004cc98
- (void).cxx_destruct;	// IMP=0x000000010004c270
@property int tvOutMode; // @synthesize tvOutMode=_tvOutMode;
- (void)stopListeningForSettingsChanges;	// IMP=0x000000010004c1d4
- (void)startListeningForSettingsChanges;	// IMP=0x000000010004c0f0
- (void)_tetherSettingChanged:(id)arg1;	// IMP=0x000000010004c0e4
- (void)_handleIapServerConnectionDied;	// IMP=0x000000010004c04c
@property(retain, nonatomic) NSSet *replayCloneContextIDs;
- (void)setVirtualDisplayClientPID:(int)arg1;	// IMP=0x000000010004beb0
- (void)setCloneMirroringModeFromClient:(id)arg1;	// IMP=0x000000010004be2c
- (void)setCloneRotationDisabled:(_Bool)arg1;	// IMP=0x000000010004bdd0
- (void)cloneMirroringClientDidExit:(id)arg1;	// IMP=0x000000010004bd4c
- (void)_queue_setInitialTVModeIfNeeded;	// IMP=0x000000010004badc
- (void)_queue_updateLayerKitSettings;	// IMP=0x000000010004b410
- (void)updateSettings;	// IMP=0x000000010004b3b8
- (void)_systemAppDidCheckin;	// IMP=0x000000010004b2c4
- (void)_queue_updateClonedDisplays;	// IMP=0x000000010004afe8
- (void)_writeCurrentScreenSizeToAggregated:(struct CGSize)arg1;	// IMP=0x000000010004afb0
- (void)_queue_addClone:(id)arg1;	// IMP=0x000000010004aa4c
- (_Bool)_supportsDisplayMirroring;	// IMP=0x000000010004aa0c
- (void)_collectWirelessDisplays:(id *)arg1 tvOutDisplay:(id *)arg2 makeImmutable:(_Bool)arg3;	// IMP=0x000000010004a5e8
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x000000010004a32c
- (void)_queue_currentModeDidChangeForDisplay:(id)arg1;	// IMP=0x000000010004a1ec
- (void)_queue_availableModesDidChangeForDisplay:(id)arg1 isWirelessDisplay:(_Bool)arg2 isPurpleTVOutDisplay:(_Bool)arg3;	// IMP=0x0000000100049e34
- (void)_queue_availableModesDidChangeForWirelessDisplay:(id)arg1 windowServerDisplay:(id)arg2 mainWindowServerDisplay:(id)arg3;	// IMP=0x0000000100049b8c
- (void)_queue_forceRemoveClone:(id)arg1 fromMainWindowServerDisplay:(id)arg2;	// IMP=0x0000000100049a50
- (void)_queue_availableModesDidChangeForPurpleTVOutDisplay:(id)arg1 windowServerDisplay:(id)arg2 mainWindowServerDisplay:(id)arg3;	// IMP=0x0000000100049988
- (void)setBlanked:(_Bool)arg1 forDisplay:(id)arg2;	// IMP=0x00000001000498fc
- (void)dealloc;	// IMP=0x00000001000498b0
- (id)init;	// IMP=0x0000000100049488

@end

