//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSSet;

@interface _PBAppInfoStoreUpdate : NSObject
{
    long long _updateType;	// 8 = 0x8
    NSSet *_applicationInfos;	// 16 = 0x10
    NSSet *_placeholders;	// 24 = 0x18
}

+ (id)updateDynamicState;	// IMP=0x0000000100012070
+ (id)updatePolicy;	// IMP=0x0000000100012028
+ (id)updatePlaceholders:(id)arg1;	// IMP=0x0000000100011fac
+ (id)removePlaceholders:(id)arg1;	// IMP=0x0000000100011f30
+ (id)addPlaceholders:(id)arg1;	// IMP=0x0000000100011eb4
+ (id)updateLocalizations:(id)arg1;	// IMP=0x0000000100011e38
+ (id)updateAlternateAppIcons:(id)arg1;	// IMP=0x0000000100011dbc
+ (id)updateApplicationInfos:(id)arg1;	// IMP=0x0000000100011d40
+ (id)removeApplicationInfos:(id)arg1;	// IMP=0x0000000100011cc4
+ (id)addApplicationInfos:(id)arg1;	// IMP=0x0000000100011c4c
- (void).cxx_destruct;	// IMP=0x0000000100012848
@property(readonly, copy, nonatomic) NSSet *placeholders; // @synthesize placeholders=_placeholders;
@property(readonly, copy, nonatomic) NSSet *applicationInfos; // @synthesize applicationInfos=_applicationInfos;
@property(readonly, nonatomic) long long updateType; // @synthesize updateType=_updateType;
- (id)description;	// IMP=0x00000001000122e4
- (id)initWithType:(long long)arg1 applicationInfos:(id)arg2 placeholders:(id)arg3;	// IMP=0x00000001000120b8

@end

