//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import "PBSceneLayoutElement-Protocol.h"

@class FBScene, NSString;

@interface _PBSceneView : UIView <PBSceneLayoutElement>
{
    _Bool _allowSnapshots;	// 8 = 0x8
    _Bool _wallpaperEnabled;	// 9 = 0x9
    NSString *_identifier;	// 16 = 0x10
    long long _layoutLevel;	// 24 = 0x18
    FBScene *_scene;	// 32 = 0x20
    NSString *_bundleIdentifier;	// 40 = 0x28
    UIView *_sceneView;	// 48 = 0x30
    UIView *_wallpaperView;	// 56 = 0x38
}

+ (id)_sceneViewForPBSceneView:(id)arg1;	// IMP=0x00000001001c4654
- (void).cxx_destruct;	// IMP=0x00000001001c49e4
@property(readonly, nonatomic) UIView *wallpaperView; // @synthesize wallpaperView=_wallpaperView;
@property(readonly, nonatomic) UIView *sceneView; // @synthesize sceneView=_sceneView;
@property(readonly, copy, nonatomic) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
@property(nonatomic, getter=isWallpaperEnabled) _Bool wallpaperEnabled; // @synthesize wallpaperEnabled=_wallpaperEnabled;
@property(nonatomic) _Bool allowSnapshots; // @synthesize allowSnapshots=_allowSnapshots;
@property(readonly, nonatomic) FBScene *scene; // @synthesize scene=_scene;
@property(readonly, nonatomic) long long layoutLevel; // @synthesize layoutLevel=_layoutLevel;
@property(readonly, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (id)_newWallpaperView;	// IMP=0x00000001001c4738
@property(readonly, nonatomic, getter=isReady) _Bool ready;
- (void)_setContinuousCornerRadius:(double)arg1;	// IMP=0x00000001001c4280
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x00000001001c3dd8
- (void)didMoveToWindow;	// IMP=0x00000001001c3c00
- (id)initWithScene:(id)arg1 layoutLevel:(long long)arg2;	// IMP=0x00000001001c396c
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001001c38fc
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001001c38a8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

