//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "PBAttentionMonitorStateMachine.h"

@interface HiliteSM : PBAttentionMonitorStateMachine
{
}

- (void)_establishVisualHiliteSetting:(_Bool)arg1;	// IMP=0x00000001001e1238
- (void)_enterOffStateAutomatically;	// IMP=0x00000001001e11f8
- (void)_enterOnStateAutomatically;	// IMP=0x00000001001e1178
- (_Bool)_canBeInOnStateAutomatically;	// IMP=0x00000001001e0b98

@end

