//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class BSProcessHandle, ITIdleTimerConfiguration, NSString;
@protocol BSInvalidatable;

@protocol ITIdleTimerStateServiceDelegate
- (id <BSInvalidatable>)acquireIdleTimerAssertionWithConfiguration:(ITIdleTimerConfiguration *)arg1 fromClient:(BSProcessHandle *)arg2 forReason:(NSString *)arg3;
@end

