//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep  6 2019 11:16:02).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSDictionary, PBAppInfoConfiguration, PBApplicationInfo, PBApplicationPlaceholder;

@protocol PBAppInfoStorePolicyProviding
- (PBAppInfoConfiguration *)configurationForProposedAppInfos:(NSDictionary *)arg1;
- (_Bool)isPlaceholderHidden:(PBApplicationPlaceholder *)arg1;
- (_Bool)isApplicationHidden:(PBApplicationInfo *)arg1;
- (_Bool)isPlaceholderEnabled:(PBApplicationPlaceholder *)arg1 reasons:(unsigned long long *)arg2;
- (_Bool)isApplicationEnabled:(PBApplicationInfo *)arg1 reasons:(unsigned long long *)arg2;
@end

