//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "PBSystemOverlayControllerDelegate-Protocol.h"
#import "PBSystemUIManaging-Protocol.h"

@class NSHashTable, NSMutableDictionary, NSString, PBSystemOverlayController;
@protocol OS_dispatch_source;

@interface PBBulletinManager : NSObject <PBSystemOverlayControllerDelegate, PBSystemUIManaging>
{
    NSMutableDictionary *_identifiersToBulletinInfos;	// 8 = 0x8
    PBSystemOverlayController *_overlayController;	// 16 = 0x10
    NSObject<OS_dispatch_source> *_bulletinDismissalTimer;	// 24 = 0x18
    NSHashTable *_observers;	// 32 = 0x20
}

+ (id)sharedInstance;	// IMP=0x0000000100061778
- (void).cxx_destruct;	// IMP=0x00000001000631ec
@property(readonly, nonatomic) NSHashTable *observers; // @synthesize observers=_observers;
@property(readonly, nonatomic) NSObject<OS_dispatch_source> *bulletinDismissalTimer; // @synthesize bulletinDismissalTimer=_bulletinDismissalTimer;
@property(readonly, nonatomic) PBSystemOverlayController *overlayController; // @synthesize overlayController=_overlayController;
@property(readonly, nonatomic) NSMutableDictionary *identifiersToBulletinInfos; // @synthesize identifiersToBulletinInfos=_identifiersToBulletinInfos;
- (void)_cancelTimer;	// IMP=0x000000010006312c
- (void)_startTimerForViewController:(id)arg1 withTimeout:(double)arg2;	// IMP=0x0000000100062ed8
- (void)dismissBulletinViewController:(id)arg1;	// IMP=0x0000000100062b78
- (void)updateBulletinViewControllerTimeout:(id)arg1 timeoutInSeconds:(double)arg2;	// IMP=0x0000000100062798
- (void)presentBulletinViewController:(id)arg1 withTimeoutInSeconds:(double)arg2;	// IMP=0x0000000100062418
- (void)overlayController:(id)arg1 didCancelSession:(id)arg2 withContext:(id)arg3;	// IMP=0x0000000100062310
- (void)overlayController:(id)arg1 didDismissSession:(id)arg2;	// IMP=0x000000010006223c
- (void)overlayController:(id)arg1 didPresentSession:(id)arg2;	// IMP=0x0000000100061f18
- (void)removeObserver:(id)arg1;	// IMP=0x0000000100061eb4
- (void)addObserver:(id)arg1;	// IMP=0x0000000100061e50
- (_Bool)dismissCurrentBulletin;	// IMP=0x0000000100061d00
- (void)activateCurrentBulletin;	// IMP=0x0000000100061bcc
- (_Bool)shouldActivateCurrentBulletinForAction:(unsigned long long)arg1;	// IMP=0x0000000100061a74
@property(readonly, nonatomic, getter=isPresenting) _Bool presenting;
- (id)init;	// IMP=0x0000000100061874

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

