//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSMutableDictionary, NSMutableSet, NSThread, PBBluetoothObserver;
@protocol OS_dispatch_queue;

@interface PBDataReportingService : NSObject
{
    NSMutableSet *_seenEDIDs;	// 8 = 0x8
    NSMutableDictionary *_toReportEDIDData;	// 16 = 0x10
    NSDate *_lastSentEDIDTimestamp;	// 24 = 0x18
    NSMutableDictionary *_keyTimingStarts;	// 32 = 0x20
    NSMutableDictionary *_keyTimingTotals;	// 40 = 0x28
    NSThread *_NANDReportingThread;	// 48 = 0x30
    NSObject<OS_dispatch_queue> *_serialQueue;	// 56 = 0x38
    double _lastSentProfileServiceTimestamp;	// 64 = 0x40
    PBBluetoothObserver *_bluetoothObserver;	// 72 = 0x48
}

+ (id)serviceLog;	// IMP=0x0000000100097810
+ (id)_sharedInstance;	// IMP=0x0000000100097404
+ (id)diagnosticLogPaths;	// IMP=0x000000010009739c
+ (void)stopTimingForKey:(id)arg1;	// IMP=0x0000000100096eb0
+ (void)startTimingForKey:(id)arg1;	// IMP=0x0000000100096b20
+ (void)incrementLongTVButtonPresses:(struct __IOHIDEvent *)arg1;	// IMP=0x0000000100096990
+ (void)incrementLongMenuButtonPresses:(struct __IOHIDEvent *)arg1;	// IMP=0x0000000100096794
+ (void)incrementEventCountForRemoteApp;	// IMP=0x000000010009676c
+ (void)incrementEventCountForGameController;	// IMP=0x0000000100096744
+ (void)incrementEventCountForBluetoothKeyboard;	// IMP=0x000000010009671c
+ (void)incrementEventCountForCEC;	// IMP=0x00000001000966f4
+ (void)incrementEventCountForIRRemote;	// IMP=0x00000001000966cc
+ (void)incrementEventCountForAppleBluetoothRemote;	// IMP=0x00000001000966a4
+ (void)incrementB239TVButtonPresses;	// IMP=0x000000010009667c
+ (void)incrementB239ButtonPresses;	// IMP=0x0000000100096654
+ (void)incrementScalarKey:(id)arg1;	// IMP=0x00000001000964dc
+ (void)noteApplicationExit;	// IMP=0x0000000100096470
+ (void)reportNow;	// IMP=0x0000000100096404
+ (void)startService;	// IMP=0x0000000100096344
- (void).cxx_destruct;	// IMP=0x00000001000a3ae4
@property(retain, nonatomic) PBBluetoothObserver *bluetoothObserver; // @synthesize bluetoothObserver=_bluetoothObserver;
@property(nonatomic) double lastSentProfileServiceTimestamp; // @synthesize lastSentProfileServiceTimestamp=_lastSentProfileServiceTimestamp;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *serialQueue; // @synthesize serialQueue=_serialQueue;
@property(retain, nonatomic) NSThread *NANDReportingThread; // @synthesize NANDReportingThread=_NANDReportingThread;
@property(retain, nonatomic) NSMutableDictionary *keyTimingTotals; // @synthesize keyTimingTotals=_keyTimingTotals;
@property(retain, nonatomic) NSMutableDictionary *keyTimingStarts; // @synthesize keyTimingStarts=_keyTimingStarts;
@property(retain, nonatomic) NSDate *lastSentEDIDTimestamp; // @synthesize lastSentEDIDTimestamp=_lastSentEDIDTimestamp;
@property(retain, nonatomic) NSMutableDictionary *toReportEDIDData; // @synthesize toReportEDIDData=_toReportEDIDData;
@property(retain, nonatomic) NSMutableSet *seenEDIDs; // @synthesize seenEDIDs=_seenEDIDs;
- (unsigned long long)_integer:(unsigned long long)arg1 quantizedBy:(unsigned long long)arg2;	// IMP=0x00000001000a3778
- (unsigned long long)_quantizedTimeForKey:(id)arg1;	// IMP=0x00000001000a35a4
- (void)_handleDeviceWillWakeNotification:(id)arg1;	// IMP=0x00000001000a325c
- (void)_handleDeviceWillSleepNotification:(id)arg1;	// IMP=0x00000001000a2f70
- (void)_reportCurrentPersistentDisplayMode;	// IMP=0x00000001000a2a8c
- (void)_reportRecoveryActions;	// IMP=0x00000001000a27b4
- (void)_threadReportNANDStatistics;	// IMP=0x00000001000a26d4
- (void)_reportNANDStatistics;	// IMP=0x00000001000a2678
- (void)_reportBluetoothData;	// IMP=0x00000001000a1a34
- (void)_sendToURL:(id)arg1 withSubtopic:(id)arg2 andParameters:(id)arg3;	// IMP=0x00000001000a1370
- (id)_reportingURLForTopic:(id)arg1;	// IMP=0x00000001000a0cd4
- (void)_sendCoreControlUsage;	// IMP=0x00000001000a0554
- (void)_sendEDIDURLRequest:(id)arg1;	// IMP=0x000000010009ffcc
- (void)_sendEDIDLogs;	// IMP=0x000000010009fc8c
- (void)_recordEDID;	// IMP=0x000000010009f718
- (void)_addExtendedCoreControlDataWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010009e92c
- (id)_dataReportingGUID;	// IMP=0x000000010009e81c
- (void)_handleDisplayModeDidChange;	// IMP=0x000000010009e6f0
- (void)tvs_bindDisplayModeBindingToObject:(id)arg1 withKeyPath:(id)arg2 options:(id)arg3;	// IMP=0x000000010009e550
- (id)DisplayModeBinding;	// IMP=0x000000010009e490
- (void)_showPushedIndicatorForCount:(unsigned long long)arg1;	// IMP=0x000000010009e188
- (void)_pushDiagnosticLogsAtPaths:(id)arg1;	// IMP=0x000000010009db00
- (id)_collectConfigLogs;	// IMP=0x000000010009d2b4
- (id)_collectBluetoothLogPaths;	// IMP=0x000000010009cdf4
- (id)_collectThermalLogPaths;	// IMP=0x000000010009cac0
- (id)_collectAirPlayLogPaths;	// IMP=0x000000010009bf90
- (id)_collectWiFiLogPaths;	// IMP=0x000000010009ae1c
- (id)_collectPlaybackLogPaths;	// IMP=0x000000010009aac0
- (id)_collectMediaserverLogPaths;	// IMP=0x0000000100099d30
- (id)_collectAVLog;	// IMP=0x00000001000995e4
- (id)_collectLogPaths;	// IMP=0x0000000100099188
- (void)_sendDiagnosticLogs:(id)arg1;	// IMP=0x0000000100098fe0
- (void)_reportDataNow;	// IMP=0x000000010009821c
- (void)_configureSleepWakeReporting;	// IMP=0x0000000100098114
- (void)_schedulePeriodicTrigger;	// IMP=0x0000000100097e38
- (void)_configureEDIDReporting;	// IMP=0x0000000100097d94
- (void)_configureMemoryPressureReporting;	// IMP=0x0000000100097c6c
- (void)_configureAggregateDataReporting;	// IMP=0x00000001000979f0
- (_Bool)_isDiagnosticsSubmissionAllowed;	// IMP=0x00000001000978e4
- (id)init;	// IMP=0x00000001000974d4

@end

