//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "PBSystemOverlayUIProvider-Protocol.h"

@class NSString;

@interface PBNowPlayingSystemOverlayUIProvider : NSObject <PBSystemOverlayUIProvider>
{
    NSString *_preferredBundleIdentifier;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010014ba5c
@property(copy, nonatomic) NSString *preferredBundleIdentifier; // @synthesize preferredBundleIdentifier=_preferredBundleIdentifier;
- (void)prepareUIForSystemOverlayPresentationWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010014b238

@end

