//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep  6 2019 11:16:02).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol PBPresentationElement <NSObject>
@property(readonly, nonatomic) _Bool shouldForwardHIDEvents;
@property(readonly, nonatomic) unsigned long long state;
@property(readonly, nonatomic) long long layoutLevel;
@property(readonly, nonatomic) NSString *identifier;
@end

