//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep  6 2019 11:16:02).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, PBSceneLayoutViewController, UIViewController;
@protocol PBSceneLayoutElement;

@protocol PBSceneLayoutViewControllerDisplayPublisherDelegate <NSObject>
- (void)sceneLayoutViewController:(PBSceneLayoutViewController *)arg1 didEndTransitionForTransitionElement:(UIViewController<PBSceneLayoutElement> *)arg2 forReason:(NSString *)arg3;
- (void)sceneLayoutViewController:(PBSceneLayoutViewController *)arg1 didStartTransitionForTransitionElement:(UIViewController<PBSceneLayoutElement> *)arg2 forReason:(NSString *)arg3;
- (void)sceneLayoutViewController:(PBSceneLayoutViewController *)arg1 didRemoveTransitionElement:(UIViewController<PBSceneLayoutElement> *)arg2;
- (void)sceneLayoutViewController:(PBSceneLayoutViewController *)arg1 didAddTransitionElement:(UIViewController<PBSceneLayoutElement> *)arg2;
@end

