//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class BKSApplicationStateMonitor, NSMutableDictionary;

@interface PBServiceProviderRegistry : NSObject
{
    BKSApplicationStateMonitor *_appStateMonitor;	// 8 = 0x8
    NSMutableDictionary *_clientEndpoints;	// 16 = 0x10
    NSMutableDictionary *_clientResponseBlocks;	// 24 = 0x18
}

+ (id)sharedInstance;	// IMP=0x000000010006e92c
- (void).cxx_destruct;	// IMP=0x00000001000709e0
- (void)endpointForIdentifier:(id)arg1 providerType:(id)arg2 responseBlock:(CDUnknownBlockType)arg3;	// IMP=0x000000010006fe1c
- (void)clearEndpointsForIdentifier:(id)arg1;	// IMP=0x000000010006f668
- (void)registerEndpoint:(id)arg1 forIdentifier:(id)arg2 providerType:(id)arg3;	// IMP=0x000000010006eef0
- (void)dealloc;	// IMP=0x000000010006ee88
- (id)init;	// IMP=0x000000010006e9fc

@end

