//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSXPCConnection, PGPictureInPictureApplication, PGPictureInPictureController, PGPictureInPictureViewController;

@protocol PGPictureInPictureControllerDelegate <NSObject>

@optional
- (_Bool)pictureInPictureController:(PGPictureInPictureController *)arg1 shouldDenyNewConnection:(NSXPCConnection *)arg2;
- (_Bool)pictureInPictureController:(PGPictureInPictureController *)arg1 shouldCancelPictureInPictureForApplication:(PGPictureInPictureApplication *)arg2 whenStartingPictureInPictureForApplication:(PGPictureInPictureApplication *)arg3;
- (void)pictureInPictureController:(PGPictureInPictureController *)arg1 didHidePictureInPictureViewController:(PGPictureInPictureViewController *)arg2;
- (void)pictureInPictureController:(PGPictureInPictureController *)arg1 willHidePictureInPictureViewController:(PGPictureInPictureViewController *)arg2;
- (void)pictureInPictureController:(PGPictureInPictureController *)arg1 willDestroyPictureInPictureViewController:(PGPictureInPictureViewController *)arg2;
- (void)pictureInPictureController:(PGPictureInPictureController *)arg1 didCreatePictureInPictureViewController:(PGPictureInPictureViewController *)arg2;
@end

