//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep  6 2019 11:16:02).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SplashBoard/XBApplicationSnapshot.h>

@interface XBApplicationSnapshot (PineBoardAdditions)
- (id)_extendedDataValueForKey:(id)arg1;	// IMP=0x00000001001717dc
- (void)_setExtendedDataValue:(id)arg1 forKey:(id)arg2;	// IMP=0x0000000100171660
@property(nonatomic, setter=pb_setIsTemplateImage:) _Bool pb_isTemplateImage;
@end

