/*
* This header is generated by classdump-dyld 1.0
* on Sunday, June 7, 2020 at 11:46:38 AM Mountain Standard Time
* Operating System: Version 13.4.5 (Build 17L562)
* Image Source: /usr/lib/libMemoryResourceException.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FPAuxDataType
@property (nonatomic,readonly) BOOL isContainer; 
@property (nonatomic,readonly) id jsonRepresentation; 
@required
-(BOOL)isContainer;
-(id)jsonRepresentation;

@end

