//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE;

@interface _TtC6Arcade21ArcadeWelcomeItemView : UIView
{
    MISSING_TYPE *headlineLabel;	// 8 = 0x8
    MISSING_TYPE *bodyLabel;	// 16 = 0x10
    MISSING_TYPE *artworkView;	// 24 = 0x18
    MISSING_TYPE *artwork;	// 32 = 0x20
    MISSING_TYPE *artworkLoader;	// 40 = 0x28
    MISSING_TYPE *shouldUpdateArtwork;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x00000001000e2ad8
- (struct JUMeasurements)measurementsWithFitting:(struct CGSize)arg1 in:(id)arg2;	// IMP=0x00000001000e28f0
- (void)layoutSubviews;	// IMP=0x00000001000e2778
@property(nonatomic) struct CGRect frame;
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001000e1fc4
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001000e1fa4

@end

