//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionReusableView.h>

@class MISSING_TYPE;

@interface _TtC6Arcade11DividerView : UICollectionReusableView
{
    MISSING_TYPE *separatorView;	// 8 = 0x8
    MISSING_TYPE *separatorInset;	// 16 = 0x10
    MISSING_TYPE *style;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x000000010018bbec
- (void)layoutSubviews;	// IMP=0x000000010018bb8c
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x000000010018b938
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010018b854
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010018b834

@end

