//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class MISSING_TYPE;

@interface _TtC6Arcade27ArcadeWelcomeViewController : UIViewController
{
    MISSING_TYPE *objectGraph;	// 8 = 0x8
    MISSING_TYPE *presenter;	// 16 = 0x10
    MISSING_TYPE *artworkLoader;	// 24 = 0x18
    MISSING_TYPE *lifecycleObserver;	// 32 = 0x20
    MISSING_TYPE *impressionsReporter;	// 72 = 0x48
    MISSING_TYPE *pageView;	// 80 = 0x50
    MISSING_TYPE *overlayView;	// 88 = 0x58
}

- (void).cxx_destruct;	// IMP=0x00000001001656c0
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x0000000100165658
- (void)appExitedWhileAppeared;	// IMP=0x000000010016530c
- (void)appEnteredWhileAppeared;	// IMP=0x0000000100165304
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x0000000100165270
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x0000000100165234
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x0000000100165018
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100164d74
- (void)viewDidLoad;	// IMP=0x0000000100164d48
- (void)viewWillLayoutSubviews;	// IMP=0x0000000100164bfc
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100164a98

@end

