//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE;

@interface _TtC6Arcade8PillView : UIView
{
    MISSING_TYPE *titleLabel;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010010ab20
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;	// IMP=0x000000010010aa38
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x000000010010a800
- (void)layoutSubviews;	// IMP=0x000000010010a7d4
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010010a550
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010010a530

@end

