//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE;

@interface _TtC6Arcade22ProductLockupBadgeView : UIView
{
    MISSING_TYPE *captionView;	// 8 = 0x8
    MISSING_TYPE *contentView;	// 16 = 0x10
    MISSING_TYPE *contentViewShouldBaselineAlignWithCaption;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00000001000e85b4
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001000e85ec
- (struct JUMeasurements)measurementsWithFitting:(struct CGSize)arg1 in:(id)arg2;	// IMP=0x00000001000e8538
- (void)layoutSubviews;	// IMP=0x00000001000e850c
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001000e8248

@end

