//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC6Arcade17RoundedCornerView.h"

@class MISSING_TYPE;

@interface _TtC6Arcade9VideoView : _TtC6Arcade17RoundedCornerView
{
    MISSING_TYPE *previewFrameArtwork;	// 56 = 0x38
    MISSING_TYPE *videoPlayer;	// 64 = 0x40
    MISSING_TYPE *playerViewController;	// 72 = 0x48
    MISSING_TYPE *templateMediaEvent;	// 80 = 0x50
    MISSING_TYPE *templateClickEvent;	// 104 = 0x68
    MISSING_TYPE *metricsPipeline;	// 128 = 0x80
    MISSING_TYPE *container;	// 224 = 0xe0
    MISSING_TYPE *videoUrl;	// 0 = 0x0
    MISSING_TYPE *interactionState;	// 0 = 0x0
    MISSING_TYPE *playbackId;	// 0 = 0x0
    MISSING_TYPE *delegate;	// 0 = 0x0
    MISSING_TYPE *isFullScreen;	// 0 = 0x0
    MISSING_TYPE *isTransitioningToFullscreen;	// 0 = 0x0
    MISSING_TYPE *configuration;	// 0 = 0x0
    MISSING_TYPE *fullScreenVideoController;	// 0 = 0x0
    MISSING_TYPE *fullScreenTransitionManager;	// 0 = 0x0
    MISSING_TYPE *wasAudioOnPreFullScreen;	// 0 = 0x0
    MISSING_TYPE *playWorkItem;	// 0 = 0x0
    MISSING_TYPE *releaseAssetsAtNextPauseState;	// 0 = 0x0
}

- (void).cxx_destruct;	// IMP=0x000000010010b244
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010010e214
- (void)willExitIdleMode;	// IMP=0x000000010010e1e8
- (void)willEnterIdleMode;	// IMP=0x000000010010e0c4
- (void)handleMediaServicesReset;	// IMP=0x000000010010e098
- (void)_setContinuousCornerRadius:(double)arg1;	// IMP=0x000000010010dd88
@property(nonatomic) double _continuousCornerRadius;
- (void)_setCornerRadius:(double)arg1;	// IMP=0x000000010010dcf4
@property(nonatomic) double _cornerRadius;
- (void)updateAudioSessionCategoryWithIsAudioOn:(_Bool)arg1;	// IMP=0x000000010010d8a4
- (void)layoutSubviews;	// IMP=0x000000010010c574
- (void)didChangeAutoPlayVideoSetting;	// IMP=0x000000010010c050
- (void)dealloc;	// IMP=0x000000010010b1a0
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010010afe0

@end

