//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSArray, NSString, TVSUITextAlertController;

@interface TVProfileMapSelectionViewController : UIViewController
{
    CDUnknownBlockType _selectedProfileIndex;	// 8 = 0x8
    NSString *_user;	// 16 = 0x10
    NSString *_app;	// 24 = 0x18
    NSArray *_profiles;	// 32 = 0x20
    TVSUITextAlertController *_alertController;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x0000000100003a20
@property(retain, nonatomic) TVSUITextAlertController *alertController; // @synthesize alertController=_alertController;
@property(retain, nonatomic) NSArray *profiles; // @synthesize profiles=_profiles;
@property(retain, nonatomic) NSString *app; // @synthesize app=_app;
@property(retain, nonatomic) NSString *user; // @synthesize user=_user;
@property(copy, nonatomic) CDUnknownBlockType selectedProfileIndex; // @synthesize selectedProfileIndex=_selectedProfileIndex;
- (id)preferredFocusEnvironments;	// IMP=0x0000000100003904
- (void)viewDidLoad;	// IMP=0x000000010000330c
- (id)initWithProfiles:(id)arg1 user:(id)arg2 app:(id)arg3;	// IMP=0x000000010000321c

@end

