//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SATVBaseStep-Protocol.h"

@class NSString, SATVLanguageController;
@protocol SATVStepDelegate;

@interface SATVLanguageStep : NSObject <SATVBaseStep>
{
    id <SATVStepDelegate> stepDelegate;	// 8 = 0x8
    SATVLanguageController *_languageController;	// 16 = 0x10
}

+ (id)stepPresentationRecordKey;	// IMP=0x0000000100008b54
+ (void)initialize;	// IMP=0x0000000100008af0
- (void).cxx_destruct;	// IMP=0x00000001000093f8
@property(retain, nonatomic) SATVLanguageController *languageController; // @synthesize languageController=_languageController;
@property(nonatomic) __weak id <SATVStepDelegate> stepDelegate; // @synthesize stepDelegate;
- (void)_sendStepCompletionNotificationWithLanguageCode:(id)arg1;	// IMP=0x0000000100009230
- (void)_presentLanguageController;	// IMP=0x00000001000090b8
- (void)_resetLanguageIfRequiredForContext:(id)arg1;	// IMP=0x000000010000900c
- (_Bool)_didLockdownSetLanguage;	// IMP=0x0000000100008fa0
- (void)autoAdvance;	// IMP=0x0000000100008f0c
- (_Bool)executeStepForContext:(id)arg1;	// IMP=0x0000000100008b60

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

