//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SATVPreviewTableViewController.h"

@class SATVActivityIndicatorViewController, UIView;

@interface SATVTableViewController : SATVPreviewTableViewController
{
    _Bool _horizontallyCentered;	// 8 = 0x8
    double _customContentTopInset;	// 16 = 0x10
    double _tableViewTopInset;	// 24 = 0x18
    double _maxBannerViewWidth;	// 32 = 0x20
    SATVActivityIndicatorViewController *_activityIndicatorViewController;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x00000001000523e0
@property(retain, nonatomic) SATVActivityIndicatorViewController *activityIndicatorViewController; // @synthesize activityIndicatorViewController=_activityIndicatorViewController;
@property(nonatomic) double maxBannerViewWidth; // @synthesize maxBannerViewWidth=_maxBannerViewWidth;
@property(nonatomic) double tableViewTopInset; // @synthesize tableViewTopInset=_tableViewTopInset;
@property(nonatomic) double customContentTopInset; // @synthesize customContentTopInset=_customContentTopInset;
@property(nonatomic, getter=isHorizontallyCentered) _Bool horizontallyCentered; // @synthesize horizontallyCentered=_horizontallyCentered;
- (void)_centerTableViewHorizontally;	// IMP=0x00000001000522a0
- (id)preferredFocusEnvironments;	// IMP=0x00000001000521ec
- (void)setTableViewWidth:(double)arg1;	// IMP=0x00000001000520c4
- (id)navigationController;	// IMP=0x0000000100052090
- (void)viewDidLayoutSubviews;	// IMP=0x0000000100051d6c
- (void)loadView;	// IMP=0x0000000100051be4
- (id)init;	// IMP=0x0000000100051b84

// Remaining properties
@property(retain, nonatomic) UIView *bannerView; // @dynamic bannerView;

@end

