//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep  6 2019 11:16:02).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, NSSet, SATVStepPresentationInfo, UIViewController;
@protocol SATVBaseStep;

@protocol SATVStepDelegate <NSObject>
- (void)finishBuddyFlowForStep:(id <SATVBaseStep>)arg1;
- (void)didPressMenuForStep:(id <SATVBaseStep>)arg1;
- (void)step:(id <SATVBaseStep>)arg1 didFailToFetchCloudConfigDetailsWithInfo:(NSDictionary *)arg2;
- (void)step:(id <SATVBaseStep>)arg1 triggerStatusDidChangeForTriggers:(NSSet *)arg2 shouldReset:(_Bool)arg3;
- (void)displayViewController:(UIViewController *)arg1 forStep:(id <SATVBaseStep>)arg2;
- (void)step:(id <SATVBaseStep>)arg1 didCompleteWithInfo:(SATVStepPresentationInfo *)arg2;
@end

