//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SATVAbstractFlow.h"

@class NSMutableArray, NSMutableDictionary, SATVNavigationController, TVSStateMachine;

@interface SATVUpdateFlow : SATVAbstractFlow
{
    SATVNavigationController *_navigationController;	// 8 = 0x8
    TVSStateMachine *_stateMachine;	// 16 = 0x10
    NSMutableArray *_stateBreadcrumbs;	// 24 = 0x18
    NSMutableArray *_skippedControllers;	// 32 = 0x20
    NSMutableDictionary *_stateBreadcrumbsToControllers;	// 40 = 0x28
    CDUnknownBlockType _completionBlock;	// 48 = 0x30
}

+ (void)initialize;	// IMP=0x0000000100009d14
- (void).cxx_destruct;	// IMP=0x000000010000d88c
@property(copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
@property(retain, nonatomic) NSMutableDictionary *stateBreadcrumbsToControllers; // @synthesize stateBreadcrumbsToControllers=_stateBreadcrumbsToControllers;
@property(retain, nonatomic) NSMutableArray *skippedControllers; // @synthesize skippedControllers=_skippedControllers;
@property(retain, nonatomic) NSMutableArray *stateBreadcrumbs; // @synthesize stateBreadcrumbs=_stateBreadcrumbs;
@property(retain, nonatomic) TVSStateMachine *stateMachine; // @synthesize stateMachine=_stateMachine;
@property(retain, nonatomic) SATVNavigationController *navigationController; // @synthesize navigationController=_navigationController;
- (id)_siriDiagnosticsController;	// IMP=0x000000010000d5d8
- (id)_displayRegionModeController;	// IMP=0x000000010000d4b0
- (id)_airplay2RoomPickerViewController;	// IMP=0x000000010000d2cc
- (id)_iCloudHomeScreenSyncController;	// IMP=0x000000010000d0fc
- (id)_videoSubscriberAccountAppController;	// IMP=0x000000010000cf18
- (id)_videoSubscriberAccountController;	// IMP=0x000000010000cd34
- (id)_privacyController;	// IMP=0x000000010000cb64
- (id)_whatsNewController;	// IMP=0x000000010000ca34
- (id)_accountUpdationViewController;	// IMP=0x000000010000c90c
- (id)_homeScreenSyncQueryController;	// IMP=0x000000010000c7e4
- (void)_popToControllerForCurrentState;	// IMP=0x000000010000c5dc
- (id)_existingControllerForCurrentState;	// IMP=0x000000010000c550
- (void)_pushControllerForCurrentState:(id)arg1 skipIfConfigured:(_Bool)arg2;	// IMP=0x000000010000c1e0
- (id)_previousState;	// IMP=0x000000010000c160
- (unsigned long long)_currentStateIndex;	// IMP=0x000000010000c0dc
- (id)_currentState;	// IMP=0x000000010000c088
- (void)_registerHandlersForStateMachine:(id)arg1;	// IMP=0x000000010000a06c
- (void)finish;	// IMP=0x000000010000a04c
- (void)startWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010000a008
- (id)initWithNavigationController:(id)arg1 overrideEntryFlowState:(id)arg2;	// IMP=0x0000000100009d74

@end

