//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SATVStepViewController.h"

#import "SATVConsentStep-Protocol.h"
#import "SATVConsentViewControllerDataSource-Protocol.h"
#import "SATVConsentViewControllerDelegate-Protocol.h"

@class NSString;

@interface SATVCloudConfigViewController : SATVStepViewController <SATVConsentViewControllerDelegate, SATVConsentViewControllerDataSource, SATVConsentStep>
{
    CDUnknownBlockType consentHandler;	// 8 = 0x8
}

+ (_Bool)isSupported;	// IMP=0x0000000100012e70
+ (id)stableKey;	// IMP=0x0000000100012e64
- (void).cxx_destruct;	// IMP=0x0000000100014cf0
@property(copy, nonatomic) CDUnknownBlockType consentHandler; // @synthesize consentHandler;
- (void)_obliterate;	// IMP=0x0000000100014c14
- (void)_leaveRemoteManagementAndErase;	// IMP=0x00000001000147d8
- (void)_showEraseDeviceAlert;	// IMP=0x000000010001457c
- (void)showLeaveRemoteManagementAlert;	// IMP=0x0000000100014320
- (void)_presentEraseAlertWithTitle:(id)arg1 message:(id)arg2 eraseHandler:(CDUnknownBlockType)arg3;	// IMP=0x00000001000140b4
- (void)_applyConfiguration:(_Bool)arg1;	// IMP=0x0000000100013ff0
- (id)_aboutText;	// IMP=0x0000000100013a40
- (_Bool)consentViewControllerCanSelectDissent:(id)arg1;	// IMP=0x00000001000139ec
- (void)consentViewControllerDidSelectAuxiliary:(id)arg1;	// IMP=0x00000001000139e0
- (void)consentViewControllerDidSelectFooter:(id)arg1;	// IMP=0x00000001000138bc
- (void)consentViewControllerDidSelectDissent:(id)arg1;	// IMP=0x0000000100013838
- (void)consentViewControllerDidSelectConsent:(id)arg1;	// IMP=0x00000001000137b4
- (id)auxiliaryButtonTextForConsentViewController:(id)arg1;	// IMP=0x00000001000136e0
- (id)footnoteTextForConsentViewController:(id)arg1;	// IMP=0x0000000100013594
- (id)footerButtonTextForConsentViewController:(id)arg1;	// IMP=0x0000000100013514
- (id)dissentButtonTextForConsentViewController:(id)arg1;	// IMP=0x00000001000133f0
- (id)consentButtonTextForConsentViewController:(id)arg1;	// IMP=0x00000001000132c8
- (id)subtitleTextForConsentViewController:(id)arg1;	// IMP=0x0000000100013110
- (id)titleTextForConsentViewController:(id)arg1;	// IMP=0x0000000100013090
- (void)autoAdvance;	// IMP=0x0000000100013080
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100012fec
- (void)viewDidLoad;	// IMP=0x0000000100012f0c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) _Bool isConfigured;
@property(copy, nonatomic) CDUnknownBlockType menuHandler;
@property(readonly) Class superclass;

@end

