//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSURLSessionDataDelegate-Protocol.h"
#import "NSURLSessionDelegate-Protocol.h"
#import "RemoteUIControllerDelegate-Protocol.h"

@class NSMutableArray, NSString, NSTimer, RUIPage, RemoteUIController, SATVActivationEngine, TVSStateMachine, UINavigationController;
@protocol SATVActivatorDelegate;

@interface SATVActivator : NSObject <NSURLSessionDelegate, NSURLSessionDataDelegate, RemoteUIControllerDelegate>
{
    SATVActivationEngine *_engine;	// 8 = 0x8
    RemoteUIController *_remoteUIController;	// 16 = 0x10
    NSMutableArray *_objectModels;	// 24 = 0x18
    RUIPage *_loadingPage;	// 32 = 0x20
    NSTimer *_ticketAcceptedTimer;	// 40 = 0x28
    id <SATVActivatorDelegate> _delegate;	// 48 = 0x30
    UINavigationController *_navigationController;	// 56 = 0x38
    TVSStateMachine *_stateMachine;	// 64 = 0x40
}

+ (_Bool)_hasDeKOTAFlagInActivationRecord;	// IMP=0x000000010004ee9c
+ (unsigned long long)_successTypeForActivationState:(id)arg1;	// IMP=0x000000010004a338
+ (_Bool)isBricked;	// IMP=0x000000010004a2f4
+ (_Bool)isDeviceFactoryActivated;	// IMP=0x000000010004a298
+ (_Bool)isDeviceActivated;	// IMP=0x000000010004a23c
+ (id)_activationState;	// IMP=0x000000010004a164
- (void).cxx_destruct;	// IMP=0x000000010004f13c
@property(retain, nonatomic) TVSStateMachine *stateMachine; // @synthesize stateMachine=_stateMachine;
@property(retain, nonatomic) UINavigationController *navigationController; // @synthesize navigationController=_navigationController;
@property(nonatomic) __weak id <SATVActivatorDelegate> delegate; // @synthesize delegate=_delegate;
- (void)remoteUIController:(id)arg1 didFinishLoadWithError:(id)arg2;	// IMP=0x000000010004ec80
- (void)remoteUIController:(id)arg1 didRemoveObjectModel:(id)arg2;	// IMP=0x000000010004eb24
- (void)remoteUIController:(id)arg1 willPresentObjectModel:(id)arg2 modally:(_Bool)arg3;	// IMP=0x000000010004ea18
- (void)remoteUIController:(id)arg1 didReceiveObjectModel:(id)arg2 actionSignal:(unsigned long long *)arg3;	// IMP=0x000000010004e71c
- (_Bool)remoteUIController:(id)arg1 shouldLoadRequest:(id)arg2 redirectResponse:(id)arg3;	// IMP=0x000000010004e37c
- (void)_dismissRemoteUI;	// IMP=0x000000010004e244
- (void)_loadCloudConfig;	// IMP=0x000000010004e024
- (void)_checkActivationFailIfBricked:(_Bool)arg1;	// IMP=0x000000010004de58
- (void)_activationStateChanged;	// IMP=0x000000010004dd08
- (void)_ticketAcceptedDidTimeout;	// IMP=0x000000010004dbe8
- (void)_clearTicketAcceptedTimer;	// IMP=0x000000010004db1c
- (void)_activationDidFailWithreason:(unsigned long long)arg1 error:(id)arg2;	// IMP=0x000000010004d8d4
- (void)_activationSucceeded;	// IMP=0x000000010004d5f8
- (void)_cleanup;	// IMP=0x000000010004d538
- (void)_handleActivationFailureWithError:(id)arg1 reason:(unsigned long long)arg2;	// IMP=0x000000010004d234
- (void)_handleActivationResponse:(id)arg1;	// IMP=0x000000010004cde4
- (void)_activateDeviceWithResponse:(id)arg1;	// IMP=0x000000010004c8f4
- (void)_startRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010004c490
- (void)_tryActivateWithOptions:(id)arg1 requestMutator:(CDUnknownBlockType)arg2;	// IMP=0x000000010004bf78
- (void)_startActivation;	// IMP=0x000000010004bb8c
- (void)_setTimeWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010004b79c
- (void)_configureStateMachine;	// IMP=0x000000010004a65c
- (void)start;	// IMP=0x000000010004a594
- (void)dealloc;	// IMP=0x000000010004a524
- (id)init;	// IMP=0x000000010004a3d8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

