//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, SATVButton, UIFocusGuide, UILabel, UITextField;

@interface SATVTextEntryView : UIView
{
    _Bool _touchInputEnabled;	// 8 = 0x8
    UILabel *_titleLabel;	// 16 = 0x10
    UILabel *_subtitleLabel;	// 24 = 0x18
    UITextField *_textField;	// 32 = 0x20
    SATVButton *_continueButton;	// 40 = 0x28
    UIView *_systemInputView;	// 48 = 0x30
    NSArray *_keyboardConstraints;	// 56 = 0x38
    UIFocusGuide *_gridFocusGuide;	// 64 = 0x40
}

- (void).cxx_destruct;	// IMP=0x000000010002248c
@property(retain, nonatomic) UIFocusGuide *gridFocusGuide; // @synthesize gridFocusGuide=_gridFocusGuide;
@property(nonatomic) _Bool touchInputEnabled; // @synthesize touchInputEnabled=_touchInputEnabled;
@property(retain, nonatomic) NSArray *keyboardConstraints; // @synthesize keyboardConstraints=_keyboardConstraints;
@property(readonly, nonatomic) UIView *systemInputView; // @synthesize systemInputView=_systemInputView;
@property(readonly, nonatomic) SATVButton *continueButton; // @synthesize continueButton=_continueButton;
@property(readonly, nonatomic) UITextField *textField; // @synthesize textField=_textField;
@property(readonly, nonatomic) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(readonly, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void)_setSystemInputView:(id)arg1;	// IMP=0x00000001000222c8
- (void)_gridAlignFrame:(struct CGRect *)arg1;	// IMP=0x0000000100022288
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;	// IMP=0x00000001000221a8
- (void)layoutSubviews;	// IMP=0x0000000100021cd8
- (void)updateConstraints;	// IMP=0x0000000100021950
- (void)setSystemInputView:(id)arg1 touchInputEnabled:(_Bool)arg2;	// IMP=0x0000000100021828
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010002140c

@end

