//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, NSString, SATVHighlightView, UIImageView, UILabel;
@protocol SATVPasscodeDigitViewDelegate;

@interface SATVPasscodeDigitView : UIView
{
    _Bool _showDigit;	// 8 = 0x8
    double _fontSize;	// 16 = 0x10
    unsigned long long _maxDigitValue;	// 24 = 0x18
    id <SATVPasscodeDigitViewDelegate> _delegate;	// 32 = 0x20
    UIView *_clippingView;	// 40 = 0x28
    UILabel *_label;	// 48 = 0x30
    SATVHighlightView *_highlight;	// 56 = 0x38
    UIImageView *_bulletView;	// 64 = 0x40
    UIImageView *_upArrowView;	// 72 = 0x48
    UIImageView *_downArrowView;	// 80 = 0x50
    NSArray *_recognizers;	// 88 = 0x58
}

- (void).cxx_destruct;	// IMP=0x0000000100038258
@property(retain, nonatomic) NSArray *recognizers; // @synthesize recognizers=_recognizers;
@property(retain, nonatomic) UIImageView *downArrowView; // @synthesize downArrowView=_downArrowView;
@property(retain, nonatomic) UIImageView *upArrowView; // @synthesize upArrowView=_upArrowView;
@property(retain, nonatomic) UIImageView *bulletView; // @synthesize bulletView=_bulletView;
@property(retain, nonatomic) SATVHighlightView *highlight; // @synthesize highlight=_highlight;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
@property(retain, nonatomic) UIView *clippingView; // @synthesize clippingView=_clippingView;
@property(nonatomic) __weak id <SATVPasscodeDigitViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool showDigit; // @synthesize showDigit=_showDigit;
@property(nonatomic) unsigned long long maxDigitValue; // @synthesize maxDigitValue=_maxDigitValue;
@property(nonatomic) double fontSize; // @synthesize fontSize=_fontSize;
- (id)hiddenDigitImage;	// IMP=0x0000000100037dec
- (id)arrowImage:(_Bool)arg1;	// IMP=0x0000000100037bdc
- (void)downGesture:(id)arg1;	// IMP=0x0000000100037a9c
- (void)upGesture:(id)arg1;	// IMP=0x0000000100037970
@property(copy, nonatomic) NSString *text;
- (void)setHighlightProgress:(double)arg1;	// IMP=0x0000000100037864
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;	// IMP=0x000000010003770c
- (_Bool)canBecomeFocused;	// IMP=0x0000000100037704
- (void)layoutSubviews;	// IMP=0x000000010003747c
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100036d80

@end

