//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableView.h>

@interface UITableView (TVKitCovfefe)
- (void)tv_updateSectionsWithChanges:(id)arg1;	// IMP=0x000000010003e08c
- (void)tv_updateItemsInSection:(unsigned long long)arg1 withChanges:(id)arg2;	// IMP=0x000000010003df64
- (void)tv_updateSectionsWithChange:(id)arg1;	// IMP=0x000000010003ddf0
- (void)tv_updateItemsInSection:(unsigned long long)arg1 withChange:(id)arg2;	// IMP=0x000000010003db90
- (id)tv_indexPathsForIndexSet:(id)arg1 withOptions:(unsigned long long)arg2 prefix:(id)arg3;	// IMP=0x000000010003da1c
@end

