//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;
@protocol OS_dispatch_source;

@interface _XBMemoryMonitor : NSObject
{
    NSMutableArray *_accessLock_memoryRecords;	// 8 = 0x8
    NSObject<OS_dispatch_source> *_memoryPressureSource;	// 16 = 0x10
    unsigned int _memoryPressureStatus;	// 24 = 0x18
    struct os_unfair_lock_s _accessLock;	// 28 = 0x1c
}

- (void).cxx_destruct;	// IMP=0x00000001000058c4
- (id)_getProcessMemoryUsed;	// IMP=0x0000000100005854
- (void)_publishMemoryReportForPressureType:(id)arg1;	// IMP=0x00000001000054c4
- (void)_setupProcessMemoryPressureMonitor;	// IMP=0x0000000100005398
- (void)recordMemoryForBundleID:(id)arg1;	// IMP=0x00000001000050e8
- (id)init;	// IMP=0x0000000100005060

@end

