//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "DMDEngineDatabaseOperation.h"

@class DMFUpdateDeclarationsRequest;

@interface DMDEngineUpdateDeclarationsOperation : DMDEngineDatabaseOperation
{
    DMFUpdateDeclarationsRequest *_request;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00000001000487f8
@property(retain, nonatomic) DMFUpdateDeclarationsRequest *request; // @synthesize request=_request;
- (void)performDatabaseModificationOperationWithManagedObjectContext:(id)arg1;	// IMP=0x0000000100047a94

@end

