//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "DMDTaskOperation.h"

@interface DMDFetchDeclarationsOperation : DMDTaskOperation
{
}

+ (_Bool)validateRequest:(id)arg1 error:(id *)arg2;	// IMP=0x000000010004e03c
+ (id)requiredEntitlements;	// IMP=0x000000010004de10
+ (id)whitelistedClassesForRequest;	// IMP=0x000000010004ddd4
- (void)runWithRequest:(id)arg1;	// IMP=0x000000010004de8c
- (_Bool)runOnMainThread;	// IMP=0x000000010004de84
- (unsigned long long)queueGroup;	// IMP=0x000000010004de7c

@end

