//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "DMDTaskOperation.h"

@interface DMDFetchProfilesOperation : DMDTaskOperation
{
}

+ (id)requiredEntitlements;	// IMP=0x000000010004f0c8
+ (id)whitelistedClassesForRequest;	// IMP=0x000000010004f000
- (id)_profileListWithFilterFlags:(int)arg1;	// IMP=0x000000010004f1cc
- (void)runWithRequest:(id)arg1;	// IMP=0x000000010004f134

@end

