//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "DMDTaskOperation.h"

@interface DMDFetchDeclarationCapabilitiesOperation : DMDTaskOperation
{
}

+ (_Bool)validateRequest:(id)arg1 error:(id *)arg2;	// IMP=0x000000010004dbc0
+ (id)requiredEntitlements;	// IMP=0x000000010004db54
+ (id)whitelistedClassesForRequest;	// IMP=0x000000010004db18
- (void)runWithRequest:(id)arg1;	// IMP=0x000000010004dbfc
- (unsigned long long)queueGroup;	// IMP=0x000000010004dbf4

@end

