//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "DMDAppController.h"

@class ASDJobManager, ASDSoftwareUpdatesStore, FBSDisplayLayoutMonitor, NSArray, NSMutableDictionary, NSString;

@interface DMDiphoneOSAppController : DMDAppController
{
    NSString *_singleAppModeBundleIndentifier;	// 8 = 0x8
    NSMutableDictionary *_bundleIDsToAssertions;	// 16 = 0x10
    FBSDisplayLayoutMonitor *_layoutMonitor;	// 24 = 0x18
    NSArray *__foregroundBundleIdentifiers;	// 32 = 0x20
}

+ (id)metadataPath;	// IMP=0x000000010001dc7c
+ (id)changeTypeAsString:(long long)arg1;	// IMP=0x000000010001d8f4
- (void).cxx_destruct;	// IMP=0x000000010001f224
@property(retain, nonatomic) NSArray *_foregroundBundleIdentifiers; // @synthesize _foregroundBundleIdentifiers=__foregroundBundleIdentifiers;
@property(retain, nonatomic) FBSDisplayLayoutMonitor *layoutMonitor; // @synthesize layoutMonitor=_layoutMonitor;
@property(retain, nonatomic) NSMutableDictionary *bundleIDsToAssertions; // @synthesize bundleIDsToAssertions=_bundleIDsToAssertions;
@property(copy, nonatomic) NSString *singleAppModeBundleIndentifier; // @synthesize singleAppModeBundleIndentifier=_singleAppModeBundleIndentifier;
- (void)_updateForegroundBundleIdentifiers;	// IMP=0x000000010001eef0
- (void)_getMetadataForBundleIdentifier:(id)arg1 storeItemIdentifier:(id)arg2 accountIdentifier:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x000000010001e8e4
- (void)_applyStoreDictionary:(id)arg1 toAppMetadata:(id)arg2;	// IMP=0x000000010001e714
- (id)_dataContainerPathForBundleIdentifier:(id)arg1;	// IMP=0x000000010001e690
- (id)_managedDefaultsForBundleIdentifier:(id)arg1;	// IMP=0x000000010001e630
- (_Bool)setFeedback:(id)arg1 forBundleIdentifier:(id)arg2 error:(id *)arg3;	// IMP=0x000000010001e4b4
- (id)feedbackForBundleIdentifier:(id)arg1;	// IMP=0x000000010001e3b0
- (_Bool)setConfiguration:(id)arg1 forBundleIdentifier:(id)arg2 error:(id *)arg3;	// IMP=0x000000010001e1e4
- (id)configurationForBundleIdentifier:(id)arg1;	// IMP=0x000000010001e188
- (void)getMetadataForNonEnterpriseAppRequest:(id)arg1 accountIdentifier:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010001ddf4
- (void)getBundleIdentifierForStoreItemIdentifier:(id)arg1 accountIdentifier:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010001dc90
- (_Bool)writeManagementInformationToDiskWithError:(id *)arg1;	// IMP=0x000000010001dbfc
- (void)installSystemAppWithBundleIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010001d964
- (void)sendAppRequestWithBundleIdentifier:(id)arg1 storeItemIdentifier:(id)arg2 accountIdentifier:(id)arg3 type:(long long)arg4 skipDownloads:(_Bool)arg5 completion:(CDUnknownBlockType)arg6;	// IMP=0x000000010001d4b8
- (void)promptUserToSignInWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010001d29c
@property(readonly, nonatomic) _Bool userIsSignedIn;
- (void)removeTerminationAssertionForBundleIdentifier:(id)arg1;	// IMP=0x000000010001d0e0
- (void)addTerminationAssertion:(id)arg1 forBundleIdentifier:(id)arg2;	// IMP=0x000000010001cf74
@property(readonly, copy, nonatomic) ASDSoftwareUpdatesStore *updatesStore;
@property(readonly, copy, nonatomic) ASDJobManager *jobManager;
- (id)foregroundBundleIdentifiers;	// IMP=0x000000010001ce50
- (id)initPrivate;	// IMP=0x000000010001ccdc
- (id)_allPropertyKeys;	// IMP=0x000000010001bb4c
- (void)handleFetchRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010001abfc
- (void)_downloadAppForRequest:(id)arg1 type:(long long)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010001ca88
- (void)_installUserAppForRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010001c824
- (void)_installDeviceLicensedAppForRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010001c72c
- (void)resumeAppInstallationWithBundleIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010001c1f8
- (void)startInstallingNonEnterpriseAppForRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010001bfdc
- (void)startInstallingEnterpriseAppWithManifestURL:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010001bd98
- (void)startRedeemingAppWithCode:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010001f2b4
- (void)_uninstallAppWithBundleIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010001fe50
- (void)startUninstallingAppWithBundleIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010001fb60
- (void)cancelAppInstallationWithBundleIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010001f6b0
- (void)_updateEndedForLifeCycle:(id)arg1;	// IMP=0x0000000100020668
- (void)_startUpdatingAppForRequest:(id)arg1 metadata:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00000001000202ec
- (void)didFinishUpdatingForLifeCycle:(id)arg1;	// IMP=0x0000000100020274
- (void)didFailUpdatingForLifeCycle:(id)arg1;	// IMP=0x00000001000201fc
- (void)didCancelUpdatingForLifeCycle:(id)arg1;	// IMP=0x0000000100020184
- (void)resumeAppUpdateWithBundleIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100020134
- (void)cancelAppUpdateWithBundleIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000200e4
- (void)startUpdatingAppForRequest:(id)arg1 metadata:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010001fe9c

@end

