//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class SWCDatabase, SWCDownloader;

@interface SWCDownloadScheduler : NSObject
{
    _Bool _enabled;	// 8 = 0x8
    SWCDownloader *_downloader;	// 16 = 0x10
    SWCDatabase *_database;	// 24 = 0x18
}

+ (id)new;	// IMP=0x0000000100020808
+ (id)_log;	// IMP=0x0000000100021420
- (void).cxx_destruct;	// IMP=0x00000001000207d8
@property(getter=isEnabled) _Bool enabled; // @synthesize enabled=_enabled;
@property(readonly) SWCDatabase *database; // @synthesize database=_database;
@property(readonly) SWCDownloader *downloader; // @synthesize downloader=_downloader;
- (void)update;	// IMP=0x0000000100020750
- (id)init;	// IMP=0x0000000100020720
- (id)initWithDownloader:(id)arg1 database:(id)arg2;	// IMP=0x0000000100020654
- (void)_performUpdatesWithTransaction:(id)arg1;	// IMP=0x0000000100020df4
- (id)_updateableEntries;	// IMP=0x0000000100020cb0
- (void)_performUpdateWithActivity:(id)arg1;	// IMP=0x00000001000209b8
- (void)_scheduleUpdateTimer;	// IMP=0x000000010002088c
- (id)_init;	// IMP=0x0000000100020814

@end

