//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NRBabelInstance.h"

@class NSString;

@interface NRBabelInstanceFake : NRBabelInstance
{
    NSString *_name;	// 96 = 0x60
}

- (void).cxx_destruct;	// IMP=0x000000010007a740
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
- (id)description;	// IMP=0x000000010007a6c8
- (void)setupAddress:(struct in6_addr *)arg1;	// IMP=0x000000010007a6c4
- (void)setupInterfaces;	// IMP=0x000000010007a6c0
- (id)initWithName:(id)arg1;	// IMP=0x000000010007a440

@end

