//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NEPolicySession, NSMutableDictionary;
@protocol OS_dispatch_queue;

@interface NRDPolicySessionManager : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    NEPolicySession *_policySession;	// 16 = 0x10
    NSMutableDictionary *_installedPolicyIdentifiers;	// 24 = 0x18
}

+ (id)copySharedManager;	// IMP=0x000000010009dbb0
- (void).cxx_destruct;	// IMP=0x000000010009db74
@property(retain, nonatomic) NSMutableDictionary *installedPolicyIdentifiers; // @synthesize installedPolicyIdentifiers=_installedPolicyIdentifiers;
@property(retain, nonatomic) NEPolicySession *policySession; // @synthesize policySession=_policySession;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void)applyPolicies;	// IMP=0x000000010009d9f8
- (void)removeAllPoliciesForIdentifier:(id)arg1;	// IMP=0x000000010009d6d8
- (void)removePolicyIDForIdentifier:(id)arg1 policyID:(id)arg2;	// IMP=0x000000010009d444
- (id)addPolicyForIdentifier:(id)arg1 policy:(id)arg2;	// IMP=0x000000010009d1c4
- (id)copyStatusString;	// IMP=0x000000010009d0ac
- (id)copyName;	// IMP=0x000000010009d0a0
- (id)initManager;	// IMP=0x000000010009cd8c

@end

