//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NRBabelInstance, NRBabelNeighbor, NRBabelPrefix, NRBabelRoute;
@protocol OS_dispatch_source;

@interface NRPendingOutgoingSeqnoReq : NSObject
{
    unsigned char _hopCount;	// 8 = 0x8
    _Bool _removedFromInstance;	// 9 = 0x9
    unsigned short _seqno;	// 10 = 0xa
    short _retriesLeft;	// 12 = 0xc
    NRBabelPrefix *_bPrefix;	// 16 = 0x10
    unsigned long long _routerID;	// 24 = 0x18
    NRBabelNeighbor *_target;	// 32 = 0x20
    NRBabelNeighbor *_originator;	// 40 = 0x28
    NRBabelRoute *_route;	// 48 = 0x30
    NSObject<OS_dispatch_source> *_retryTimer;	// 56 = 0x38
    NRBabelInstance *_instance;	// 64 = 0x40
}

- (void).cxx_destruct;	// IMP=0x00000001000732e8
@property(nonatomic) _Bool removedFromInstance; // @synthesize removedFromInstance=_removedFromInstance;
@property(nonatomic) __weak NRBabelInstance *instance; // @synthesize instance=_instance;
@property(nonatomic) unsigned char hopCount; // @synthesize hopCount=_hopCount;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *retryTimer; // @synthesize retryTimer=_retryTimer;
@property(nonatomic) short retriesLeft; // @synthesize retriesLeft=_retriesLeft;
@property(nonatomic) __weak NRBabelRoute *route; // @synthesize route=_route;
@property(retain, nonatomic) NRBabelNeighbor *originator; // @synthesize originator=_originator;
@property(retain, nonatomic) NRBabelNeighbor *target; // @synthesize target=_target;
@property(nonatomic) unsigned short seqno; // @synthesize seqno=_seqno;
@property(nonatomic) unsigned long long routerID; // @synthesize routerID=_routerID;
@property(retain, nonatomic) NRBabelPrefix *bPrefix; // @synthesize bPrefix=_bPrefix;
- (_Bool)cancelIfMatchesPrefix:(id)arg1 routerID:(unsigned long long)arg2 seqno:(unsigned short)arg3;	// IMP=0x0000000100073158
- (_Bool)cancelIfRouteUnselected;	// IMP=0x000000010007307c
- (void)dealloc;	// IMP=0x0000000100072ffc
- (void)cancelWithDelay:(_Bool)arg1;	// IMP=0x0000000100072ec8
- (void)cancelTimer;	// IMP=0x0000000100072e8c
- (void)start;	// IMP=0x0000000100072e00
- (id)description;	// IMP=0x0000000100072cf4
- (_Bool)isEqual:(id)arg1;	// IMP=0x0000000100072c24
- (_Bool)matchesPrefix:(id)arg1 routerID:(unsigned long long)arg2;	// IMP=0x0000000100072c00
- (id)initWithInstance:(id)arg1 prefix:(id)arg2 routerID:(unsigned long long)arg3;	// IMP=0x00000001000729b4
- (void)sendSeqnoReq;	// IMP=0x00000001000728bc
- (id)createTLV;	// IMP=0x000000010007280c

@end

