//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "RPClientProtocol-Protocol.h"

@class NSString, NSXPCConnection;

@interface RPClientProxy : NSObject <RPClientProtocol>
{
    NSXPCConnection *_connection;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0000000100014ae0
@property(retain, nonatomic) NSXPCConnection *connection; // @synthesize connection=_connection;
- (oneway void)recordingTimerDidUpdate:(id)arg1;	// IMP=0x00000001000149cc
- (oneway void)recordingDidPause;	// IMP=0x00000001000148e4
- (oneway void)recordingShouldResume;	// IMP=0x00000001000147fc
- (oneway void)recordingLockInterrupted:(id)arg1;	// IMP=0x00000001000146fc
- (oneway void)captureHandlerWithAudioSample:(id)arg1 bufferType:(long long)arg2;	// IMP=0x00000001000145a0
- (oneway void)captureHandlerWithSample:(id)arg1 timingData:(id)arg2;	// IMP=0x000000010001443c
- (oneway void)updateBroadcastURL:(id)arg1;	// IMP=0x000000010001433c
- (oneway void)updateBroadcastServiceInfo:(id)arg1;	// IMP=0x000000010001423c
- (oneway void)recordingDidStopWithError:(id)arg1 movieURL:(id)arg2;	// IMP=0x0000000100014118
- (oneway void)updateScreenRecordingStateWithCurrentState:(id)arg1;	// IMP=0x0000000100014018
- (void)dealloc;	// IMP=0x0000000100013f90
- (id)initWithConnection:(id)arg1;	// IMP=0x0000000100013f1c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

