//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;
@protocol OS_os_activity;

@interface GKActivity : NSObject
{
    unsigned int _mode;	// 8 = 0x8
    NSString *_name;	// 16 = 0x10
    NSObject<OS_os_activity> *_parent;	// 24 = 0x18
    NSObject<OS_os_activity> *_activity;	// 32 = 0x20
}

+ (void)execute:(CDUnknownBlockType)arg1;	// IMP=0x000000010005dc1c
+ (void)named:(id)arg1 execute:(CDUnknownBlockType)arg2;	// IMP=0x000000010005db6c
+ (id)named:(id)arg1;	// IMP=0x000000010005d618
+ (id)currentOrNew;	// IMP=0x000000010005d5b0
+ (id)detached;	// IMP=0x000000010005d548
+ (id)activity;	// IMP=0x000000010005d374
- (void).cxx_destruct;	// IMP=0x000000010005dd8c
@property(retain, nonatomic) NSObject<OS_os_activity> *activity; // @synthesize activity=_activity;
@property(retain, nonatomic) NSObject<OS_os_activity> *parent; // @synthesize parent=_parent;
@property(nonatomic) unsigned int mode; // @synthesize mode=_mode;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
- (void)execute:(CDUnknownBlockType)arg1;	// IMP=0x000000010005dc8c
- (void)named:(id)arg1 execute:(CDUnknownBlockType)arg2;	// IMP=0x000000010005dae0
- (id)named:(id)arg1;	// IMP=0x000000010005dab4
- (id)child;	// IMP=0x000000010005da2c
- (void)createActivity;	// IMP=0x000000010005d678
- (id)initWithName:(id)arg1 parent:(id)arg2 mode:(unsigned int)arg3;	// IMP=0x000000010005d2b4

@end

