//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GKChallengeBulletin.h"

@interface GKChallengeCompletedBulletin : GKChallengeBulletin
{
}

+ (void)loadBulletinsForPushNotification:(id)arg1 withHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001000295ec
- (void)handleAction:(id)arg1;	// IMP=0x000000010002ae8c
- (unsigned long long)launchEventType;	// IMP=0x000000010002ae84
- (void)assembleBulletin;	// IMP=0x000000010002aae4
- (void)notifyClient:(id)arg1;	// IMP=0x000000010002a980
- (void)dealloc;	// IMP=0x00000001000295b8
- (id)init;	// IMP=0x0000000100029584

@end

