//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GKTournamentService.h"

#import "GKTournamentServicePrivate-Protocol.h"

@class NSString;

@interface GKCloudTournamentServicePrivate : GKTournamentService <GKTournamentServicePrivate>
{
}

+ (unsigned long long)requiredEntitlements;	// IMP=0x00000001000b77d0
+ (Class)interfaceClass;	// IMP=0x00000001000b77c4
- (oneway void)removeCustomTournament:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x00000001000b7f08
- (oneway void)resetTournamentDataForTournamentsWithTournamentDefinitionIdentifier:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001000b7c1c
- (oneway void)loadTournamentWithID:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001000b77d8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

