//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "APSConnectionDelegate-Protocol.h"
#import "GKLockStatusObserver-Protocol.h"
#import "GKNATObserverDelegate-Protocol.h"
#import "GKPreferencesDelegate-Protocol.h"
#import "NSXPCListenerDelegate-Protocol.h"

@class APSConnection, GKApplicationStateMonitor, GKNATObserver, GKReachability, NSCountedSet, NSData, NSDate, NSMutableDictionary, NSString, NSXPCListener;
@protocol OS_dispatch_queue, OS_dispatch_semaphore;

@interface GKDataRequestManager : NSObject <NSXPCListenerDelegate, APSConnectionDelegate, GKNATObserverDelegate, GKPreferencesDelegate, GKLockStatusObserver>
{
    NSXPCListener *_publicListener;	// 8 = 0x8
    long long _currentEnvironment;	// 16 = 0x10
    int _natType;	// 24 = 0x18
    GKNATObserver *_natObserver;	// 32 = 0x20
    NSObject<OS_dispatch_semaphore> *_natSemaphore;	// 40 = 0x28
    NSObject<OS_dispatch_queue> *_natQueue;	// 48 = 0x30
    NSData *_pushToken;	// 56 = 0x38
    _Bool _receivesMemoryWarnings;	// 64 = 0x40
    long long _activePushEnvironment;	// 72 = 0x48
    NSDate *_nearbyQueryLastCheckDate;	// 80 = 0x50
    double _nearbyQueryAllowance;	// 88 = 0x58
    APSConnection *_apsConnection;	// 96 = 0x60
    APSConnection *_pushConnectionProd;	// 104 = 0x68
    APSConnection *_pushConnectionDev;	// 112 = 0x70
    NSMutableDictionary *_transactionBag;	// 120 = 0x78
    NSCountedSet *_transactionCounts;	// 128 = 0x80
    GKApplicationStateMonitor *_applicationStateMonitor;	// 136 = 0x88
    NSString *_authenticatingWithSettingsBundleID;	// 144 = 0x90
    GKReachability *_reachability;	// 152 = 0x98
}

+ (id)ratingsQueue;	// IMP=0x0000000100065f68
+ (id)statsQueue;	// IMP=0x0000000100065f00
+ (_Bool)allowSelfSignedCertForEnvironment:(long long)arg1;	// IMP=0x0000000100060758
+ (id)syncQueue;	// IMP=0x000000010005e048
+ (id)pushQueue;	// IMP=0x000000010005dfe0
+ (id)clientQueue;	// IMP=0x000000010005dfd4
+ (id)sharedManager;	// IMP=0x000000010005dfc8
@property(retain, nonatomic) GKReachability *reachability; // @synthesize reachability=_reachability;
@property(retain) NSString *authenticatingWithSettingsBundleID; // @synthesize authenticatingWithSettingsBundleID=_authenticatingWithSettingsBundleID;
@property(retain, nonatomic) GKApplicationStateMonitor *applicationStateMonitor; // @synthesize applicationStateMonitor=_applicationStateMonitor;
@property(retain, nonatomic) NSCountedSet *transactionCounts; // @synthesize transactionCounts=_transactionCounts;
@property(retain, nonatomic) NSMutableDictionary *transactionBag; // @synthesize transactionBag=_transactionBag;
@property(retain, nonatomic) APSConnection *pushConnectionDev; // @synthesize pushConnectionDev=_pushConnectionDev;
@property(retain, nonatomic) APSConnection *pushConnectionProd; // @synthesize pushConnectionProd=_pushConnectionProd;
@property(retain, nonatomic) APSConnection *apsConnection; // @synthesize apsConnection=_apsConnection;
@property double nearbyQueryAllowance; // @synthesize nearbyQueryAllowance=_nearbyQueryAllowance;
@property(retain) NSDate *nearbyQueryLastCheckDate; // @synthesize nearbyQueryLastCheckDate=_nearbyQueryLastCheckDate;
@property(nonatomic) _Bool receivesMemoryWarnings; // @synthesize receivesMemoryWarnings=_receivesMemoryWarnings;
@property(readonly) long long currentEnvironment; // @synthesize currentEnvironment=_currentEnvironment;
- (id)storeBag;	// IMP=0x0000000100065fd0
- (void)terminate;	// IMP=0x0000000100065cdc
- (void)beginTransaction:(id)arg1;	// IMP=0x0000000100065a88
- (void)endTransaction:(id)arg1;	// IMP=0x000000010006587c
- (void)processIncomingMessage:(id)arg1;	// IMP=0x0000000100065690
- (void)connection:(id)arg1 didReceiveIncomingMessage:(id)arg2;	// IMP=0x0000000100064cf0
- (void)connection:(id)arg1 didReceivePublicToken:(id)arg2;	// IMP=0x00000001000649ac
- (void)processIncomingiMessageInvite:(id)arg1;	// IMP=0x00000001000642e8
- (void)didReceiveIncomingIDSMessage:(id)arg1;	// IMP=0x00000001000642dc
- (void)gameCenterDidBecomeRestricted;	// IMP=0x0000000100064198
- (void)loadLocalizedGameNameForBundleID:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100063f58
- (void)appStateChanged:(id)arg1;	// IMP=0x0000000100063b28
- (void)terminateClient:(id)arg1;	// IMP=0x00000001000639dc
- (void)synchronizeBagWithPreferences;	// IMP=0x00000001000637f0
- (void)sendPushTokenForClient:(id)arg1;	// IMP=0x0000000100062e88
- (void)loadConnectivitySettingsAndStartNATObserver;	// IMP=0x0000000100062a90
- (void)_resetNATObserverWithSettings:(id)arg1;	// IMP=0x00000001000628d8
- (void)updateActivePushEnvironment;	// IMP=0x0000000100062570
- (void)_updatePushEnvironmentWithStoreBag:(id)arg1;	// IMP=0x00000001000622d8
@property(retain) NSData *pushToken; // @synthesize pushToken=_pushToken;
- (void)_setPushToken:(id)arg1;	// IMP=0x00000001000620b4
@property long long activePushEnvironment; // @synthesize activePushEnvironment=_activePushEnvironment;
- (void)_setActivePushEnvironment:(long long)arg1;	// IMP=0x0000000100061c30
- (void)getValidNATTypeWithHandler:(CDUnknownBlockType)arg1;	// IMP=0x0000000100061864
- (void)NATTypeDidChange:(int)arg1;	// IMP=0x0000000100061708
@property int natType; // @synthesize natType=_natType;
- (void)_waitForValidNATType;	// IMP=0x00000001000614c4
- (void)_setConnectivitySettings:(id)arg1;	// IMP=0x00000001000612c4
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x000000010006094c
- (void)resetEnvironment;	// IMP=0x000000010006077c
@property(readonly, nonatomic) long long preferredEnvironment;
- (void)dealloc;	// IMP=0x0000000100060604
- (void)clearPushEnvironment;	// IMP=0x000000010006051c
- (void)_clearPushConnections;	// IMP=0x0000000100060298
- (void)updateNotificationTopics;	// IMP=0x0000000100060230
- (void)setUpCloudKitNotificationTopics;	// IMP=0x000000010006011c
- (void)_updateNotificationTopics;	// IMP=0x000000010005f9e8
@property(readonly, nonatomic) APSConnection *activePushConnection; // @dynamic activePushConnection;
- (id)pushConnectionForEnvironment:(long long)arg1;	// IMP=0x000000010005f998
- (void)storeBagChanged:(id)arg1;	// IMP=0x000000010005f684
- (void)finishStartup;	// IMP=0x000000010005e4cc
- (void)clientProxy:(id)arg1 didRefreshContentsForDataType:(unsigned int)arg2 userInfo:(id)arg3;	// IMP=0x000000010005e4c8
- (void)reachabilityDidChange:(id)arg1;	// IMP=0x000000010005e478
- (void)iCloudAccountAvailabilityChanged:(id)arg1;	// IMP=0x000000010005e460
- (id)init;	// IMP=0x000000010005e21c
- (void)lockStatusDidChange;	// IMP=0x000000010005e218
- (void)performAsync:(CDUnknownBlockType)arg1;	// IMP=0x000000010005e1e8
- (void)performSync:(CDUnknownBlockType)arg1;	// IMP=0x000000010005e0b0
- (void)clearAllNearbyInvites;	// IMP=0x00000001000ac21c
- (void)handleNearbyInviteResponse:(id)arg1;	// IMP=0x00000001000abd74
- (void)nearbyInviteWasCancelled:(id)arg1;	// IMP=0x00000001000abac8
- (void)presentNearbyInvite:(id)arg1;	// IMP=0x00000001000ab16c
- (id)updateRequestWithPushToken:(id)arg1;	// IMP=0x0000000100190ba8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

