//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GKUIServiceClientProxy.h"

@interface GKExtensionClientProxy : GKUIServiceClientProxy
{
}

- (oneway void)setHostPID:(int)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x0000000100132e20
- (void)setExtensionProxy:(id)arg1 forBundleID:(id)arg2;	// IMP=0x0000000100132d48
- (_Bool)isUIService;	// IMP=0x0000000100132d40
- (_Bool)isExtension;	// IMP=0x0000000100132d38
- (void)dealloc;	// IMP=0x0000000100132cc0

@end

