//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GKSessionBulletin.h"

@class NSString;

@interface GKSessionMessageBulletin : GKSessionBulletin
{
    NSString *_sessionIdentifier;	// 104 = 0x68
}

+ (void)loadBulletinsForPushNotification:(id)arg1 withHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001000e17e0
+ (_Bool)supportsSecureCoding;	// IMP=0x00000001000e17d8
- (void).cxx_destruct;	// IMP=0x00000001000e34f4
@property(retain, nonatomic) NSString *sessionIdentifier; // @synthesize sessionIdentifier=_sessionIdentifier;
- (id)assembledMessage;	// IMP=0x00000001000e32d4
- (void)distributeData;	// IMP=0x00000001000e2dd8
- (id)aggregateDictionaryKey;	// IMP=0x00000001000e2dc8
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00000001000e2bec
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001000e29fc
- (id)initWithPushNotification:(id)arg1;	// IMP=0x00000001000e2818
- (void)loadSessionWithHandler:(CDUnknownBlockType)arg1;	// IMP=0x00000001000e2358

@end

