/*
* This header is generated by classdump-dyld 1.0
* on Sunday, June 7, 2020 at 11:12:14 AM Mountain Standard Time
* Operating System: Version 13.4.5 (Build 17L562)
* Image Source: /usr/lib/system/libdispatch.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libdispatch.dylib/OS_dispatch_queue_serial.h>
#import <libobjc.A.dylib/OS_dispatch_queue_mgr.h>

@protocol OS_dispatch_queue_mgr <OS_dispatch_queue_serial>
@end


@class NSString;

@interface OS_dispatch_queue_mgr : OS_dispatch_queue_serial <OS_dispatch_queue_mgr>

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)init;
@end

