//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "FilterTier.h"

@interface FilterRootTier : FilterTier
{
}

- (id)newChildInstance;	// IMP=0x0000000100005710
- (id)keyForChildren:(id)arg1;	// IMP=0x0000000100005700
- (id)init;	// IMP=0x000000010000567c

@end

