//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CKKSGroupOperation.h"

@class CKKSKeychainView;

__attribute__((visibility("hidden")))
@interface CKKSLocalSynchronizeOperation : CKKSGroupOperation
{
    int _restartCount;	// 12 = 0xc
    CKKSKeychainView *_ckks;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x000000010007d998
@property int restartCount; // @synthesize restartCount=_restartCount;
@property __weak CKKSKeychainView *ckks; // @synthesize ckks=_ckks;
- (void)groupStart;	// IMP=0x000000010007d848
- (id)initWithCKKSKeychainView:(id)arg1;	// IMP=0x000000010007d788
- (id)init;	// IMP=0x000000010007d770

@end

