//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CKKSCKRecordHolder.h"

@class CKKSTLKShare, NSData, NSString;

__attribute__((visibility("hidden")))
@interface CKKSTLKShareRecord : CKKSCKRecordHolder
{
    CKKSTLKShare *_share;	// 8 = 0x8
}

+ (id)fromDatabaseRow:(id)arg1;	// IMP=0x00000001001544f0
+ (id)sqlColumns;	// IMP=0x00000001001543f4
+ (id)sqlTable;	// IMP=0x00000001001543e8
+ (id)ckrecordPrefix;	// IMP=0x00000001001543dc
+ (id)tryFromDatabaseFromCKRecordID:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100153e98
+ (id)allInZone:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100153d74
+ (id)allForUUID:(id)arg1 zoneID:(id)arg2 error:(id *)arg3;	// IMP=0x0000000100153bc4
+ (id)allFor:(id)arg1 keyUUID:(id)arg2 zoneID:(id)arg3 error:(id *)arg4;	// IMP=0x00000001001539e0
+ (id)tryFromDatabase:(id)arg1 receiverPeerID:(id)arg2 senderPeerID:(id)arg3 zoneID:(id)arg4 error:(id *)arg5;	// IMP=0x0000000100153744
+ (id)fromDatabase:(id)arg1 receiverPeerID:(id)arg2 senderPeerID:(id)arg3 zoneID:(id)arg4 error:(id *)arg5;	// IMP=0x00000001001534a8
+ (id)share:(id)arg1 as:(id)arg2 to:(id)arg3 epoch:(long long)arg4 poisoned:(long long)arg5 error:(id *)arg6;	// IMP=0x0000000100153188
- (void).cxx_destruct;	// IMP=0x0000000100153174
@property(retain) CKKSTLKShare *share; // @synthesize share=_share;
- (id)sqlValues;	// IMP=0x0000000100152af4
- (id)whereClauseToFindSelf;	// IMP=0x000000010015290c
- (void)setFromCKRecord:(id)arg1;	// IMP=0x00000001001523e8
- (_Bool)matchesCKRecord:(id)arg1;	// IMP=0x000000010015229c
- (id)updateCKRecord:(id)arg1 zoneID:(id)arg2;	// IMP=0x0000000100151b2c
- (id)CKRecordName;	// IMP=0x00000001001519f4
- (id)recoverTLK:(id)arg1 trustedPeers:(id)arg2 error:(id *)arg3;	// IMP=0x00000001001518e8
- (_Bool)isEqual:(id)arg1;	// IMP=0x000000010015180c
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000100151768
- (_Bool)signatureVerifiesWithPeerSet:(id)arg1 error:(id *)arg2;	// IMP=0x00000001001516bc
- (_Bool)verifySignature:(id)arg1 verifyingPeer:(id)arg2 error:(id *)arg3;	// IMP=0x00000001001515ec
- (id)signRecord:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100151538
- (id)dataForSigning;	// IMP=0x00000001001514ac
- (id)unwrapUsing:(id)arg1 error:(id *)arg2;	// IMP=0x00000001001513f0
@property(readonly) NSData *signature;
@property(readonly) NSData *wrappedTLK;
@property(readonly) long long poisoned;
@property(readonly) long long epoch;
@property(readonly) NSString *senderPeerID;
@property(readonly) NSString *tlkUUID;
- (id)description;	// IMP=0x00000001001510d0
- (id)initForKey:(id)arg1 senderPeerID:(id)arg2 recieverPeerID:(id)arg3 receiverEncPublicKeySPKI:(id)arg4 curve:(long long)arg5 version:(unsigned long long)arg6 epoch:(long long)arg7 poisoned:(long long)arg8 wrappedKey:(id)arg9 signature:(id)arg10 zoneID:(id)arg11 encodedCKRecord:(id)arg12;	// IMP=0x0000000100150f54
- (id)init:(id)arg1 sender:(id)arg2 receiver:(id)arg3 curve:(long long)arg4 version:(unsigned long long)arg5 epoch:(long long)arg6 poisoned:(long long)arg7 zoneID:(id)arg8 encodedCKRecord:(id)arg9;	// IMP=0x0000000100150df0
- (id)init:(id)arg1 zoneID:(id)arg2 encodedCKRecord:(id)arg3;	// IMP=0x0000000100150d3c

@end

