//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface CKKSItemEncrypter : NSObject
{
}

+ (id)decryptDictionary:(id)arg1 key:(id)arg2 authenticatedData:(id)arg3 error:(id *)arg4;	// IMP=0x0000000100055a98
+ (id)encryptDictionary:(id)arg1 key:(id)arg2 authenticatedData:(id)arg3 error:(id *)arg4;	// IMP=0x000000010005593c
+ (id)decryptItemToDictionary:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100055718
+ (id)decryptItemToDictionaryVersion1or2:(id)arg1 error:(id *)arg2;	// IMP=0x00000001000554c4
+ (id)decryptItemToDictionaryVersionNone:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100055444
+ (id)encryptCKKSItem:(id)arg1 dataDictionary:(id)arg2 updatingCKKSItem:(id)arg3 parentkey:(id)arg4 error:(id *)arg5;	// IMP=0x0000000100054fac
+ (id)removePaddingFromData:(id)arg1;	// IMP=0x0000000100054f0c
+ (id)padData:(id)arg1 blockSize:(unsigned long long)arg2 additionalBlock:(_Bool)arg3;	// IMP=0x0000000100054da0

@end

