//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface SECC2MPInternalTestConfig : PBCodable <NSCopying>
{
    NSString *_key;	// 8 = 0x8
    NSString *_value;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00000001000b50a8
@property(retain, nonatomic) NSString *value; // @synthesize value=_value;
@property(retain, nonatomic) NSString *key; // @synthesize key=_key;
- (void)mergeFrom:(id)arg1;	// IMP=0x00000001000b4ff4
- (unsigned long long)hash;	// IMP=0x00000001000b4f98
- (_Bool)isEqual:(id)arg1;	// IMP=0x00000001000b4ec4
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001000b4e14
- (void)copyTo:(id)arg1;	// IMP=0x00000001000b4da8
- (void)writeTo:(id)arg1;	// IMP=0x00000001000b4d44
- (_Bool)readFrom:(id)arg1;	// IMP=0x00000001000b4d3c
- (id)dictionaryRepresentation;	// IMP=0x00000001000b4ca8
- (id)description;	// IMP=0x00000001000b4bf4
@property(readonly, nonatomic) _Bool hasValue;
@property(readonly, nonatomic) _Bool hasKey;

@end

