//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@class NSMutableArray, NSString;

__attribute__((visibility("hidden")))
@interface SECC2MPGenericEvent : PBCodable <NSCopying>
{
    unsigned long long _timestampEnd;	// 8 = 0x8
    unsigned long long _timestampStart;	// 16 = 0x10
    NSMutableArray *_metrics;	// 24 = 0x18
    NSString *_name;	// 32 = 0x20
    int _type;	// 40 = 0x28
    struct {
        unsigned int timestampEnd:1;
        unsigned int timestampStart:1;
        unsigned int type:1;
    } _has;	// 44 = 0x2c
}

+ (Class)metricType;	// IMP=0x0000000100090134
- (void).cxx_destruct;	// IMP=0x000000010008fcac
@property(retain, nonatomic) NSMutableArray *metrics; // @synthesize metrics=_metrics;
@property(nonatomic) unsigned long long timestampEnd; // @synthesize timestampEnd=_timestampEnd;
@property(nonatomic) unsigned long long timestampStart; // @synthesize timestampStart=_timestampStart;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
- (void)mergeFrom:(id)arg1;	// IMP=0x000000010008fa74
- (unsigned long long)hash;	// IMP=0x000000010008f99c
- (_Bool)isEqual:(id)arg1;	// IMP=0x000000010008f838
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x000000010008f624
- (void)copyTo:(id)arg1;	// IMP=0x000000010008f4bc
- (void)writeTo:(id)arg1;	// IMP=0x000000010008f30c
- (_Bool)readFrom:(id)arg1;	// IMP=0x000000010008f304
- (id)dictionaryRepresentation;	// IMP=0x000000010008ef94
- (id)description;	// IMP=0x000000010008eee0
- (id)metricAtIndex:(unsigned long long)arg1;	// IMP=0x000000010008eec8
- (unsigned long long)metricsCount;	// IMP=0x000000010008eeb0
- (void)addMetric:(id)arg1;	// IMP=0x000000010008ee3c
- (void)clearMetrics;	// IMP=0x000000010008ee24
@property(nonatomic) _Bool hasTimestampEnd;
@property(nonatomic) _Bool hasTimestampStart;
@property(readonly, nonatomic) _Bool hasName;
- (int)StringAsType:(id)arg1;	// IMP=0x000000010008eca4
- (id)typeAsString:(int)arg1;	// IMP=0x000000010008ec10
@property(nonatomic) _Bool hasType;
@property(nonatomic) int type; // @synthesize type=_type;

@end

