//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSURLSessionDelegate-Protocol.h"

@class NSMutableDictionary, NSString, NSURLSession;
@protocol OS_os_transaction;

__attribute__((visibility("hidden")))
@interface SecMetrics : NSObject <NSURLSessionDelegate>
{
    NSMutableDictionary *_taskMap;	// 8 = 0x8
    NSURLSession *_URLSession;	// 16 = 0x10
    NSObject<OS_os_transaction> *_transaction;	// 24 = 0x18
    long long _lostEvents;	// 32 = 0x20
}

+ (id)managerObject;	// IMP=0x000000010010bcd0
+ (id)c2MetricsEndpoint;	// IMP=0x000000010010bb3c
- (void).cxx_destruct;	// IMP=0x000000010010bb00
@property long long lostEvents; // @synthesize lostEvents=_lostEvents;
@property(retain) NSObject<OS_os_transaction> *transaction; // @synthesize transaction=_transaction;
@property(retain) NSURLSession *URLSession; // @synthesize URLSession=_URLSession;
@property(retain) NSMutableDictionary *taskMap; // @synthesize taskMap=_taskMap;
- (id)generateDeviceInfo;	// IMP=0x000000010010b8f4
- (id)gzipEncode:(id)arg1;	// IMP=0x000000010010b754
- (id)requestForGenericEvent:(id)arg1;	// IMP=0x000000010010b4e0
- (void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3;	// IMP=0x000000010010b088
- (id)getEvent:(id)arg1;	// IMP=0x000000010010af88
- (void)sendEvent:(id)arg1 pushTopic:(id)arg2;	// IMP=0x000000010010ac10
- (void)submitEvent:(id)arg1;	// IMP=0x000000010010abfc
- (id)init;	// IMP=0x000000010010aaf0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

