//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSSet;

__attribute__((visibility("hidden")))
@interface SOSAuthKitHelpers : NSObject
{
    NSSet *_midList;	// 8 = 0x8
    NSSet *_machineIDs;	// 16 = 0x10
    NSSet *_serialNumbers;	// 24 = 0x18
}

+ (_Bool)accountIsHSA2;	// IMP=0x00000001001aed68
+ (_Bool)updateMIDInPeerInfo:(id)arg1;	// IMP=0x00000001001aebd4
+ (_Bool)peerinfoHasMID:(id)arg1;	// IMP=0x00000001001aeb94
+ (void)activeMIDs:(CDUnknownBlockType)arg1;	// IMP=0x00000001001ae7ac
+ (id)machineID;	// IMP=0x00000001001ae510
- (void).cxx_destruct;	// IMP=0x00000001001ae4d4
@property(retain, nonatomic) NSSet *serialNumbers; // @synthesize serialNumbers=_serialNumbers;
@property(retain, nonatomic) NSSet *machineIDs; // @synthesize machineIDs=_machineIDs;
@property(retain, nonatomic) NSSet *midList; // @synthesize midList=_midList;
- (_Bool)isUseful;	// IMP=0x00000001001ae470
- (_Bool)serialIsValidInList:(id)arg1;	// IMP=0x00000001001ae454
- (_Bool)midIsValidInList:(id)arg1;	// IMP=0x00000001001ae438
- (id)initWithActiveMIDS:(id)arg1;	// IMP=0x00000001001ae164

@end

