//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface IMRuntimeUtil : NSObject
{
}

+ (double)associatedDoubleValueForKey:(id)arg1 onObject:(id)arg2 withDefault:(double)arg3;	// IMP=0x000000010019d938
+ (double)associatedDoubleValueForKey:(id)arg1 onObject:(id)arg2;	// IMP=0x000000010019d8d0
+ (float)associatedFloatValueForKey:(id)arg1 onObject:(id)arg2 withDefault:(float)arg3;	// IMP=0x000000010019d840
+ (float)associatedFloatValueForKey:(id)arg1 onObject:(id)arg2;	// IMP=0x000000010019d7d8
+ (long long)associatedIntValueForKey:(id)arg1 onObject:(id)arg2 withDefault:(long long)arg3;	// IMP=0x000000010019d750
+ (long long)associatedIntValueForKey:(id)arg1 onObject:(id)arg2;	// IMP=0x000000010019d6f0
+ (_Bool)associatedBoolValueForKey:(id)arg1 onObject:(id)arg2 withDefault:(_Bool)arg3;	// IMP=0x000000010019d668
+ (_Bool)associatedBoolValueForKey:(id)arg1 onObject:(id)arg2;	// IMP=0x000000010019d608
+ (id)associatedValueForKey:(id)arg1 onObject:(id)arg2 withDefault:(id)arg3;	// IMP=0x000000010019d570
+ (id)associatedValueForKey:(id)arg1 onObject:(id)arg2;	// IMP=0x000000010019d508
+ (void)associateDoubleValue:(double)arg1 forKey:(id)arg2 onObject:(id)arg3;	// IMP=0x000000010019d4a4
+ (void)associateDoubleValue:(double)arg1 forKey:(id)arg2 onObject:(id)arg3 withPolicy:(unsigned long long)arg4;	// IMP=0x000000010019d3ec
+ (void)associateFloatValue:(float)arg1 forKey:(id)arg2 onObject:(id)arg3;	// IMP=0x000000010019d388
+ (void)associateFloatValue:(float)arg1 forKey:(id)arg2 onObject:(id)arg3 withPolicy:(unsigned long long)arg4;	// IMP=0x000000010019d2d0
+ (void)associateIntValue:(long long)arg1 forKey:(id)arg2 onObject:(id)arg3;	// IMP=0x000000010019d274
+ (void)associateIntValue:(long long)arg1 forKey:(id)arg2 onObject:(id)arg3 withPolicy:(unsigned long long)arg4;	// IMP=0x000000010019d1bc
+ (void)associateBoolValue:(_Bool)arg1 forKey:(id)arg2 onObject:(id)arg3;	// IMP=0x000000010019d160
+ (void)associateBoolValue:(_Bool)arg1 forKey:(id)arg2 onObject:(id)arg3 withPolicy:(unsigned long long)arg4;	// IMP=0x000000010019d0a8
+ (void)associateValue:(id)arg1 forKey:(id)arg2 onObject:(id)arg3;	// IMP=0x000000010019d038
+ (void)associateValue:(id)arg1 forKey:(id)arg2 onObject:(id)arg3 withPolicy:(unsigned long long)arg4;	// IMP=0x000000010019cfd4
+ (void)swizzleClassMethod:(SEL)arg1 onClass:(Class)arg2 withReplacementBlock:(CDUnknownBlockType)arg3;	// IMP=0x000000010019cf60
+ (void)swizzleMethod:(SEL)arg1 onClass:(Class)arg2 withReplacementBlock:(CDUnknownBlockType)arg3;	// IMP=0x000000010019ced0

@end

