//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "UIApplicationDelegate-Protocol.h"

@class MTMediaRemoteController, NSString, UIViewController, UIWindow;
@protocol MTAppController;

@interface MTAppDelegate_Shared : NSObject <UIApplicationDelegate>
{
    UIWindow *_window;	// 8 = 0x8
    id <MTAppController> _appController;	// 16 = 0x10
    MTMediaRemoteController *_mediaRemoteController;	// 24 = 0x18
}

+ (id)createWindow;	// IMP=0x0000000100006fb4
- (void).cxx_destruct;	// IMP=0x00000001000072d4
@property(retain, nonatomic) MTMediaRemoteController *mediaRemoteController; // @synthesize mediaRemoteController=_mediaRemoteController;
@property(retain, nonatomic) id <MTAppController> appController; // @synthesize appController=_appController;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (_Bool)_mainWindowIsKey;	// IMP=0x0000000100007290
- (_Bool)_hasMainWindow;	// IMP=0x0000000100007288
- (void)_showMainWindow;	// IMP=0x0000000100007284
- (long long)_hostWindowLayoutDirection;	// IMP=0x000000010000727c
- (void)application:(id)arg1 didFailToContinueUserActivityWithType:(id)arg2 error:(id)arg3;	// IMP=0x0000000100007238
- (_Bool)application:(id)arg1 continueUserActivity:(id)arg2 restorationHandler:(CDUnknownBlockType)arg3;	// IMP=0x0000000100007144
- (_Bool)application:(id)arg1 willContinueUserActivityWithType:(id)arg2;	// IMP=0x00000001000070a4
- (void)application:(id)arg1 handleEventsForBackgroundURLSession:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0000000100006d1c
- (void)application:(id)arg1 performFetchWithCompletionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100006c4c
- (void)_performBackgroundLaunchFeedUpdatesForApplication:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001000068b8
@property(readonly, nonatomic) UIViewController *rootViewController;
- (void)didChangeStoreAccount:(id)arg1;	// IMP=0x0000000100006864
- (_Bool)openURL:(id)arg1;	// IMP=0x000000010000685c
- (void)storeAccountDidChange;	// IMP=0x0000000100006814
- (void)setupAfterBecomingActive;	// IMP=0x00000001000063e0
- (void)_setupPlayer;	// IMP=0x00000001000062c4
- (_Bool)_isApplicationActive;	// IMP=0x000000010000626c
- (void)application:(id)arg1 didChangeStatusBarOrientation:(long long)arg2;	// IMP=0x00000001000061e8
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2 fetchCompletionHandler:(CDUnknownBlockType)arg3;	// IMP=0x00000001000061d8
- (void)application:(id)arg1 didFailToRegisterForRemoteNotificationsWithError:(id)arg2;	// IMP=0x00000001000061d4
- (void)application:(id)arg1 didRegisterForRemoteNotificationsWithDeviceToken:(id)arg2;	// IMP=0x00000001000061d0
- (void)applicationDidBecomeActive:(id)arg1;	// IMP=0x0000000100006188
- (void)applicationWillEnterForeground:(id)arg1;	// IMP=0x000000010000614c
- (void)applicationDidEnterBackground:(id)arg1;	// IMP=0x0000000100006090
- (void)applicationWillResignActive:(id)arg1;	// IMP=0x0000000100006034
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;	// IMP=0x0000000100005e50
- (_Bool)application:(id)arg1 willFinishLaunchingWithOptions:(id)arg2;	// IMP=0x0000000100005c34
- (_Bool)application:(id)arg1 openURL:(id)arg2 options:(id)arg3;	// IMP=0x0000000100005764
- (void)dealloc;	// IMP=0x00000001000056ec

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

