//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MTPlayerManifest.h"

@class NSArray, NSMutableDictionary, NSString;

@interface MTBaseEpisodeListManifest : MTPlayerManifest
{
    _Bool _isInitialPrepare;	// 8 = 0x8
    NSString *_initialEpisodeUuid;	// 16 = 0x10
    NSMutableDictionary *_uuidToPlayerItemMap;	// 24 = 0x18
    NSArray *_episodeUuids;	// 32 = 0x20
}

+ (id)_mediaItemForEpisode:(id)arg1;	// IMP=0x0000000100144e28
+ (id)mediaItemForEpisodeWithUUID:(id)arg1;	// IMP=0x0000000100144994
+ (void)episodeUuidForActivity:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001001446ec
- (void).cxx_destruct;	// IMP=0x00000001001455b0
@property(retain, nonatomic) NSArray *episodeUuids; // @synthesize episodeUuids=_episodeUuids;
@property(nonatomic) _Bool isInitialPrepare; // @synthesize isInitialPrepare=_isInitialPrepare;
@property(retain, nonatomic) NSMutableDictionary *uuidToPlayerItemMap; // @synthesize uuidToPlayerItemMap=_uuidToPlayerItemMap;
@property(retain, nonatomic) NSString *initialEpisodeUuid; // @synthesize initialEpisodeUuid=_initialEpisodeUuid;
- (id)_predicateForFilteringExplicitEpisodes;	// IMP=0x0000000100144da4
- (_Bool)defaultToInitialIndexZero;	// IMP=0x0000000100144d9c
- (void)postManifestDidChangeNotification;	// IMP=0x0000000100144b9c
- (void)assertIndexInBounds:(unsigned long long)arg1;	// IMP=0x0000000100144b98
- (void)enumerateObjectsUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x00000001001445d8
- (id)objectAtIndex:(unsigned long long)arg1;	// IMP=0x00000001001443d0
- (unsigned long long)count;	// IMP=0x0000000100144384
- (id)init;	// IMP=0x0000000100144374
- (id)initWithInitialEpisodeUuid:(id)arg1;	// IMP=0x00000001001442b8

@end

