//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView;

@interface MTChevronView : UIView
{
    UIImageView *_imageView;	// 8 = 0x8
}

+ (id)chevronImage;	// IMP=0x000000010012671c
- (void).cxx_destruct;	// IMP=0x0000000100126a50
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x00000001001269c0
- (void)layoutSubviews;	// IMP=0x00000001001268a4
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100126788

@end

