//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

#import "UIScrollViewDelegate-Protocol.h"

@class MTActionButtonContainerView, MTCollectionView, MTUIFocusedTouchGestureRecognizer, NSString, UIButton, UIImageView, UIScrollView, UITapGestureRecognizer, UIView;
@protocol MTCollectionViewCellDelegate;

@interface MTCollectionViewCell : UICollectionViewCell <UIScrollViewDelegate>
{
    UIView *_contentView;	// 8 = 0x8
    UIScrollView *_scrollView;	// 16 = 0x10
    UIImageView *_editingControl;	// 24 = 0x18
    _Bool _editing;	// 32 = 0x20
    _Bool _userSwiping;	// 33 = 0x21
    _Bool _showsMoreButton;	// 34 = 0x22
    id <MTCollectionViewCellDelegate> _delegate;	// 40 = 0x28
    unsigned long long _swipeState;	// 48 = 0x30
    UITapGestureRecognizer *_tapGestureRecognizer;	// 56 = 0x38
    MTUIFocusedTouchGestureRecognizer *_dismissOnTouchRecognizer;	// 64 = 0x40
    MTActionButtonContainerView *_actionButtonsContainer;	// 72 = 0x48
    UIButton *_deleteButton;	// 80 = 0x50
    UIButton *_moreButton;	// 88 = 0x58
}

+ (id)_multiSelectNotSelectedImage;	// IMP=0x0000000100168d94
+ (id)_multiSelectCheckmarkImage;	// IMP=0x0000000100168cec
+ (Class)_contentViewClass;	// IMP=0x0000000100168ce0
+ (double)maximumContentWidth;	// IMP=0x0000000100168cd4
+ (double)estimatedHeight;	// IMP=0x0000000100168cc8
- (void).cxx_destruct;	// IMP=0x000000010016b204
@property(nonatomic) _Bool showsMoreButton; // @synthesize showsMoreButton=_showsMoreButton;
@property(nonatomic) _Bool userSwiping; // @synthesize userSwiping=_userSwiping;
@property(retain, nonatomic) UIButton *moreButton; // @synthesize moreButton=_moreButton;
@property(retain, nonatomic) UIButton *deleteButton; // @synthesize deleteButton=_deleteButton;
@property(retain, nonatomic) MTActionButtonContainerView *actionButtonsContainer; // @synthesize actionButtonsContainer=_actionButtonsContainer;
@property(retain, nonatomic) MTUIFocusedTouchGestureRecognizer *dismissOnTouchRecognizer; // @synthesize dismissOnTouchRecognizer=_dismissOnTouchRecognizer;
@property(retain, nonatomic) UITapGestureRecognizer *tapGestureRecognizer; // @synthesize tapGestureRecognizer=_tapGestureRecognizer;
@property(nonatomic) unsigned long long swipeState; // @synthesize swipeState=_swipeState;
@property(nonatomic) __weak id <MTCollectionViewCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic, getter=isEditing) _Bool editing; // @synthesize editing=_editing;
- (double)defaultActionButtonsXOriginForScrollFrame:(struct CGRect)arg1 andActionContainerSize:(struct CGSize)arg2;	// IMP=0x000000010016b0a4
- (void)scrollViewExposedDelete;	// IMP=0x000000010016b05c
- (void)scrollViewHidDelete;	// IMP=0x000000010016b014
- (double)targetXOffsetForExposedActions;	// IMP=0x000000010016aed4
- (void)hideActionsAnimated:(_Bool)arg1;	// IMP=0x000000010016ada8
- (void)exposeActionsAnimated:(_Bool)arg1;	// IMP=0x000000010016ad24
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;	// IMP=0x000000010016ac40
- (void)scrollViewDidScroll:(id)arg1;	// IMP=0x000000010016a8bc
- (void)removeDismissRecognizer;	// IMP=0x000000010016a774
- (void)addDismissRecognizer;	// IMP=0x000000010016a704
- (void)dismissDelete:(id)arg1;	// IMP=0x000000010016a6c8
- (void)setOpen:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x000000010016a664
- (void)applyLayoutAttributes:(id)arg1;	// IMP=0x000000010016a53c
- (void)moreButtonTapCancelled:(id)arg1;	// IMP=0x000000010016a4bc
- (void)moreButtonTapped:(id)arg1;	// IMP=0x000000010016a418
- (void)deleteButtonTapped:(id)arg1;	// IMP=0x000000010016a39c
- (id)mt_collectionView;	// IMP=0x0000000100169ee0
@property(readonly, nonatomic) MTCollectionView *collectionView;
- (id)contentView;	// IMP=0x0000000100169dc4
- (id)scrollView;	// IMP=0x0000000100169d58
- (void)layoutSubviews;	// IMP=0x00000001001699c0
- (struct CGRect)editingControlRectInBounds:(struct CGRect)arg1;	// IMP=0x000000010016982c
- (struct CGRect)contentRectForEditControlWidth:(double)arg1;	// IMP=0x0000000100169780
@property(readonly, nonatomic) _Bool exposedActions;
@property(nonatomic, getter=isSwipeEnabled) _Bool swipeEnabled;
- (void)setSelected:(_Bool)arg1;	// IMP=0x0000000100169420
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x000000010016930c
- (void)prepareForReuse;	// IMP=0x0000000100169260
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;	// IMP=0x0000000100169130
- (void)configureSubviews;	// IMP=0x0000000100168f00
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100168e94

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

