//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MTManagedObjectContext, NSHashTable, NSManagedObjectModel, NSMutableArray, NSPersistentStoreCoordinator;
@protocol MTCoreDataContainerConfigProvider, OS_dispatch_queue;

@interface MTCoreDataContainer : NSObject
{
    _Bool _valid;	// 8 = 0x8
    NSManagedObjectModel *_managedObjectModel;	// 16 = 0x10
    MTManagedObjectContext *_mainQueueContext;	// 24 = 0x18
    MTManagedObjectContext *_privateQueueContext;	// 32 = 0x20
    MTManagedObjectContext *_carPlayContext;	// 40 = 0x28
    MTManagedObjectContext *_storeContext;	// 48 = 0x30
    MTManagedObjectContext *_importContext;	// 56 = 0x38
    MTManagedObjectContext *_resetableImportContext;	// 64 = 0x40
    NSObject<OS_dispatch_queue> *_mergeQueue;	// 72 = 0x48
    NSObject<OS_dispatch_queue> *_mergeNotifierQueue;	// 80 = 0x50
    NSPersistentStoreCoordinator *_coordinator;	// 88 = 0x58
    id <MTCoreDataContainerConfigProvider> _config;	// 96 = 0x60
    NSHashTable *_notifiers;	// 104 = 0x68
    NSMutableArray *_entityNames;	// 112 = 0x70
}

- (void).cxx_destruct;	// IMP=0x000000010017a0e8
@property(nonatomic) _Bool valid; // @synthesize valid=_valid;
@property(retain, nonatomic) NSMutableArray *entityNames; // @synthesize entityNames=_entityNames;
@property(retain, nonatomic) NSHashTable *notifiers; // @synthesize notifiers=_notifiers;
@property(retain, nonatomic) id <MTCoreDataContainerConfigProvider> config; // @synthesize config=_config;
@property(retain, nonatomic) NSPersistentStoreCoordinator *coordinator; // @synthesize coordinator=_coordinator;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *mergeNotifierQueue; // @synthesize mergeNotifierQueue=_mergeNotifierQueue;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *mergeQueue; // @synthesize mergeQueue=_mergeQueue;
@property(retain, nonatomic) MTManagedObjectContext *resetableImportContext; // @synthesize resetableImportContext=_resetableImportContext;
@property(retain, nonatomic) MTManagedObjectContext *importContext; // @synthesize importContext=_importContext;
@property(retain, nonatomic) MTManagedObjectContext *storeContext; // @synthesize storeContext=_storeContext;
@property(retain, nonatomic) MTManagedObjectContext *carPlayContext; // @synthesize carPlayContext=_carPlayContext;
@property(retain, nonatomic) MTManagedObjectContext *privateQueueContext; // @synthesize privateQueueContext=_privateQueueContext;
@property(retain, nonatomic) MTManagedObjectContext *mainQueueContext; // @synthesize mainQueueContext=_mainQueueContext;
@property(retain, nonatomic) NSManagedObjectModel *managedObjectModel; // @synthesize managedObjectModel=_managedObjectModel;
- (void)destroy;	// IMP=0x0000000100179dd4
- (void)_tearDown:(_Bool)arg1;	// IMP=0x0000000100179a54
- (void)tearDownAsync:(_Bool)arg1;	// IMP=0x0000000100179944
- (void)_addChanges:(id)arg1 ofType:(int)arg2 toLibraryChanges:(id)arg3;	// IMP=0x000000010017974c
- (void)_notifyLibraryChanged:(id)arg1;	// IMP=0x0000000100179380
- (void)removeChangeNotifier:(id)arg1;	// IMP=0x00000001001792d0
- (void)addChangeNotifier:(id)arg1;	// IMP=0x0000000100179220
- (void)mergeFromContextDidSave:(id)arg1;	// IMP=0x0000000100178f80
- (id)persistentStoreUuid;	// IMP=0x0000000100178e18
- (id)persistentStoreCoordinator;	// IMP=0x0000000100178be8
- (id)_createManagedObjectContextWithName:(id)arg1 coordinator:(id)arg2 concurrencyType:(unsigned long long)arg3;	// IMP=0x0000000100178aa4
- (id)mainOrPrivateContext;	// IMP=0x0000000100178570
- (id)initWithConfig:(id)arg1;	// IMP=0x0000000100178304

@end

