//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSManagedObjectContextProvider-Protocol.h"

@class MTCoreDataContainer, NSString;
@protocol MTCoreDataContainerConfigProvider;

@interface MTDB : NSObject <NSManagedObjectContextProvider>
{
    MTCoreDataContainer *_coreDataContainer;	// 8 = 0x8
    id <MTCoreDataContainerConfigProvider> _config;	// 16 = 0x10
}

+ (void)setCoreDataVersion:(long long)arg1;	// IMP=0x00000001000e2cd0
+ (void)setLibraryDataVersion:(long long)arg1;	// IMP=0x00000001000e2c40
+ (long long)coreDataVersion;	// IMP=0x00000001000e2be4
+ (long long)libraryDataVersion;	// IMP=0x00000001000e2b88
+ (void)setCorrupt:(_Bool)arg1;	// IMP=0x00000001000e2b30
+ (_Bool)isCorrupt;	// IMP=0x00000001000e2ad4
+ (id)fetchManagedObjectModelFromDisk;	// IMP=0x00000001000e277c
+ (id)libraryWalPath;	// IMP=0x00000001000e2714
+ (id)libraryShmPath;	// IMP=0x00000001000e26ac
+ (id)libraryPath;	// IMP=0x00000001000e2644
+ (_Bool)canExtensionOpenDatabase;	// IMP=0x00000001000e24d4
+ (_Bool)createDatabaseIfNeeded;	// IMP=0x00000001000e2458
+ (void)setSharedInstance:(id)arg1;	// IMP=0x00000001000e220c
+ (id)sharedInstance;	// IMP=0x00000001000e2180
- (void).cxx_destruct;	// IMP=0x00000001000e2d88
@property(retain, nonatomic) id <MTCoreDataContainerConfigProvider> config; // @synthesize config=_config;
@property(retain, nonatomic) MTCoreDataContainer *coreDataContainer; // @synthesize coreDataContainer=_coreDataContainer;
- (id)managedObjectModel;	// IMP=0x00000001000e2a80
- (id)persistentStoreUuid;	// IMP=0x00000001000e2a2c
- (id)storeContext;	// IMP=0x00000001000e29d8
- (id)resetableImportContext;	// IMP=0x00000001000e2984
- (id)privateQueueContext;	// IMP=0x00000001000e2930
- (id)mainQueueContext;	// IMP=0x00000001000e28dc
- (id)mainOrPrivateContext;	// IMP=0x00000001000e2888
- (id)importContext;	// IMP=0x00000001000e2834
- (id)carPlayContext;	// IMP=0x00000001000e27e0
- (void)removeChangeNotifier:(id)arg1;	// IMP=0x00000001000e23ec
- (void)addChangeNotifier:(id)arg1;	// IMP=0x00000001000e2380
- (id)initWithCoreDataContainer:(id)arg1 config:(id)arg2;	// IMP=0x00000001000e22d8
- (id)init;	// IMP=0x00000001000e2254

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

