//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MTBaseProcessor.h"

@interface MTEpisodeDeletionProcessor : MTBaseProcessor
{
}

- (void)resultsChangedWithDeletedIds:(id)arg1 andInsertIds:(id)arg2;	// IMP=0x00000001000d616c
- (id)entityName;	// IMP=0x00000001000d615c
- (id)predicate;	// IMP=0x00000001000d60c4

@end

