//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MTTableViewCell.h"

@class UIActivityIndicatorView;

@interface MTLoadingCell : MTTableViewCell
{
    UIActivityIndicatorView *_activityIndicator;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x0000000100043500
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
- (void)layoutSubviews;	// IMP=0x000000010004338c
- (void)setupCell;	// IMP=0x000000010004327c

@end

