//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MTSetting.h"

@class MTOptionsDescription, NSString;

@interface MTOptionSetting : MTSetting
{
    MTOptionsDescription *_options;	// 8 = 0x8
    NSString *_headerTitle;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x000000010011995c
@property(copy, nonatomic) NSString *headerTitle; // @synthesize headerTitle=_headerTitle;
@property(retain, nonatomic) MTOptionsDescription *options; // @synthesize options=_options;
- (id)currentShortTitle;	// IMP=0x0000000100119858

@end

