//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MTListResultsController.h"

@interface MTPlayHistoryResultsController : MTListResultsController
{
    unsigned long long _newCount;	// 8 = 0x8
    unsigned long long _previousCount;	// 16 = 0x10
}

+ (id)fetchRequestForHistory;	// IMP=0x0000000100108f20
+ (id)predicateForHistory;	// IMP=0x0000000100108d20
+ (id)invertIndexPath:(id)arg1 withCount:(unsigned long long)arg2;	// IMP=0x0000000100108c68
+ (unsigned long long)invertIndex:(unsigned long long)arg1 withCount:(unsigned long long)arg2;	// IMP=0x0000000100108c5c
@property(nonatomic) unsigned long long previousCount; // @synthesize previousCount=_previousCount;
@property(nonatomic) unsigned long long newCount; // @synthesize newCount=_newCount;
- (void)reloadData;	// IMP=0x0000000100108b0c
- (void)generator:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(id)arg3 forChangeType:(unsigned long long)arg4 newIndexPath:(id)arg5;	// IMP=0x00000001001089b0
- (void)setObjects:(id)arg1;	// IMP=0x00000001001088e4
- (id)indexPathForObject:(id)arg1;	// IMP=0x0000000100108844
- (id)objectAtIndexPath:(id)arg1;	// IMP=0x000000010010878c
- (void)currentItemDidChange;	// IMP=0x0000000100108724
- (id)init;	// IMP=0x00000001001085a8

@end

