//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MTSubscribeUtil : NSObject
{
}

+ (id)identifierForDictionary:(id)arg1;	// IMP=0x00000001000164e0
+ (_Bool)isSubscribedToPodcastWithStorePlatformDictionary:(id)arg1;	// IMP=0x0000000100016274
+ (void)unsubscribeToPodcastWithStorePlatformDictionary:(id)arg1;	// IMP=0x0000000100016038
+ (void)subscribeToPodcastWithStorePlatformDictionary:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100015a00
+ (void)subscribeToPodcastWithFeedUrl:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010001548c

@end

