//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MTSpecialIndexPathTableViewController.h"

@class NSMutableSet, NSString;
@protocol MTPlaylistSelectPodcastListViewControllerSaveDelegate;

@interface MTTVStationSelectPodcastsListViewController : MTSpecialIndexPathTableViewController
{
    _Bool _allPodcastsSelected;	// 8 = 0x8
    NSString *_playlistName;	// 16 = 0x10
    NSMutableSet *_podcastUuids;	// 24 = 0x18
    NSString *_playlistUuid;	// 32 = 0x20
    id <MTPlaylistSelectPodcastListViewControllerSaveDelegate> _saveDelegate;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x0000000100054b00
@property(nonatomic) __weak id <MTPlaylistSelectPodcastListViewControllerSaveDelegate> saveDelegate; // @synthesize saveDelegate=_saveDelegate;
@property(retain, nonatomic) NSString *playlistUuid; // @synthesize playlistUuid=_playlistUuid;
@property(nonatomic) _Bool allPodcastsSelected; // @synthesize allPodcastsSelected=_allPodcastsSelected;
@property(retain, nonatomic) NSMutableSet *podcastUuids; // @synthesize podcastUuids=_podcastUuids;
@property(retain, nonatomic) NSString *playlistName; // @synthesize playlistName=_playlistName;
- (void)main_tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x00000001000548f4
- (_Bool)main_tableView:(id)arg1 canFocusRowAtIndexPath:(id)arg2;	// IMP=0x00000001000548d4
- (double)main_tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;	// IMP=0x00000001000548c8
- (void)main_configureCell:(id)arg1 forRowAtIndexPath:(id)arg2;	// IMP=0x0000000100054754
- (id)main_tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x00000001000546f8
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;	// IMP=0x00000001000546f0
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;	// IMP=0x0000000100054680
- (void)save;	// IMP=0x0000000100054480
- (_Bool)toggleUuid:(id)arg1;	// IMP=0x000000010005436c
- (void)toggleAllPodcastsSelected;	// IMP=0x0000000100054304
- (void)setupIncludeAllCell;	// IMP=0x0000000100053f64
- (void)setupFRC;	// IMP=0x0000000100053d94
- (void)viewWillLayoutSubviews;	// IMP=0x0000000100053adc
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x0000000100053a8c
- (void)viewDidLoad;	// IMP=0x00000001000539a4

@end

