//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MTFetchedCollectionWithSectionsViewController.h"

#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"

@class MTTVContentUnavailableViewController, NSIndexPath, NSString, UILongPressGestureRecognizer, UITapGestureRecognizer;

@interface MTTVFetchedCollectionWithSectionsViewController : MTFetchedCollectionWithSectionsViewController <UICollectionViewDataSource, UICollectionViewDelegate, UICollectionViewDelegateFlowLayout>
{
    MTTVContentUnavailableViewController *_emptyContentViewController;	// 8 = 0x8
    long long _listState;	// 16 = 0x10
    NSIndexPath *_indexPathForAvoidingSectionHeader;	// 24 = 0x18
    UITapGestureRecognizer *_playButtonRecognizer;	// 32 = 0x20
    UILongPressGestureRecognizer *_longPressRecognizer;	// 40 = 0x28
    NSString *_titleToRestore;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x00000001000a14a4
@property(retain, nonatomic) NSString *titleToRestore; // @synthesize titleToRestore=_titleToRestore;
@property(retain, nonatomic) UILongPressGestureRecognizer *longPressRecognizer; // @synthesize longPressRecognizer=_longPressRecognizer;
@property(retain, nonatomic) UITapGestureRecognizer *playButtonRecognizer; // @synthesize playButtonRecognizer=_playButtonRecognizer;
@property(retain, nonatomic) NSIndexPath *indexPathForAvoidingSectionHeader; // @synthesize indexPathForAvoidingSectionHeader=_indexPathForAvoidingSectionHeader;
@property(readonly, nonatomic) long long listState; // @synthesize listState=_listState;
@property(retain, nonatomic) MTTVContentUnavailableViewController *emptyContentViewController; // @synthesize emptyContentViewController=_emptyContentViewController;
- (id)preferredFocusedView;	// IMP=0x00000001000a12e0
- (void)updateEmptyView;	// IMP=0x00000001000a10d8
- (void)tearDownEmptyContentViewController;	// IMP=0x00000001000a0fcc
- (void)standupEmptyContentViewController;	// IMP=0x00000001000a0e0c
- (void)setListState:(long long)arg1;	// IMP=0x00000001000a0d40
- (void)updateListState;	// IMP=0x00000001000a0ce8
- (void)collectionView:(id)arg1 didLongPressItemAtIndexPath:(id)arg2;	// IMP=0x00000001000a0ce4
- (void)playItemAtIndexPath:(id)arg1;	// IMP=0x00000001000a0c98
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;	// IMP=0x00000001000a0ba8
- (void)collectionView:(id)arg1 didEndDisplayingSupplementaryView:(id)arg2 forElementOfKind:(id)arg3 atIndexPath:(id)arg4;	// IMP=0x00000001000a0ba4
- (void)collectionView:(id)arg1 willDisplaySupplementaryView:(id)arg2 forElementKind:(id)arg3 atIndexPath:(id)arg4;	// IMP=0x00000001000a0a6c
- (_Bool)collectionView:(id)arg1 canFocusItemAtIndexPath:(id)arg2;	// IMP=0x00000001000a0a64
- (void)collectionView:(id)arg1 didUpdateFocusInContext:(id)arg2 withAnimationCoordinator:(id)arg3;	// IMP=0x00000001000a09fc
- (void)setAvoidenceEnabled:(_Bool)arg1 forSectionHeaderView:(id)arg2;	// IMP=0x00000001000a09ec
- (void)setAvoidenceEnabled:(_Bool)arg1 forSectionHeaderAtIndexPath:(id)arg2;	// IMP=0x00000001000a0948
- (void)updateAvoidingSectingHeader:(id)arg1 forFocusedIndexPath:(id)arg2;	// IMP=0x00000001000a0480
- (void)updateAvoidingSectingHeaderForFocusedIndexPath:(id)arg1;	// IMP=0x00000001000a0390
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;	// IMP=0x00000001000a02a4
- (void)collectionView:(id)arg1 configureReusableView:(id)arg2 ofSupplementaryElementOfKind:(id)arg3 forItemAtIndexPath:(id)arg4;	// IMP=0x00000001000a0184
- (void)collectionView:(id)arg1 configureCell:(id)arg2 withObject:(id)arg3 atIndexPath:(id)arg4;	// IMP=0x00000001000a0180
- (void)registerCollectionViewClasses;	// IMP=0x00000001000a0088
- (void)controllerDidChangeContent:(id)arg1;	// IMP=0x00000001000a0038
- (void)longPressAction:(id)arg1;	// IMP=0x000000010009ff6c
- (void)playPauseButtonAction:(id)arg1;	// IMP=0x000000010009fe1c
- (void)willTransitionToTraitCollection:(id)arg1 withTransitionCoordinator:(id)arg2;	// IMP=0x000000010009fd44
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;	// IMP=0x000000010009fc70
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x000000010009fb54
- (void)viewDidLoad;	// IMP=0x000000010009f8a0
- (id)initWithCollectionViewLayout:(id)arg1 compositeFetchedResultsController:(id)arg2;	// IMP=0x000000010009f81c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

