//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MZKeyValueStoreSerializer, MZKeyValueStoreTransaction, NSString;
@protocol MZKeyValueStoreOperationDelegate;

@interface MZKeyValueStoreRequest : NSObject
{
    NSString *_domain;	// 8 = 0x8
    MZKeyValueStoreTransaction *_transaction;	// 16 = 0x10
    NSString *_DSID;	// 24 = 0x18
    _Bool _shouldAuthenticate;	// 32 = 0x20
    id <MZKeyValueStoreOperationDelegate> _delegate;	// 40 = 0x28
    MZKeyValueStoreSerializer *_serializer;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x0000000100078258
@property(retain, nonatomic) MZKeyValueStoreSerializer *serializer; // @synthesize serializer=_serializer;
@property(nonatomic) _Bool shouldAuthenticate; // @synthesize shouldAuthenticate=_shouldAuthenticate;
@property(nonatomic) __weak id <MZKeyValueStoreOperationDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSString *DSID; // @synthesize DSID=_DSID;
@property(retain, nonatomic) MZKeyValueStoreTransaction *transaction; // @synthesize transaction=_transaction;
@property(copy, nonatomic) NSString *domain; // @synthesize domain=_domain;
- (void)scheduleStoreURLRequest:(id)arg1;	// IMP=0x000000010007807c
- (void)postData:(id)arg1;	// IMP=0x0000000100077cc4
- (void)start;	// IMP=0x0000000100077c50
- (id)initWithTransaction:(id)arg1;	// IMP=0x0000000100077bd8

@end

