//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep  6 2019 11:16:02).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreData/NSManagedObjectContext.h>

@class NSString;

@interface NSManagedObjectContext (MTLibraryAdditions)
- (id)episodeIdsForPodcastUuid:(id)arg1 sortOptions:(int)arg2;	// IMP=0x000000010000c964
- (id)colorThemeForUuid:(id)arg1;	// IMP=0x0000000100030ba4
- (id)themeForUuid:(id)arg1;	// IMP=0x0000000100030994
- (id)podcastPlaylistSettingsForUuid:(id)arg1;	// IMP=0x0000000100045518
- (id)existingPodcastPlaylistSettingsWithID:(id)arg1;	// IMP=0x0000000100045448
- (id)playlistForUuid:(id)arg1;	// IMP=0x00000001000cf414
- (id)playlistIdWithUuid:(id)arg1;	// IMP=0x00000001000cf3fc
- (void)deletePlaylist:(id)arg1;	// IMP=0x00000001000cf2ac
- (id)existingPlaylistWithID:(id)arg1;	// IMP=0x00000001000cf0bc
- (id)playlistWithID:(id)arg1;	// IMP=0x00000001000cf0b0
- (_Bool)deleteAllUPPMetadata;	// IMP=0x00000001000f179c
- (id)uppMetadataForMetadataIdentifiers:(id)arg1;	// IMP=0x00000001000f16c8
- (id)uppMetadataForMetadataIdentifier:(id)arg1;	// IMP=0x00000001000f1600
- (id)cacheKeyForUuid:(id)arg1 entityName:(id)arg2;	// IMP=0x0000000100134790
- (id)cacheKeyForObject:(id)arg1;	// IMP=0x00000001001346bc
- (id)uuidCache;	// IMP=0x00000001001345b0
- (id)titlesOfObjectsInEntity:(id)arg1 predicate:(id)arg2;	// IMP=0x00000001001342bc
- (unsigned long long)countOfObjectsInEntity:(id)arg1 predicate:(id)arg2;	// IMP=0x000000010013413c
- (id)objectDictionaryForUuid:(id)arg1 entityName:(id)arg2 byAddingComputedProperties:(id)arg3 toFetchedObjectDictionary:(id)arg4;	// IMP=0x0000000100133d2c
- (id)valueForProperty:(id)arg1 objectUuid:(id)arg2 entityName:(id)arg3;	// IMP=0x0000000100133bd0
- (id)objectDictionaryForUuid:(id)arg1 propertiesToFetch:(id)arg2 entityName:(id)arg3;	// IMP=0x0000000100133adc
- (id)objectDictionaryForUuid:(id)arg1 entityName:(id)arg2;	// IMP=0x0000000100133a74
- (id)objectDictionariesInEntity:(id)arg1 predicate:(id)arg2 sortDescriptors:(id)arg3 propertiesToFetch:(id)arg4 includeObjectId:(_Bool)arg5 limit:(unsigned long long)arg6 distinct:(_Bool)arg7 groupBy:(id)arg8;	// IMP=0x00000001001337e4
- (id)objectDictionariesInEntity:(id)arg1 predicate:(id)arg2 sortDescriptors:(id)arg3 propertiesToFetch:(id)arg4 includeObjectId:(_Bool)arg5;	// IMP=0x0000000100133724
- (id)_predicateForUuid:(id)arg1;	// IMP=0x00000001001336ec
- (id)_objectsInEntity:(id)arg1 predicate:(id)arg2 sortDescriptors:(id)arg3 resultType:(unsigned long long)arg4 returnsObjectsAsFaults:(_Bool)arg5 limit:(long long)arg6 propertiesToFetch:(id)arg7 batchSize:(unsigned long long)arg8;	// IMP=0x00000001001332e4
- (id)_objectsInEntity:(id)arg1 predicate:(id)arg2 sortDescriptors:(id)arg3 resultType:(unsigned long long)arg4 returnsObjectsAsFaults:(_Bool)arg5 limit:(long long)arg6;	// IMP=0x0000000100133230
- (id)objectForUuid:(id)arg1 entityName:(id)arg2;	// IMP=0x00000001001331c8
- (id)objectForUuid:(id)arg1 entityName:(id)arg2 returnsObjectAsFault:(_Bool)arg3;	// IMP=0x0000000100132f98
- (id)objectsInEntity:(id)arg1 predicate:(id)arg2 sortDescriptors:(id)arg3 returnsObjectsAsFaults:(_Bool)arg4 limit:(long long)arg5;	// IMP=0x0000000100132efc
- (id)objectsInEntity:(id)arg1 predicate:(id)arg2 sortDescriptors:(id)arg3 returnsObjectsAsFaults:(_Bool)arg4;	// IMP=0x0000000100132e64
- (id)objectsInEntity:(id)arg1 predicate:(id)arg2 propertiesToFetch:(id)arg3 batchSize:(unsigned long long)arg4;	// IMP=0x0000000100132db8
- (id)objectsInEntity:(id)arg1 predicate:(id)arg2 sortDescriptors:(id)arg3;	// IMP=0x0000000100132d2c
- (id)objectIdForUuid:(id)arg1 entityName:(id)arg2;	// IMP=0x0000000100132afc
- (id)objectIdsInEntity:(id)arg1 predicate:(id)arg2 sortDescriptors:(id)arg3;	// IMP=0x0000000100132a70
- (void)performBlockAndWaitWithSave:(CDUnknownBlockType)arg1;	// IMP=0x000000010013299c
- (_Bool)saveInCurrentBlock;	// IMP=0x0000000100132908
- (id)valueForProperty:(id)arg1 episodeUuid:(id)arg2;	// IMP=0x0000000100136b58
- (id)dictionaryWithProperties:(id)arg1 episodeUuid:(id)arg2;	// IMP=0x0000000100136ae8
- (id)dictionaryForEpisodeUuid:(id)arg1;	// IMP=0x0000000100136ad0
- (id)episodeForUuid:(id)arg1;	// IMP=0x0000000100136ab8
- (id)episodeForUuid:(id)arg1 returnsObjectAsFault:(_Bool)arg2;	// IMP=0x0000000100136a9c
- (id)episodeIdWithUuid:(id)arg1;	// IMP=0x0000000100136a84
- (id)existingEpisodeWithID:(id)arg1;	// IMP=0x0000000100136a00
- (unsigned long long)_nextSortOrderWithRequest:(id)arg1;	// IMP=0x0000000100183048
- (unsigned long long)nextSortOrderForNotSubscribedPodcasts;	// IMP=0x0000000100182ecc
- (unsigned long long)nextSortOrderForSubscribedPodcasts;	// IMP=0x0000000100182d50
- (unsigned long long)countOfPodcasts;	// IMP=0x0000000100182c9c
- (id)valueForProperty:(id)arg1 podcastUuid:(id)arg2;	// IMP=0x0000000100182c2c
- (id)dictionaryWithProperties:(id)arg1 podcastUuid:(id)arg2;	// IMP=0x0000000100182bbc
- (id)dictionaryForPodcastUuid:(id)arg1;	// IMP=0x0000000100182ba4
- (id)podcastForFeedUrl:(id)arg1;	// IMP=0x00000001001829e0
- (id)podcastForPodcastPID:(long long)arg1;	// IMP=0x0000000100182830
- (id)podcastForUuid:(id)arg1;	// IMP=0x0000000100182818
- (id)podcastIdWithUuid:(id)arg1;	// IMP=0x0000000100182800
- (id)existingPodcastWithID:(id)arg1;	// IMP=0x0000000100182610

// Remaining properties
@property(retain, nonatomic) NSString *name;
@end

