//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep  6 2019 11:16:02).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface NSObject (IMAccessibilitySafeCategory)
- (id)imaxUnignoredDescendant;	// IMP=0x00000001001ba510
- (id)imaxDescendentOfType:(Class)arg1;	// IMP=0x00000001001ba494
- (id)_accessibilityFindDescendant:(CDUnknownBlockType)arg1;	// IMP=0x00000001001ba1a0
- (id)imaxAncestorIsKindOf:(Class)arg1;	// IMP=0x00000001001ba124
- (id)imaxElementIsAncestor:(id)arg1;	// IMP=0x00000001001ba070
- (id)_imaxFindAncestor:(CDUnknownBlockType)arg1;	// IMP=0x00000001001b9fb8
- (_Bool)imaxBoolForKey:(id)arg1;	// IMP=0x00000001001b9f44
- (id)imaxValueForKeyPath:(id)arg1;	// IMP=0x00000001001b9ed0
- (id)imaxValueForKey:(id)arg1;	// IMP=0x00000001001b9e5c
- (id)imaxStorageValueForKey:(id)arg1;	// IMP=0x00000001001b9df8
- (void)imaxStorageSetRetainedValue:(id)arg1 forKey:(id)arg2;	// IMP=0x00000001001b9d88
- (void)imaxSetIdentification:(id)arg1;	// IMP=0x00000001001b9d78
- (id)imaxIdentification;	// IMP=0x00000001001b9d6c
@end

