//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep  6 2019 11:16:02).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSPredicate.h>

@interface NSPredicate (MTAdditions)
+ (id)predicateForDateKey:(id)arg1 isLessThanDate:(id)arg2;	// IMP=0x0000000100164ec4
+ (id)predicateForDateKey:(id)arg1 isGreaterThanDate:(id)arg2;	// IMP=0x0000000100164e58
+ (id)predicateForDateKey:(id)arg1 isLessThanOrEqualToDate:(id)arg2;	// IMP=0x0000000100164dec
+ (id)predicateForDateKey:(id)arg1 isGreaterThanOrEqualToDate:(id)arg2;	// IMP=0x0000000100164d80
+ (id)truePredicate;	// IMP=0x0000000100164d64
+ (id)falsePredicate;	// IMP=0x0000000100164d48
- (id)OR:(id)arg1;	// IMP=0x0000000100164c78
- (id)AND:(id)arg1;	// IMP=0x0000000100164b98
@end

