//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSPredicate.h>

@interface NSPredicate (MTAdditions)
+ (id)predicateForDateKey:(id)arg1 isLessThanDate:(id)arg2;	// IMP=0x0000000100164ec4
+ (id)predicateForDateKey:(id)arg1 isGreaterThanDate:(id)arg2;	// IMP=0x0000000100164e58
+ (id)predicateForDateKey:(id)arg1 isLessThanOrEqualToDate:(id)arg2;	// IMP=0x0000000100164dec
+ (id)predicateForDateKey:(id)arg1 isGreaterThanOrEqualToDate:(id)arg2;	// IMP=0x0000000100164d80
+ (id)truePredicate;	// IMP=0x0000000100164d64
+ (id)falsePredicate;	// IMP=0x0000000100164d48
- (id)OR:(id)arg1;	// IMP=0x0000000100164c78
- (id)AND:(id)arg1;	// IMP=0x0000000100164b98
@end

