//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep  6 2019 11:16:02).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UINavigationBar.h>

@interface UINavigationBar (AMP_UITraitCollectionOverrides)
- (void)setLayoutDirection:(long long)arg1;	// IMP=0x00000001000da11c
@end

