//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "PBSViewServicePresenter-Protocol.h"
#import "TVSMSystemMenuManagerDelegate-Protocol.h"

@class NSString, TVSMMainViewController;

@interface TVSMHostViewController : UIViewController <PBSViewServicePresenter, TVSMSystemMenuManagerDelegate>
{
    TVSMMainViewController *_mainViewController;	// 8 = 0x8
}

+ (id)_remoteViewControllerInterface;	// IMP=0x00000001000095a0
+ (id)_exportedInterface;	// IMP=0x00000001000094a0
- (void).cxx_destruct;	// IMP=0x00000001000095cc
@property(readonly, nonatomic) TVSMMainViewController *mainViewController; // @synthesize mainViewController=_mainViewController;
- (void)viewServiceEndPresentationWithOptions:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100009250
- (void)viewServiceBeginPresentationWithOptions:(id)arg1;	// IMP=0x00000001000090c4
- (void)systemMenuManagerRequestedDismissal:(id)arg1;	// IMP=0x0000000100009080
- (id)preferredFocusEnvironments;	// IMP=0x0000000100008ff0
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x0000000100008f20

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

