//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TVContentPartnerKitUI/TVCKStoreAppDelegate.h>

@interface TVMoviesAppDelegate : TVCKStoreAppDelegate
{
}

- (id)mediaType;	// IMP=0x0000000100003a84
- (_Bool)application:(id)arg1 openURL:(id)arg2 options:(id)arg3;	// IMP=0x00000001000036a4
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;	// IMP=0x0000000100003554

@end

