//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep  6 2019 11:16:02).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ASTSessionDelegate-Protocol.h"

@class ASTSession, NSData, NSURL;

@protocol ASTSessionSigningDelegate <ASTSessionDelegate>
- (void)session:(ASTSession *)arg1 generateAuthInfoWithNonce:(NSData *)arg2;

@optional
- (void)session:(ASTSession *)arg1 signFile:(NSURL *)arg2 completionHandler:(void (^)(NSData *, NSError *))arg3;
- (void)session:(ASTSession *)arg1 signPayload:(NSData *)arg2 completionHandler:(void (^)(NSData *, NSError *))arg3;
@end

