//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import "CAAnimationDelegate-Protocol.h"

@class CAShapeLayer, NSString, UIColor;

@interface DACheckAnimationView : UIView <CAAnimationDelegate>
{
    UIColor *_strokeColor;	// 8 = 0x8
    CAShapeLayer *_check;	// 16 = 0x10
    CDUnknownBlockType _animationCompletion;	// 24 = 0x18
}

+ (Class)layerClass;	// IMP=0x000000010001a0ec
- (void).cxx_destruct;	// IMP=0x000000010001a638
@property(copy, nonatomic) CDUnknownBlockType animationCompletion; // @synthesize animationCompletion=_animationCompletion;
@property(retain, nonatomic) CAShapeLayer *check; // @synthesize check=_check;
@property(retain, nonatomic) UIColor *strokeColor; // @synthesize strokeColor=_strokeColor;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;	// IMP=0x000000010001a550
- (void)playCheckAnimationWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010001a338
- (void)layoutSubviews;	// IMP=0x000000010001a208
- (void)_dynamicUserInterfaceTraitDidChange;	// IMP=0x000000010001a180
- (void)showCheck;	// IMP=0x000000010001a13c
- (void)hideCheck;	// IMP=0x000000010001a0f8
- (id)initWithColor:(id)arg1 lineWidth:(double)arg2 scale:(double)arg3;	// IMP=0x000000010001a068
- (id)initWithFrame:(struct CGRect)arg1 color:(id)arg2 scale:(double)arg3;	// IMP=0x0000000100019c9c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

