//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep  6 2019 11:16:02).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSObject;
@protocol NSCopying;

@protocol DADeviceObserver <NSObject>
- (void)discoverAllDevicesWithCompletionHandler:(void (^)(NSSet *))arg1;
- (void)endDiscoveringDevicesWithIdentifier:(NSObject<NSCopying> *)arg1;
- (NSObject<NSCopying> *)beginDiscoveringDevicesWithHandler:(void (^)(NSSet *))arg1;
@end

