//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "DADevice-Protocol.h"
#import "DADeviceConnectionDelegate-Protocol.h"
#import "DATestQueueDelegate-Protocol.h"
#import "DKAssetResponder-Protocol.h"

@class DADeviceState, DATestQueue, DKDiagnosticManager, DKReportManager, NSString;
@protocol DADeviceConnection;

@interface DADeviceLocal : NSObject <DKAssetResponder, DADeviceConnectionDelegate, DATestQueueDelegate, DADevice>
{
    _Bool _testsSuspended;	// 8 = 0x8
    NSString *_bundleIdentifier;	// 16 = 0x10
    id <DADeviceConnection> _connection;	// 24 = 0x18
    DKDiagnosticManager *_diagnosticsManager;	// 32 = 0x20
    DKReportManager *_reportManager;	// 40 = 0x28
    DATestQueue *_testQueue;	// 48 = 0x30
    DADeviceState *_state;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x000000010000e24c
@property(retain, nonatomic) DADeviceState *state; // @synthesize state=_state;
@property(retain, nonatomic) DATestQueue *testQueue; // @synthesize testQueue=_testQueue;
@property(nonatomic, getter=areTestsSuspended) _Bool testsSuspended; // @synthesize testsSuspended=_testsSuspended;
@property(retain, nonatomic) DKReportManager *reportManager; // @synthesize reportManager=_reportManager;
@property(retain, nonatomic) DKDiagnosticManager *diagnosticsManager; // @synthesize diagnosticsManager=_diagnosticsManager;
@property(retain, nonatomic) id <DADeviceConnection> connection; // @synthesize connection=_connection;
@property(retain, nonatomic) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
- (id)_IMEI;	// IMP=0x000000010000e1c0
- (id)_userAssignedName;	// IMP=0x000000010000e1a0
- (id)_marketingName;	// IMP=0x000000010000e180
- (id)_deviceColor;	// IMP=0x000000010000e100
- (id)_deviceEnclosureColor;	// IMP=0x000000010000e080
- (id)_deviceType;	// IMP=0x000000010000e060
- (id)_deviceClass;	// IMP=0x000000010000e040
- (id)_productClass;	// IMP=0x000000010000e020
- (id)_serialNumber;	// IMP=0x000000010000e000
- (id)_deviceMaskName;	// IMP=0x000000010000df68
- (id)_deviceImageName;	// IMP=0x000000010000de7c
- (id)_deviceAttributes;	// IMP=0x000000010000dac0
- (void)getAsset:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010000d90c
- (void)deviceConnection:(id)arg1 didRecieveCommand:(id)arg2;	// IMP=0x000000010000d894
- (void)profileWithCommand:(id)arg1;	// IMP=0x000000010000cea0
- (void)cancelTestWithCommand:(id)arg1;	// IMP=0x000000010000ce08
- (void)startTestWithCommand:(id)arg1;	// IMP=0x000000010000cc34
- (void)executeTestWithTestAttributes:(id)arg1 parameters:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010000cb60
- (void)end;	// IMP=0x000000010000c9c8
- (void)resumeTests;	// IMP=0x000000010000c8e8
- (void)suspendTests;	// IMP=0x000000010000c7d8
- (void)idle;	// IMP=0x000000010000c798
- (void)start;	// IMP=0x000000010000c758
- (void)connect;	// IMP=0x000000010000c754
@property(readonly, nonatomic, getter=isLocal) _Bool local;
@property(readonly, copy) NSString *description;
- (_Bool)isEqual:(id)arg1;	// IMP=0x000000010000c57c
@property(readonly) unsigned long long hash;
- (id)init;	// IMP=0x000000010000c2d4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

