//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSURL.h>

#import "TVHJSURL-Protocol.h"

@class NSDictionary, NSString;

@interface NSURL (TVHomeSharing) <TVHJSURL>
- (id)tvh_resourceName;	// IMP=0x0000000100009090
- (_Bool)tvh_isResourceURL;	// IMP=0x000000010000903c

// Remaining properties
@property(readonly, copy) NSString *absoluteString;
@property(readonly, copy) NSDictionary *decodedQueryParameters;
@property(readonly, copy) NSString *host;
@property(readonly, copy) NSDictionary *queryParameters;
@end

