//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSValueTransformer.h>

@class IKAppContext;

@interface TVHAppContextValueTransformer : NSValueTransformer
{
    IKAppContext *_appContext;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010000d810
@property(retain, nonatomic) IKAppContext *appContext; // @synthesize appContext=_appContext;
- (id)initWithAppContext:(id)arg1;	// IMP=0x000000010000d76c
- (id)init;	// IMP=0x000000010000d6e4

@end

