//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ITMLKit/IKJSObject.h>

#import "TVHJSMediaServerDiscoveryConfiguration-Protocol.h"

@class NSString, TVHSMediaServerDiscoveryConfiguration;

@interface TVHJSMediaServerDiscoveryConfiguration : IKJSObject <TVHJSMediaServerDiscoveryConfiguration>
{
    TVHSMediaServerDiscoveryConfiguration *_mediaServerDiscoveryConfiguration;	// 8 = 0x8
}

+ (id)_javascriptStringForMediaServerDiscoveryMode:(unsigned long long)arg1;	// IMP=0x0000000100010c1c
- (void).cxx_destruct;	// IMP=0x0000000100010c6c
@property(copy, nonatomic) TVHSMediaServerDiscoveryConfiguration *mediaServerDiscoveryConfiguration; // @synthesize mediaServerDiscoveryConfiguration=_mediaServerDiscoveryConfiguration;
@property(readonly, copy, nonatomic) NSString *homeSharingAccountName;
@property(readonly, copy, nonatomic) NSString *homeSharingGroupIdentifier;
@property(readonly, nonatomic) _Bool discoveringDAAPServers;
@property(readonly, nonatomic) _Bool discoveringHomeShareServers;
@property(readonly, nonatomic) _Bool discoveringMediaServers;
@property(readonly, copy, nonatomic) NSString *discoveryMode;
- (id)description;	// IMP=0x00000001000109c4
- (id)initWithMediaServerDiscoveryConfigutation:(id)arg1 appContext:(id)arg2;	// IMP=0x000000010001092c

@end

