//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "JSExport-Protocol.h"

@class JSValue, NSArray, NSString, TVHJSAsynchronousWorkToken, TVHJSMediaEntityFetchRequest;

@protocol TVHJSMediaServer <JSExport>
@property(readonly, copy, nonatomic) NSString *connectionState;
@property(readonly, copy, nonatomic) NSString *identifier;
@property(readonly, copy, nonatomic) NSString *name;
@property(readonly, copy, nonatomic) NSString *type;
- (void)unregisterConnectionStateDidChangeCallback:(JSValue *)arg1;
- (void)registerConnectionStateDidChangeCallback:(JSValue *)arg1;
- (void)unregisterContentsDidChangeCallback:(JSValue *)arg1;
- (void)registerContentsDidChangeCallback:(JSValue *)arg1;
- (TVHJSAsynchronousWorkToken *)enqueueFetchRequest:(TVHJSMediaEntityFetchRequest *)arg1:(NSArray *)arg2:(JSValue *)arg3;
- (void)connect;
@end

