//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep  6 2019 11:16:02).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JSExport-Protocol.h"

@class NSArray;

@protocol TVHJSCollectionComparator <JSExport>
- (NSArray *)mediaEntityChanges:(NSArray *)arg1:(NSArray *)arg2;
- (NSArray *)mediaServersChanges:(NSArray *)arg1:(NSArray *)arg2;
- (NSArray *)changes:(NSArray *)arg1:(NSArray *)arg2;
- (id)init;
@end

