//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "JSExport-Protocol.h"

@class NSArray, NSString, TVHJSMediaServer, TVHJSMediaServerDiscoveryConfiguration;

@protocol TVHJSMediaServerManager <JSExport>
@property(readonly, copy, nonatomic) NSArray *browseableMediaServers;
@property(readonly, copy, nonatomic) NSArray *mediaServers;
@property(readonly, nonatomic) TVHJSMediaServerDiscoveryConfiguration *mediaServerDiscoveryConfiguration;
- (void)updateSettingsForMediaServer:(TVHJSMediaServer *)arg1:(NSString *)arg2;
- (TVHJSMediaServer *)mediaServerWithIdentifier:(NSString *)arg1;
- (void)restartMediaServerDiscovery;
@end

