//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "JSExport-Protocol.h"

@class NSDictionary, NSString, TVHJSMediaQueryResult;

@protocol TVHJSMediaEntityFetchControllerResult <JSExport>
@property(readonly, nonatomic) NSDictionary *groupingsResult;
@property(readonly, nonatomic) TVHJSMediaQueryResult *unplayedMediaEntitiesResult;
@property(readonly, nonatomic) TVHJSMediaQueryResult *recentlyAddedMediaEntitiesResult;
@property(readonly, nonatomic) TVHJSMediaQueryResult *mediaEntitiesResult;
@property(readonly, copy, nonatomic) NSString *queryReason;
@end

