//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep  6 2019 11:16:02).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError, TVHKMediaEntitySearchController, TVHKMediaEntitySearchControllerResult, TVHKMediaEntitySearchRequest;

@protocol TVHKMediaEntitySearchControllerDelegate <NSObject>
- (void)controller:(TVHKMediaEntitySearchController *)arg1 searchRequest:(TVHKMediaEntitySearchRequest *)arg2 didFailWithError:(NSError *)arg3;
- (void)controller:(TVHKMediaEntitySearchController *)arg1 searchRequest:(TVHKMediaEntitySearchRequest *)arg2 didCompleteWithResult:(TVHKMediaEntitySearchControllerResult *)arg3;
@end

