//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError, TVHKMediaEntityFetchController, TVHKMediaEntityFetchControllerResult, TVHKMediaEntityFetchRequest, TVHSMediaServerContentsChange;

@protocol TVHKMediaEntityFetchControllerDelegate <NSObject>
- (void)controller:(TVHKMediaEntityFetchController *)arg1 fetchRequest:(TVHKMediaEntityFetchRequest *)arg2 didFailWithError:(NSError *)arg3;
- (void)controller:(TVHKMediaEntityFetchController *)arg1 fetchRequest:(TVHKMediaEntityFetchRequest *)arg2 didCompleteWithResult:(TVHKMediaEntityFetchControllerResult *)arg3;

@optional
- (unsigned long long)controller:(TVHKMediaEntityFetchController *)arg1 shouldRefetchForContentsChange:(TVHSMediaServerContentsChange *)arg2;
@end

