//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIColor, UIFont, UIImageView, UILabel;

@interface TVHMediaItemTitleView : UIView
{
    UILabel *_titleLabel;	// 8 = 0x8
    UIImageView *_contentRatingBadgeImageView;	// 16 = 0x10
    UIImageView *_videoBadgeImageView;	// 24 = 0x18
    UIImageView *_highDefinitionBadgeImageView;	// 32 = 0x20
}

+ (id)_videoBadgeImageViewFromViewElement:(id)arg1 titleTextColor:(id)arg2 existingImageView:(id)arg3;	// IMP=0x000000010000af8c
+ (id)_highDefinitionBadgeImageViewFromViewElement:(id)arg1 titleTextColor:(id)arg2 existingImageView:(id)arg3;	// IMP=0x000000010000ae2c
+ (id)_contentRatingBadgeImageViewFromViewElement:(id)arg1 titleTextColor:(id)arg2 existingImageView:(id)arg3;	// IMP=0x000000010000ac14
- (void).cxx_destruct;	// IMP=0x000000010000b2c0
@property(retain, nonatomic) UIImageView *highDefinitionBadgeImageView; // @synthesize highDefinitionBadgeImageView=_highDefinitionBadgeImageView;
@property(retain, nonatomic) UIImageView *videoBadgeImageView; // @synthesize videoBadgeImageView=_videoBadgeImageView;
@property(retain, nonatomic) UIImageView *contentRatingBadgeImageView; // @synthesize contentRatingBadgeImageView=_contentRatingBadgeImageView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void)layoutSubviews;	// IMP=0x000000010000a744
@property(nonatomic) _Bool marqueeEnabled;
@property(retain, nonatomic) UIColor *titleTextColor;
@property(retain, nonatomic) UIFont *titleFont;
- (void)updateWithViewElement:(id)arg1;	// IMP=0x0000000100009fa8
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100009f10

@end

