//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface TVHViewFactory : NSObject
{
}

- (id)_playedStateImageViewForElement:(id)arg1 existingView:(id)arg2;	// IMP=0x000000010002bf30
- (id)_mediaItemTitleViewForElement:(id)arg1 existingView:(id)arg2;	// IMP=0x000000010002be80
- (id)_episodeListViewCellForElement:(id)arg1 existingView:(id)arg2;	// IMP=0x000000010002bdd0
- (id)_playlistItemListViewCellForElement:(id)arg1 existingView:(id)arg2;	// IMP=0x000000010002bd20
- (id)_musicAlbumItemListViewCellForElement:(id)arg1 existingView:(id)arg2;	// IMP=0x000000010002bc70
- (id)_musicSongListViewCellForElement:(id)arg1 existingView:(id)arg2;	// IMP=0x000000010002bbc0
- (void)_registerViewCreators;	// IMP=0x000000010002b51c
- (id)init;	// IMP=0x000000010002b4c4

@end

