//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep  6 2019 11:16:02).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImage.h>

@interface UIImage (TVHomeSharing)
+ (id)tvh_tvmlKitImageNamed:(id)arg1;	// IMP=0x000000010000c954
@end

